using System.Collections;
using System.Collections.Generic;
using System.Linq;

public struct Bag
{
    public Bag(int count, string name)
    {
        Count = count;
        Name = name;
    }

    public int Count { get; set; }
    public string Name { get; set; }
}

public class Day7
{
    static string ShinyBagToken = "shiny gold";

    public static int CanContainShinyBagCount() => Values.Count(v => CanContainShinyBag(v.Key));

    public static int ShinyBagCanContain() => MustContainBagsCount(ShinyBagToken);

    private static bool CanContainShinyBag(string token) 
        => Values[token].Any(bag => bag.Name == ShinyBagToken || CanContainShinyBag(bag.Name));

    private static int MustContainBagsCount(string token)
        => Values[token].Select(bag => bag.Count + bag.Count * MustContainBagsCount(bag.Name)).Sum();

// Used regfexes:
//^([a-z\s]*)bags contain   ->  { "$1", new List<Bag> {
//.$    ->   } },
// ((\d)\s([a-z]*\s[a-z]*)\sbag[s]?)    ->  new Bag($2, "$3")
//no other bags -> 

    public static Dictionary<string, List<Bag>> Values = new Dictionary<string, List<Bag>>()
    {
        //{ "shiny indigo", new List<Bag> { new InsBag(4, "vibrant lime" ) } },
        //{ "clear lime", new List<Bag> { new InsBag (1, "dotted lime" ), new InsBag (2, "clear gold" ) } },
        { "shiny indigo", new List<Bag> { new Bag(4, "vibrant lime") } },
        { "clear lime", new List<Bag> { new Bag(1, "dotted lime"), new Bag(2, "clear gold") } },
        { "dotted turquoise", new List<Bag> { new Bag(2, "shiny green"), new Bag(5, "striped magenta"), new Bag(3, "muted green") } },
        { "bright red", new List<Bag> { new Bag(1, "plaid magenta"), new Bag(3, "light cyan") } },
        { "vibrant magenta", new List<Bag> { new Bag(5, "drab lime"), new Bag(3, "muted red"), new Bag(3, "wavy turquoise"), new Bag(3, "mirrored salmon") } },
        { "plaid violet", new List<Bag> { new Bag(4, "plaid indigo"), new Bag(1, "mirrored beige") } },
        { "muted gray", new List<Bag> { new Bag(2, "striped crimson"), new Bag(2, "striped maroon"), new Bag(1, "faded maroon"), new Bag(4, "dim lavender") } },
        { "mirrored crimson", new List<Bag> { new Bag(5, "muted lavender") } },
        { "muted gold", new List<Bag> { new Bag(3, "striped plum"), new Bag(4, "bright coral") } },
        { "pale black", new List<Bag> { new Bag(4, "shiny orange"), new Bag(3, "pale bronze"), new Bag(2, "wavy coral") } },
        { "muted purple", new List<Bag> { new Bag(5, "muted brown") } },
        { "clear cyan", new List<Bag> { new Bag(4, "muted white") } },
        { "shiny blue", new List<Bag> { new Bag(5, "pale magenta"), new Bag(3, "drab coral") } },
        { "posh white", new List<Bag> { new Bag(3, "posh brown"), new Bag(3, "striped gold"), new Bag(1, "faded gray") } },
        { "muted beige", new List<Bag> { new Bag(1, "pale teal") } },
        { "clear purple", new List<Bag> { new Bag(4, "plaid turquoise") } },
        { "pale gold", new List<Bag> { new Bag(1, "mirrored lime"), new Bag(2, "dim crimson"), new Bag(3, "dim aqua"), new Bag(2, "dull silver") } },
        { "pale beige", new List<Bag> { new Bag(4, "drab olive"), new Bag(2, "wavy coral") } },
        { "drab black", new List<Bag> { new Bag(4, "mirrored blue"), new Bag(2, "light olive") } },
        { "faded purple", new List<Bag> { new Bag(3, "dim lime"), new Bag(2, "vibrant violet") } },
        { "pale silver", new List<Bag> { new Bag(3, "light cyan") } },
        { "plaid teal", new List<Bag> { new Bag(3, "dotted fuchsia"), new Bag(3, "bright teal") } },
        { "plaid beige", new List<Bag> { new Bag(5, "shiny black"), new Bag(3, "dotted maroon") } },
        { "light silver", new List<Bag> { new Bag(3, "posh chartreuse"), new Bag(4, "dark bronze"), new Bag(1, "vibrant silver"), new Bag(2, "muted coral") } },
        { "pale plum", new List<Bag> { new Bag(5, "drab silver"), new Bag(4, "light crimson") } },
        { "striped cyan", new List<Bag> { new Bag(3, "wavy tan"), new Bag(5, "pale teal"), new Bag(5, "clear orange"), new Bag(3, "wavy violet") } },
        { "plaid red", new List<Bag> { new Bag(2, "dim lavender"), new Bag(4, "striped maroon") } },
        { "dark salmon", new List<Bag> { new Bag(5, "bright gold"), new Bag(5, "muted lavender"), new Bag(5, "light beige") } },
        { "shiny purple", new List<Bag> { new Bag(2, "plaid silver"), new Bag(2, "mirrored green"), new Bag(3, "bright violet") } },
        { "shiny turquoise", new List<Bag> { new Bag(1, "vibrant salmon") } },
        { "muted orange", new List<Bag> { new Bag(2, "striped indigo"), new Bag(1, "striped crimson") } },
        { "pale turquoise", new List<Bag> { new Bag(3, "light silver"), new Bag(5, "light crimson") } },
        { "light indigo", new List<Bag> { new Bag(4, "vibrant white"), new Bag(5, "plaid yellow") } },
        { "faded coral", new List<Bag> { new Bag(1, "vibrant beige"), new Bag(4, "muted white") } },
        { "dim red", new List<Bag> { new Bag(1, "mirrored cyan"), new Bag(2, "wavy indigo"), new Bag(5, "shiny chartreuse"), new Bag(5, "muted yellow") } },
        { "striped fuchsia", new List<Bag> { new Bag(2, "faded salmon"), new Bag(1, "pale beige"), new Bag(2, "posh magenta"), new Bag(2, "wavy green") } },
        { "bright green", new List<Bag> { new Bag(4, "pale turquoise"), new Bag(2, "bright chartreuse"), new Bag(5, "posh yellow"), new Bag(4, "shiny gold") } },
        { "light blue", new List<Bag> { new Bag(5, "dim silver") } },
        { "vibrant purple", new List<Bag> { new Bag(3, "wavy indigo"), new Bag(1, "pale maroon"), new Bag(3, "drab chartreuse"), new Bag(5, "vibrant aqua") } },
        { "light coral", new List<Bag> { new Bag(2, "clear orange"), new Bag(3, "shiny fuchsia"), new Bag(3, "striped chartreuse") } },
        { "striped maroon", new List<Bag> { new Bag(4, "vibrant tomato"), new Bag(2, "dull salmon"), new Bag(1, "shiny gold"), new Bag(2, "muted coral") } },
        { "drab lime", new List<Bag> { new Bag(1, "mirrored violet"), new Bag(4, "posh magenta") } },
        { "dotted gold", new List<Bag> { new Bag(3, "muted silver") } },
        { "pale magenta", new List<Bag> { new Bag(5, "mirrored orange"), new Bag(4, "pale teal") } },
        { "dim olive", new List<Bag> {  } },
        { "mirrored blue", new List<Bag> { new Bag(1, "dim indigo"), new Bag(4, "bright lime"), new Bag(1, "plaid beige") } },
        { "plaid bronze", new List<Bag> { new Bag(3, "pale gold") } },
        { "faded aqua", new List<Bag> { new Bag(3, "muted aqua"), new Bag(3, "muted gray"), new Bag(4, "dim olive") } },
        { "light gold", new List<Bag> { new Bag(1, "mirrored crimson"), new Bag(3, "pale tan"), new Bag(3, "dotted yellow"), new Bag(2, "wavy aqua") } },
        { "dim gold", new List<Bag> { new Bag(4, "plaid tomato") } },
        { "faded chartreuse", new List<Bag> { new Bag(5, "muted coral"), new Bag(4, "vibrant indigo"), new Bag(1, "faded teal"), new Bag(1, "vibrant bronze") } },
        { "posh brown", new List<Bag> { new Bag(2, "muted gray"), new Bag(1, "dark plum"), new Bag(3, "bright lime"), new Bag(2, "dull turquoise") } },
        { "mirrored lime", new List<Bag> { new Bag(1, "shiny indigo"), new Bag(4, "dark olive"), new Bag(3, "pale beige") } },
        { "posh cyan", new List<Bag> { new Bag(3, "pale olive") } },
        { "dark lime", new List<Bag> { new Bag(3, "shiny cyan"), new Bag(4, "bright green") } },
        { "drab lavender", new List<Bag> { new Bag(4, "drab plum") } },
        { "vibrant orange", new List<Bag> { new Bag(5, "wavy olive") } },
        { "faded violet", new List<Bag> { new Bag(1, "faded aqua"), new Bag(2, "muted gray") } },
        { "light green", new List<Bag> { new Bag(5, "pale brown"), new Bag(4, "dark aqua"), new Bag(5, "vibrant teal"), new Bag(1, "pale black") } },
        { "bright turquoise", new List<Bag> { new Bag(4, "striped teal"), new Bag(2, "dim magenta"), new Bag(5, "striped orange"), new Bag(4, "bright aqua") } },
        { "mirrored indigo", new List<Bag> { new Bag(2, "wavy violet"), new Bag(2, "muted white"), new Bag(2, "dim lavender") } },
        { "wavy green", new List<Bag> { new Bag(5, "dotted teal") } },
        { "light aqua", new List<Bag> { new Bag(4, "posh lime"), new Bag(1, "dotted maroon"), new Bag(3, "dotted gray"), new Bag(2, "plaid bronze") } },
        { "muted tomato", new List<Bag> { new Bag(3, "mirrored tomato"), new Bag(3, "pale blue"), new Bag(2, "mirrored violet"), new Bag(4, "drab tomato") } },
        { "posh beige", new List<Bag> { new Bag(5, "faded aqua") } },
        { "shiny coral", new List<Bag> { new Bag(5, "striped gold"), new Bag(1, "drab coral"), new Bag(2, "light lavender"), new Bag(4, "striped blue") } },
        { "posh orange", new List<Bag> { new Bag(5, "dark olive"), new Bag(3, "light silver"), new Bag(3, "striped gray"), new Bag(2, "faded fuchsia") } },
        { "posh violet", new List<Bag> { new Bag(2, "drab turquoise"), new Bag(5, "mirrored gray") } },
        { "pale brown", new List<Bag> { new Bag(2, "bright chartreuse") } },
        { "shiny green", new List<Bag> { new Bag(2, "mirrored magenta") } },
        { "faded salmon", new List<Bag> { new Bag(2, "wavy tan") } },
        { "dark gold", new List<Bag> {  } },
        { "clear black", new List<Bag> { new Bag(5, "vibrant lime") } },
        { "muted fuchsia", new List<Bag> { new Bag(1, "pale fuchsia"), new Bag(4, "mirrored white"), new Bag(3, "clear fuchsia"), new Bag(3, "faded maroon") } },
        { "drab fuchsia", new List<Bag> { new Bag(1, "bright chartreuse"), new Bag(3, "pale beige"), new Bag(5, "wavy brown") } },
        { "mirrored plum", new List<Bag> { new Bag(1, "plaid yellow"), new Bag(2, "dim beige"), new Bag(5, "dim aqua"), new Bag(4, "dim crimson") } },
        { "dark maroon", new List<Bag> { new Bag(1, "striped crimson"), new Bag(5, "muted fuchsia"), new Bag(3, "vibrant silver"), new Bag(2, "drab olive") } },
        { "drab green", new List<Bag> { new Bag(5, "faded bronze"), new Bag(2, "bright violet"), new Bag(3, "dark gold") } },
        { "drab purple", new List<Bag> { new Bag(3, "plaid orange"), new Bag(4, "striped black"), new Bag(5, "vibrant indigo"), new Bag(4, "pale turquoise") } },
        { "dotted silver", new List<Bag> { new Bag(1, "clear crimson"), new Bag(2, "faded yellow") } },
        { "dull olive", new List<Bag> { new Bag(3, "muted salmon"), new Bag(2, "vibrant cyan"), new Bag(3, "posh bronze"), new Bag(5, "light cyan") } },
        { "posh gold", new List<Bag> { new Bag(4, "bright violet"), new Bag(1, "drab yellow") } },
        { "dark plum", new List<Bag> { new Bag(4, "clear fuchsia"), new Bag(2, "mirrored aqua") } },
        { "dim purple", new List<Bag> { new Bag(5, "clear chartreuse"), new Bag(4, "dark gold") } },
        { "drab tomato", new List<Bag> { new Bag(5, "mirrored white") } },
        { "mirrored chartreuse", new List<Bag> { new Bag(3, "clear indigo"), new Bag(4, "clear crimson") } },
        { "striped olive", new List<Bag> { new Bag(4, "posh orange"), new Bag(5, "shiny indigo") } },
        { "dark purple", new List<Bag> { new Bag(2, "drab lavender"), new Bag(2, "faded bronze") } },
        { "light purple", new List<Bag> { new Bag(1, "vibrant lime"), new Bag(2, "vibrant gray") } },
        { "mirrored green", new List<Bag> { new Bag(4, "mirrored cyan") } },
        { "bright lavender", new List<Bag> { new Bag(1, "dark red"), new Bag(2, "clear yellow"), new Bag(3, "bright brown"), new Bag(2, "bright teal") } },
        { "posh tomato", new List<Bag> { new Bag(4, "posh silver"), new Bag(3, "shiny black"), new Bag(4, "clear crimson"), new Bag(3, "dotted chartreuse") } },
        { "dotted coral", new List<Bag> { new Bag(4, "dotted bronze"), new Bag(5, "dotted maroon") } },
        { "pale cyan", new List<Bag> { new Bag(2, "dim coral"), new Bag(4, "dotted brown") } },
        { "plaid gold", new List<Bag> { new Bag(4, "bright chartreuse"), new Bag(4, "faded bronze") } },
        { "bright tan", new List<Bag> { new Bag(3, "bright brown") } },
        { "dim chartreuse", new List<Bag> { new Bag(2, "clear maroon"), new Bag(3, "pale tan"), new Bag(2, "mirrored lime"), new Bag(1, "wavy crimson") } },
        { "dark bronze", new List<Bag> { new Bag(4, "faded maroon"), new Bag(1, "wavy violet"), new Bag(4, "plaid silver") } },
        { "wavy brown", new List<Bag> { new Bag(4, "light red"), new Bag(2, "dull tomato"), new Bag(5, "mirrored red"), new Bag(4, "bright lime") } },
        { "dim fuchsia", new List<Bag> { new Bag(4, "dark beige") } },
        { "drab bronze", new List<Bag> { new Bag(2, "dotted blue") } },
        { "bright plum", new List<Bag> { new Bag(2, "plaid orange") } },
        { "shiny red", new List<Bag> { new Bag(1, "faded fuchsia") } },
        { "vibrant brown", new List<Bag> { new Bag(3, "faded fuchsia"), new Bag(2, "light plum") } },
        { "pale tan", new List<Bag> { new Bag(3, "dark aqua"), new Bag(3, "dark plum"), new Bag(1, "mirrored green") } },
        { "dull aqua", new List<Bag> { new Bag(3, "muted cyan"), new Bag(5, "drab cyan") } },
        { "dark teal", new List<Bag> { new Bag(1, "light red"), new Bag(4, "plaid silver"), new Bag(2, "dark olive"), new Bag(5, "striped maroon") } },
        { "pale tomato", new List<Bag> { new Bag(4, "dim indigo"), new Bag(4, "dark salmon") } },
        { "faded silver", new List<Bag> { new Bag(5, "dim blue") } },
        { "striped lime", new List<Bag> { new Bag(2, "bright black") } },
        { "plaid coral", new List<Bag> { new Bag(4, "dull salmon"), new Bag(5, "mirrored green"), new Bag(1, "pale aqua") } },
        { "clear white", new List<Bag> { new Bag(4, "drab turquoise"), new Bag(2, "posh coral"), new Bag(5, "dark fuchsia") } },
        { "dark turquoise", new List<Bag> { new Bag(1, "wavy lavender"), new Bag(4, "bright lime") } },
        { "dark tomato", new List<Bag> { new Bag(5, "faded maroon"), new Bag(4, "dark chartreuse"), new Bag(5, "wavy fuchsia"), new Bag(2, "dotted purple") } },
        { "striped bronze", new List<Bag> {  } },
        { "dark black", new List<Bag> { new Bag(2, "dotted chartreuse"), new Bag(3, "pale bronze") } },
        { "dotted teal", new List<Bag> { new Bag(2, "dark teal") } },
        { "drab yellow", new List<Bag> { new Bag(3, "dark turquoise"), new Bag(4, "muted fuchsia") } },
        { "wavy salmon", new List<Bag> { new Bag(2, "plaid turquoise") } },
        { "dull violet", new List<Bag> { new Bag(3, "mirrored red"), new Bag(5, "shiny black"), new Bag(3, "dark maroon") } },
        { "muted cyan", new List<Bag> { new Bag(4, "mirrored black"), new Bag(4, "dim olive"), new Bag(1, "bright chartreuse"), new Bag(1, "clear bronze") } },
        { "clear plum", new List<Bag> { new Bag(4, "light teal"), new Bag(1, "faded white"), new Bag(3, "striped lime") } },
        { "light red", new List<Bag> { new Bag(3, "mirrored orange") } },
        { "pale gray", new List<Bag> { new Bag(5, "wavy cyan"), new Bag(2, "bright green"), new Bag(3, "striped gray") } },
        { "posh green", new List<Bag> { new Bag(3, "clear purple") } },
        { "dark crimson", new List<Bag> { new Bag(5, "bright violet"), new Bag(4, "light magenta"), new Bag(1, "posh chartreuse"), new Bag(1, "shiny gray") } },
        { "dull yellow", new List<Bag> { new Bag(1, "dotted fuchsia"), new Bag(5, "muted maroon"), new Bag(1, "muted salmon") } },
        { "plaid plum", new List<Bag> { new Bag(1, "striped olive") } },
        { "wavy lime", new List<Bag> { new Bag(3, "vibrant silver"), new Bag(5, "shiny gold") } },
        { "dim green", new List<Bag> { new Bag(1, "dark tomato"), new Bag(5, "light red"), new Bag(4, "muted gold") } },
        { "mirrored yellow", new List<Bag> { new Bag(1, "vibrant tomato") } },
        { "dotted yellow", new List<Bag> { new Bag(3, "striped crimson") } },
        { "drab turquoise", new List<Bag> { new Bag(1, "clear indigo"), new Bag(1, "mirrored magenta"), new Bag(4, "clear violet") } },
        { "dim aqua", new List<Bag> { new Bag(3, "wavy coral"), new Bag(1, "posh beige") } },
        { "pale violet", new List<Bag> { new Bag(1, "faded plum"), new Bag(4, "dull purple"), new Bag(2, "pale brown") } },
        { "muted crimson", new List<Bag> { new Bag(3, "dim beige"), new Bag(2, "dim gray") } },
        { "mirrored brown", new List<Bag> { new Bag(1, "dotted tan"), new Bag(4, "dim olive"), new Bag(1, "bright lime") } },
        { "dotted crimson", new List<Bag> { new Bag(5, "striped beige"), new Bag(4, "striped turquoise"), new Bag(3, "shiny fuchsia") } },
        { "mirrored tan", new List<Bag> { new Bag(5, "bright indigo"), new Bag(3, "light violet") } },
        { "striped black", new List<Bag> { new Bag(4, "striped olive") } },
        { "faded fuchsia", new List<Bag> { new Bag(3, "faded teal"), new Bag(4, "dull salmon"), new Bag(3, "light red") } },
        { "dull green", new List<Bag> { new Bag(4, "mirrored coral") } },
        { "vibrant blue", new List<Bag> { new Bag(1, "striped gray"), new Bag(4, "striped olive"), new Bag(3, "wavy brown"), new Bag(3, "faded maroon") } },
        { "vibrant plum", new List<Bag> { new Bag(4, "wavy brown"), new Bag(5, "clear violet"), new Bag(3, "pale turquoise"), new Bag(2, "posh crimson") } },
        { "wavy fuchsia", new List<Bag> { new Bag(5, "wavy olive") } },
        { "striped red", new List<Bag> { new Bag(2, "pale yellow"), new Bag(3, "pale chartreuse"), new Bag(1, "dim blue") } },
        { "muted blue", new List<Bag> { new Bag(2, "posh red"), new Bag(2, "muted red"), new Bag(3, "dark tomato") } },
        { "muted plum", new List<Bag> { new Bag(4, "plaid red") } },
        { "clear violet", new List<Bag> { new Bag(5, "muted salmon") } },
        { "pale white", new List<Bag> { new Bag(3, "plaid lavender"), new Bag(5, "mirrored green") } },
        { "clear beige", new List<Bag> { new Bag(2, "vibrant blue"), new Bag(5, "muted white"), new Bag(2, "dull chartreuse") } },
        { "vibrant fuchsia", new List<Bag> { new Bag(4, "posh gray"), new Bag(5, "dull tomato"), new Bag(3, "dim crimson") } },
        { "dim indigo", new List<Bag> { new Bag(1, "bright black"), new Bag(5, "faded black"), new Bag(5, "dull turquoise"), new Bag(2, "mirrored lime") } },
        { "dotted lime", new List<Bag> { new Bag(3, "light lime"), new Bag(4, "pale salmon"), new Bag(4, "dark aqua") } },
        { "posh teal", new List<Bag> { new Bag(3, "pale gold"), new Bag(2, "faded silver") } },
        { "faded gray", new List<Bag> { new Bag(2, "shiny gold"), new Bag(1, "dull turquoise"), new Bag(1, "faded chartreuse") } },
        { "dim magenta", new List<Bag> { new Bag(2, "mirrored aqua"), new Bag(5, "wavy orange"), new Bag(3, "pale turquoise") } },
        { "shiny fuchsia", new List<Bag> { new Bag(5, "vibrant silver") } },
        { "drab teal", new List<Bag> { new Bag(3, "posh magenta"), new Bag(2, "striped indigo"), new Bag(5, "muted salmon"), new Bag(4, "shiny plum") } },
        { "bright indigo", new List<Bag> { new Bag(2, "faded teal") } },
        { "muted teal", new List<Bag> { new Bag(4, "mirrored green"), new Bag(3, "dull violet"), new Bag(3, "shiny purple") } },
        { "light tan", new List<Bag> { new Bag(1, "muted salmon"), new Bag(1, "plaid olive"), new Bag(2, "plaid silver") } },
        { "striped yellow", new List<Bag> { new Bag(2, "drab salmon"), new Bag(2, "faded aqua") } },
        { "mirrored olive", new List<Bag> { new Bag(5, "clear maroon"), new Bag(2, "striped coral"), new Bag(4, "dim gold") } },
        { "wavy cyan", new List<Bag> { new Bag(3, "plaid lavender"), new Bag(1, "wavy turquoise"), new Bag(2, "plaid bronze"), new Bag(1, "light beige") } },
        { "mirrored red", new List<Bag> {  } },
        { "light yellow", new List<Bag> { new Bag(3, "dim purple"), new Bag(4, "posh green"), new Bag(3, "pale gold") } },
        { "dotted gray", new List<Bag> { new Bag(3, "dotted orange"), new Bag(5, "plaid turquoise"), new Bag(4, "drab magenta") } },
        { "faded red", new List<Bag> { new Bag(3, "bright aqua") } },
        { "dull teal", new List<Bag> { new Bag(4, "clear purple"), new Bag(5, "faded turquoise") } },
        { "light salmon", new List<Bag> { new Bag(3, "posh lime"), new Bag(1, "clear lime"), new Bag(1, "drab chartreuse"), new Bag(3, "clear magenta") } },
        { "dark red", new List<Bag> { new Bag(1, "plaid tomato"), new Bag(1, "plaid orange"), new Bag(4, "dotted white") } },
        { "mirrored beige", new List<Bag> { new Bag(3, "mirrored violet"), new Bag(3, "clear orange"), new Bag(3, "dark olive") } },
        { "drab indigo", new List<Bag> { new Bag(2, "muted aqua"), new Bag(3, "bright teal") } },
        { "light lime", new List<Bag> { new Bag(4, "light indigo"), new Bag(5, "plaid white") } },
        { "pale blue", new List<Bag> { new Bag(3, "wavy tan"), new Bag(1, "mirrored tomato"), new Bag(5, "faded magenta"), new Bag(2, "posh crimson") } },
        { "drab plum", new List<Bag> { new Bag(2, "striped crimson") } },
        { "striped tomato", new List<Bag> { new Bag(1, "dark maroon") } },
        { "faded maroon", new List<Bag> { new Bag(3, "drab salmon"), new Bag(5, "posh lime"), new Bag(4, "dim olive"), new Bag(5, "striped bronze") } },
        { "clear fuchsia", new List<Bag> { new Bag(5, "vibrant silver"), new Bag(5, "posh lime"), new Bag(4, "striped crimson") } },
        { "bright maroon", new List<Bag> { new Bag(2, "dull gray"), new Bag(4, "bright magenta"), new Bag(5, "clear beige"), new Bag(5, "vibrant silver") } },
        { "clear blue", new List<Bag> { new Bag(4, "faded black"), new Bag(2, "plaid magenta"), new Bag(1, "clear salmon"), new Bag(1, "shiny chartreuse") } },
        { "plaid chartreuse", new List<Bag> { new Bag(1, "dark bronze"), new Bag(1, "clear red"), new Bag(2, "mirrored plum"), new Bag(4, "posh white") } },
        { "pale crimson", new List<Bag> { new Bag(4, "muted silver") } },
        { "clear olive", new List<Bag> { new Bag(3, "dark olive"), new Bag(5, "drab plum"), new Bag(2, "striped maroon"), new Bag(5, "shiny purple") } },
        { "vibrant indigo", new List<Bag> { new Bag(1, "vibrant silver"), new Bag(5, "dark olive"), new Bag(1, "striped chartreuse"), new Bag(1, "muted fuchsia") } },
        { "dim coral", new List<Bag> { new Bag(2, "dark yellow"), new Bag(3, "clear orange"), new Bag(2, "clear cyan"), new Bag(1, "pale turquoise") } },
        { "shiny white", new List<Bag> { new Bag(3, "drab teal"), new Bag(3, "vibrant blue") } },
        { "vibrant tan", new List<Bag> { new Bag(3, "posh red"), new Bag(1, "faded black"), new Bag(3, "faded aqua"), new Bag(2, "light beige") } },
        { "wavy plum", new List<Bag> { new Bag(1, "dotted teal"), new Bag(3, "dark indigo") } },
        { "drab coral", new List<Bag> { new Bag(3, "clear orange"), new Bag(4, "shiny red"), new Bag(5, "bright teal") } },
        { "mirrored aqua", new List<Bag> { new Bag(3, "mirrored cyan"), new Bag(5, "wavy coral") } },
        { "vibrant gray", new List<Bag> { new Bag(2, "muted coral"), new Bag(1, "clear fuchsia") } },
        { "faded turquoise", new List<Bag> { new Bag(2, "posh lime") } },
        { "clear green", new List<Bag> { new Bag(4, "posh yellow"), new Bag(3, "light bronze"), new Bag(4, "drab gray"), new Bag(3, "bright teal") } },
        { "wavy gold", new List<Bag> { new Bag(3, "faded black"), new Bag(4, "faded violet") } },
        { "shiny tan", new List<Bag> { new Bag(4, "mirrored gray"), new Bag(3, "mirrored magenta"), new Bag(5, "light red") } },
        { "plaid turquoise", new List<Bag> { new Bag(5, "faded aqua"), new Bag(3, "mirrored tomato"), new Bag(5, "light tan"), new Bag(2, "drab olive") } },
        { "pale bronze", new List<Bag> { new Bag(5, "drab chartreuse"), new Bag(4, "faded lime") } },
        { "mirrored lavender", new List<Bag> { new Bag(3, "plaid green"), new Bag(1, "clear salmon"), new Bag(3, "dim gray") } },
        { "pale yellow", new List<Bag> { new Bag(3, "drab yellow"), new Bag(5, "drab green"), new Bag(1, "drab lavender"), new Bag(1, "clear magenta") } },
        { "mirrored teal", new List<Bag> { new Bag(5, "posh black") } },
        { "vibrant teal", new List<Bag> { new Bag(1, "dark teal") } },
        { "bright gold", new List<Bag> { new Bag(3, "dark green"), new Bag(4, "clear orange"), new Bag(1, "shiny purple"), new Bag(5, "dull chartreuse") } },
        { "muted lavender", new List<Bag> { new Bag(5, "faded fuchsia") } },
        { "light gray", new List<Bag> { new Bag(5, "plaid magenta"), new Bag(3, "vibrant cyan"), new Bag(3, "bright gold"), new Bag(2, "dim cyan") } },
        { "dark gray", new List<Bag> { new Bag(3, "posh silver"), new Bag(1, "dark fuchsia"), new Bag(5, "dark teal"), new Bag(5, "clear fuchsia") } },
        { "mirrored gold", new List<Bag> { new Bag(5, "dim crimson"), new Bag(2, "plaid beige"), new Bag(3, "dark coral") } },
        { "wavy violet", new List<Bag> { new Bag(5, "dull silver"), new Bag(3, "dark gold"), new Bag(5, "striped bronze") } },
        { "vibrant cyan", new List<Bag> { new Bag(2, "bright indigo") } },
        { "dull tan", new List<Bag> { new Bag(2, "shiny indigo"), new Bag(2, "dim gold"), new Bag(5, "vibrant blue"), new Bag(4, "dull tomato") } },
        { "dim orange", new List<Bag> { new Bag(5, "posh silver"), new Bag(3, "light red") } },
        { "drab gold", new List<Bag> { new Bag(4, "shiny indigo"), new Bag(2, "clear indigo"), new Bag(1, "faded fuchsia"), new Bag(1, "muted crimson") } },
        { "vibrant bronze", new List<Bag> { new Bag(3, "mirrored green"), new Bag(2, "striped gold"), new Bag(5, "wavy coral") } },
        { "light violet", new List<Bag> { new Bag(3, "dull turquoise"), new Bag(5, "light white"), new Bag(2, "drab coral") } },
        { "plaid tomato", new List<Bag> { new Bag(1, "wavy tan"), new Bag(2, "faded maroon") } },
        { "faded black", new List<Bag> { new Bag(4, "dark bronze") } },
        { "drab violet", new List<Bag> { new Bag(2, "pale green"), new Bag(5, "muted olive") } },
        { "dull lavender", new List<Bag> { new Bag(5, "light chartreuse"), new Bag(5, "striped fuchsia"), new Bag(2, "clear white"), new Bag(5, "dull indigo") } },
        { "light chartreuse", new List<Bag> { new Bag(5, "dim lavender") } },
        { "dim salmon", new List<Bag> { new Bag(5, "shiny silver"), new Bag(4, "dark coral"), new Bag(2, "vibrant cyan"), new Bag(3, "faded black") } },
        { "posh blue", new List<Bag> { new Bag(4, "clear bronze"), new Bag(5, "shiny aqua"), new Bag(1, "vibrant brown") } },
        { "light crimson", new List<Bag> { new Bag(4, "plaid aqua"), new Bag(3, "mirrored green") } },
        { "striped plum", new List<Bag> { new Bag(5, "plaid white"), new Bag(5, "light beige") } },
        { "shiny bronze", new List<Bag> { new Bag(5, "dark magenta") } },
        { "dark fuchsia", new List<Bag> { new Bag(5, "posh crimson"), new Bag(3, "dark turquoise"), new Bag(1, "vibrant white") } },
        { "striped coral", new List<Bag> { new Bag(5, "dim gray") } },
        { "vibrant gold", new List<Bag> { new Bag(5, "dull tomato"), new Bag(3, "mirrored cyan"), new Bag(2, "light tan") } },
        { "wavy tan", new List<Bag> { new Bag(2, "faded maroon"), new Bag(4, "wavy violet") } },
        { "dotted violet", new List<Bag> { new Bag(5, "shiny blue") } },
        { "faded bronze", new List<Bag> { new Bag(3, "shiny gold") } },
        { "plaid tan", new List<Bag> { new Bag(3, "posh tan"), new Bag(5, "mirrored cyan"), new Bag(1, "drab lavender"), new Bag(4, "shiny blue") } },
        { "plaid salmon", new List<Bag> { new Bag(2, "faded coral") } },
        { "dark orange", new List<Bag> { new Bag(3, "light purple"), new Bag(5, "wavy blue"), new Bag(2, "muted crimson"), new Bag(2, "dull magenta") } },
        { "wavy beige", new List<Bag> { new Bag(1, "muted silver"), new Bag(5, "bright yellow") } },
        { "plaid cyan", new List<Bag> { new Bag(4, "dark orange"), new Bag(5, "dark plum"), new Bag(5, "dotted tomato"), new Bag(5, "striped magenta") } },
        { "dark lavender", new List<Bag> { new Bag(2, "mirrored beige"), new Bag(1, "pale blue"), new Bag(2, "dull chartreuse"), new Bag(5, "mirrored black") } },
        { "light black", new List<Bag> { new Bag(1, "dull tomato"), new Bag(5, "bright violet") } },
        { "wavy silver", new List<Bag> { new Bag(2, "clear gold") } },
        { "wavy maroon", new List<Bag> { new Bag(2, "posh tomato"), new Bag(5, "shiny maroon"), new Bag(1, "wavy yellow") } },
        { "clear lavender", new List<Bag> { new Bag(1, "muted white"), new Bag(5, "striped chartreuse"), new Bag(3, "dark salmon"), new Bag(1, "plaid teal") } },
        { "dotted brown", new List<Bag> { new Bag(4, "striped blue"), new Bag(3, "mirrored fuchsia"), new Bag(3, "posh red") } },
        { "faded teal", new List<Bag> { new Bag(4, "plaid olive") } },
        { "clear gray", new List<Bag> { new Bag(2, "mirrored fuchsia"), new Bag(4, "faded blue") } },
        { "light tomato", new List<Bag> { new Bag(5, "wavy indigo"), new Bag(2, "posh beige") } },
        { "muted black", new List<Bag> { new Bag(1, "dark lime"), new Bag(1, "striped green") } },
        { "dotted beige", new List<Bag> { new Bag(5, "faded lavender"), new Bag(3, "plaid yellow") } },
        { "posh turquoise", new List<Bag> { new Bag(1, "wavy indigo") } },
        { "bright crimson", new List<Bag> { new Bag(1, "dark fuchsia") } },
        { "striped teal", new List<Bag> { new Bag(3, "vibrant olive"), new Bag(1, "bright maroon"), new Bag(3, "muted teal"), new Bag(4, "clear yellow") } },
        { "clear orange", new List<Bag> { new Bag(3, "shiny plum"), new Bag(3, "drab olive") } },
        { "posh silver", new List<Bag> { new Bag(5, "mirrored violet"), new Bag(2, "dotted teal") } },
        { "dim gray", new List<Bag> { new Bag(4, "pale teal"), new Bag(5, "muted salmon"), new Bag(3, "dark indigo") } },
        { "dotted tomato", new List<Bag> { new Bag(3, "dotted maroon") } },
        { "posh purple", new List<Bag> { new Bag(3, "drab turquoise"), new Bag(3, "dark olive"), new Bag(4, "posh lime"), new Bag(1, "posh orange") } },
        { "vibrant beige", new List<Bag> { new Bag(2, "mirrored violet"), new Bag(1, "mirrored white"), new Bag(1, "wavy violet") } },
        { "dark tan", new List<Bag> { new Bag(5, "bright violet"), new Bag(5, "light blue"), new Bag(4, "shiny plum"), new Bag(1, "light indigo") } },
        { "dim lavender", new List<Bag> { new Bag(3, "mirrored green"), new Bag(1, "wavy tan"), new Bag(2, "striped crimson"), new Bag(5, "wavy violet") } },
        { "faded crimson", new List<Bag> { new Bag(3, "muted yellow"), new Bag(2, "posh lime"), new Bag(5, "mirrored gray"), new Bag(3, "faded chartreuse") } },
        { "posh coral", new List<Bag> { new Bag(3, "muted silver"), new Bag(4, "pale magenta"), new Bag(1, "light orange") } },
        { "dull tomato", new List<Bag> { new Bag(2, "plaid tomato"), new Bag(2, "dim lavender"), new Bag(4, "mirrored orange"), new Bag(3, "clear fuchsia") } },
        { "striped orange", new List<Bag> { new Bag(2, "vibrant teal"), new Bag(1, "dotted teal") } },
        { "shiny maroon", new List<Bag> { new Bag(5, "light beige"), new Bag(1, "dim lime") } },
        { "pale olive", new List<Bag> { new Bag(2, "mirrored gold"), new Bag(4, "plaid tomato") } },
        { "light olive", new List<Bag> { new Bag(1, "light red"), new Bag(1, "light crimson"), new Bag(2, "striped chartreuse") } },
        { "posh plum", new List<Bag> { new Bag(5, "bright silver"), new Bag(4, "vibrant indigo"), new Bag(4, "pale turquoise") } },
        { "shiny orange", new List<Bag> { new Bag(4, "dim chartreuse"), new Bag(2, "dotted lavender"), new Bag(2, "shiny green") } },
        { "pale indigo", new List<Bag> { new Bag(3, "mirrored chartreuse"), new Bag(5, "mirrored violet"), new Bag(2, "vibrant blue"), new Bag(3, "mirrored maroon") } },
        { "posh tan", new List<Bag> { new Bag(5, "shiny plum"), new Bag(2, "dark aqua") } },
        { "bright blue", new List<Bag> { new Bag(5, "vibrant salmon"), new Bag(5, "bright maroon"), new Bag(1, "muted yellow") } },
        { "clear maroon", new List<Bag> { new Bag(4, "vibrant beige"), new Bag(3, "mirrored gold"), new Bag(2, "drab teal"), new Bag(2, "drab plum") } },
        { "wavy chartreuse", new List<Bag> { new Bag(3, "clear olive"), new Bag(1, "drab lavender") } },
        { "drab gray", new List<Bag> { new Bag(5, "plaid salmon") } },
        { "faded orange", new List<Bag> { new Bag(1, "faded maroon"), new Bag(5, "vibrant orange") } },
        { "bright coral", new List<Bag> { new Bag(3, "pale turquoise") } },
        { "light beige", new List<Bag> { new Bag(1, "muted cyan") } },
        { "plaid maroon", new List<Bag> { new Bag(5, "faded magenta"), new Bag(4, "faded bronze") } },
        { "dotted purple", new List<Bag> { new Bag(1, "drab plum"), new Bag(5, "faded black"), new Bag(2, "dull silver") } },
        { "muted salmon", new List<Bag> {  } },
        { "striped blue", new List<Bag> { new Bag(5, "mirrored lime"), new Bag(2, "dark plum") } },
        { "dotted lavender", new List<Bag> { new Bag(2, "faded salmon"), new Bag(3, "dim silver"), new Bag(1, "clear cyan"), new Bag(4, "plaid lavender") } },
        { "wavy black", new List<Bag> { new Bag(4, "vibrant gold"), new Bag(5, "light black"), new Bag(4, "muted aqua"), new Bag(5, "vibrant white") } },
        { "clear aqua", new List<Bag> { new Bag(3, "plaid beige"), new Bag(1, "plaid white"), new Bag(3, "shiny red"), new Bag(3, "wavy crimson") } },
        { "mirrored cyan", new List<Bag> {  } },
        { "shiny brown", new List<Bag> { new Bag(2, "dim aqua") } },
        { "dotted green", new List<Bag> { new Bag(4, "mirrored green"), new Bag(3, "mirrored tomato"), new Bag(5, "plaid gray") } },
        { "striped purple", new List<Bag> { new Bag(3, "wavy yellow"), new Bag(2, "faded orange") } },
        { "plaid indigo", new List<Bag> { new Bag(2, "shiny plum"), new Bag(5, "bright magenta"), new Bag(2, "posh yellow"), new Bag(3, "shiny gold") } },
        { "posh chartreuse", new List<Bag> { new Bag(2, "mirrored cyan"), new Bag(4, "drab salmon"), new Bag(4, "dim olive"), new Bag(2, "posh lime") } },
        { "light lavender", new List<Bag> { new Bag(4, "dim fuchsia"), new Bag(5, "pale salmon"), new Bag(4, "clear teal") } },
        { "shiny crimson", new List<Bag> { new Bag(5, "light blue") } },
        { "plaid black", new List<Bag> { new Bag(5, "clear indigo"), new Bag(5, "mirrored purple"), new Bag(1, "light aqua") } },
        { "shiny lime", new List<Bag> { new Bag(5, "dotted blue"), new Bag(2, "shiny tan") } },
        { "dotted salmon", new List<Bag> { new Bag(4, "pale salmon"), new Bag(1, "clear maroon") } },
        { "vibrant lavender", new List<Bag> { new Bag(4, "shiny red"), new Bag(4, "shiny green"), new Bag(5, "dim silver") } },
        { "muted yellow", new List<Bag> { new Bag(5, "wavy aqua"), new Bag(2, "posh lavender"), new Bag(3, "dull magenta"), new Bag(1, "plaid red") } },
        { "faded beige", new List<Bag> { new Bag(1, "wavy violet"), new Bag(4, "plaid maroon") } },
        { "wavy blue", new List<Bag> { new Bag(5, "dotted orange"), new Bag(1, "faded chartreuse"), new Bag(4, "posh magenta") } },
        { "faded brown", new List<Bag> { new Bag(4, "bright coral"), new Bag(3, "mirrored aqua") } },
        { "striped lavender", new List<Bag> { new Bag(5, "dim brown"), new Bag(2, "wavy cyan"), new Bag(4, "pale blue"), new Bag(1, "posh olive") } },
        { "bright fuchsia", new List<Bag> { new Bag(5, "clear lime") } },
        { "bright black", new List<Bag> { new Bag(5, "clear fuchsia"), new Bag(4, "pale purple") } },
        { "pale orange", new List<Bag> { new Bag(3, "plaid aqua"), new Bag(5, "muted fuchsia"), new Bag(1, "wavy crimson") } },
        { "mirrored magenta", new List<Bag> { new Bag(2, "posh chartreuse"), new Bag(2, "muted white"), new Bag(5, "posh lime"), new Bag(5, "dark gold") } },
        { "light magenta", new List<Bag> { new Bag(1, "mirrored white"), new Bag(1, "dull silver"), new Bag(5, "posh chartreuse") } },
        { "striped gold", new List<Bag> { new Bag(1, "mirrored cyan"), new Bag(1, "dark olive"), new Bag(4, "mirrored red"), new Bag(5, "posh chartreuse") } },
        { "plaid lavender", new List<Bag> { new Bag(1, "vibrant white"), new Bag(4, "dotted maroon") } },
        { "faded gold", new List<Bag> { new Bag(5, "striped crimson") } },
        { "vibrant olive", new List<Bag> { new Bag(1, "plaid beige") } },
        { "dark aqua", new List<Bag> { new Bag(4, "plaid tomato"), new Bag(1, "striped olive"), new Bag(4, "pale fuchsia"), new Bag(3, "dim gold") } },
        { "dim lime", new List<Bag> { new Bag(2, "plaid gray") } },
        { "pale lavender", new List<Bag> { new Bag(4, "muted yellow"), new Bag(1, "drab yellow"), new Bag(2, "dull cyan"), new Bag(2, "muted teal") } },
        { "bright violet", new List<Bag> { new Bag(2, "posh lime"), new Bag(1, "wavy violet"), new Bag(2, "mirrored red") } },
        { "dotted maroon", new List<Bag> { new Bag(1, "drab salmon") } },
        { "clear magenta", new List<Bag> { new Bag(3, "mirrored brown") } },
        { "vibrant red", new List<Bag> { new Bag(5, "clear cyan"), new Bag(2, "dark teal") } },
        { "shiny olive", new List<Bag> { new Bag(5, "light tan"), new Bag(5, "plaid maroon"), new Bag(3, "mirrored blue") } },
        { "plaid fuchsia", new List<Bag> { new Bag(5, "posh silver") } },
        { "vibrant chartreuse", new List<Bag> { new Bag(2, "clear coral"), new Bag(2, "pale purple"), new Bag(5, "light beige") } },
        { "vibrant violet", new List<Bag> { new Bag(3, "striped bronze"), new Bag(2, "drab tomato"), new Bag(2, "faded violet"), new Bag(5, "posh crimson") } },
        { "vibrant white", new List<Bag> { new Bag(1, "plaid orange"), new Bag(5, "muted aqua"), new Bag(5, "pale fuchsia"), new Bag(3, "muted fuchsia") } },
        { "drab magenta", new List<Bag> { new Bag(3, "bright indigo"), new Bag(1, "faded violet") } },
        { "faded tan", new List<Bag> { new Bag(3, "dark crimson"), new Bag(5, "light aqua") } },
        { "bright salmon", new List<Bag> { new Bag(3, "clear plum"), new Bag(3, "striped blue"), new Bag(5, "plaid green") } },
        { "wavy aqua", new List<Bag> { new Bag(1, "clear beige"), new Bag(5, "dull magenta") } },
        { "muted white", new List<Bag> { new Bag(5, "wavy tan"), new Bag(5, "plaid silver"), new Bag(5, "striped bronze"), new Bag(3, "dull silver") } },
        { "mirrored gray", new List<Bag> { new Bag(4, "dim olive"), new Bag(3, "striped gold"), new Bag(1, "wavy tan"), new Bag(5, "striped bronze") } },
        { "vibrant maroon", new List<Bag> { new Bag(5, "clear bronze") } },
        { "shiny violet", new List<Bag> { new Bag(2, "clear salmon"), new Bag(1, "bright beige") } },
        { "dim bronze", new List<Bag> { new Bag(2, "posh brown"), new Bag(4, "vibrant indigo"), new Bag(2, "dull purple") } },
        { "bright bronze", new List<Bag> { new Bag(1, "bright maroon"), new Bag(4, "faded aqua"), new Bag(2, "pale tan"), new Bag(3, "mirrored lavender") } },
        { "dull blue", new List<Bag> { new Bag(4, "clear coral"), new Bag(2, "drab olive") } },
        { "posh crimson", new List<Bag> { new Bag(1, "muted white"), new Bag(2, "faded maroon"), new Bag(5, "plaid olive") } },
        { "dark olive", new List<Bag> { new Bag(3, "dim olive"), new Bag(3, "mirrored red") } },
        { "striped violet", new List<Bag> { new Bag(4, "wavy gold"), new Bag(4, "dotted maroon"), new Bag(1, "vibrant salmon") } },
        { "vibrant tomato", new List<Bag> { new Bag(1, "striped gold"), new Bag(1, "faded turquoise") } },
        { "mirrored turquoise", new List<Bag> { new Bag(2, "dark magenta"), new Bag(2, "clear lime"), new Bag(3, "dull turquoise") } },
        { "mirrored coral", new List<Bag> { new Bag(4, "plaid lavender"), new Bag(4, "vibrant salmon"), new Bag(4, "mirrored chartreuse"), new Bag(3, "plaid white") } },
        { "muted red", new List<Bag> { new Bag(2, "mirrored maroon"), new Bag(4, "vibrant beige") } },
        { "shiny salmon", new List<Bag> { new Bag(2, "posh black"), new Bag(4, "wavy tan") } },
        { "vibrant turquoise", new List<Bag> { new Bag(4, "clear crimson") } },
        { "pale maroon", new List<Bag> { new Bag(4, "striped crimson"), new Bag(5, "wavy indigo"), new Bag(3, "dull turquoise"), new Bag(2, "faded black") } },
        { "dull beige", new List<Bag> { new Bag(4, "dim olive"), new Bag(3, "vibrant olive"), new Bag(1, "mirrored plum"), new Bag(3, "muted white") } },
        { "striped tan", new List<Bag> { new Bag(5, "mirrored gray") } },
        { "dotted magenta", new List<Bag> { new Bag(4, "wavy olive"), new Bag(5, "mirrored magenta"), new Bag(4, "muted fuchsia"), new Bag(2, "muted gray") } },
        { "pale chartreuse", new List<Bag> { new Bag(1, "wavy crimson") } },
        { "dull white", new List<Bag> { new Bag(1, "dull tomato"), new Bag(4, "faded tomato"), new Bag(3, "shiny fuchsia"), new Bag(4, "dim beige") } },
        { "light cyan", new List<Bag> { new Bag(3, "drab plum"), new Bag(1, "wavy violet"), new Bag(1, "vibrant gold"), new Bag(1, "dotted purple") } },
        { "bright tomato", new List<Bag> { new Bag(1, "bright plum") } },
        { "bright olive", new List<Bag> { new Bag(1, "dull green") } },
        { "shiny tomato", new List<Bag> { new Bag(3, "faded red"), new Bag(3, "mirrored gold") } },
        { "light white", new List<Bag> { new Bag(2, "dotted gray") } },
        { "dotted bronze", new List<Bag> { new Bag(3, "wavy olive") } },
        { "drab white", new List<Bag> { new Bag(4, "dim fuchsia") } },
        { "posh indigo", new List<Bag> { new Bag(2, "dull salmon"), new Bag(4, "mirrored white") } },
        { "vibrant coral", new List<Bag> { new Bag(2, "faded chartreuse"), new Bag(3, "dark indigo"), new Bag(1, "wavy coral") } },
        { "bright purple", new List<Bag> { new Bag(4, "dull white") } },
        { "faded blue", new List<Bag> { new Bag(1, "striped chartreuse"), new Bag(2, "faded crimson") } },
        { "striped turquoise", new List<Bag> { new Bag(5, "dark plum") } },
        { "faded green", new List<Bag> { new Bag(1, "mirrored white"), new Bag(1, "striped magenta") } },
        { "dotted indigo", new List<Bag> { new Bag(5, "pale olive"), new Bag(5, "vibrant fuchsia") } },
        { "drab blue", new List<Bag> { new Bag(2, "faded tomato") } },
        { "dull lime", new List<Bag> { new Bag(4, "faded crimson"), new Bag(1, "striped white"), new Bag(3, "drab bronze") } },
        { "bright yellow", new List<Bag> { new Bag(5, "drab purple"), new Bag(2, "mirrored white"), new Bag(4, "faded fuchsia"), new Bag(2, "dark tomato") } },
        { "clear turquoise", new List<Bag> { new Bag(3, "muted fuchsia"), new Bag(3, "plaid purple"), new Bag(4, "posh blue") } },
        { "dull crimson", new List<Bag> { new Bag(5, "muted green"), new Bag(3, "dotted bronze"), new Bag(2, "pale gray") } },
        { "light maroon", new List<Bag> { new Bag(5, "faded indigo"), new Bag(1, "clear yellow") } },
        { "wavy magenta", new List<Bag> { new Bag(3, "bright orange"), new Bag(2, "pale lavender"), new Bag(1, "shiny blue"), new Bag(1, "plaid purple") } },
        { "vibrant aqua", new List<Bag> { new Bag(2, "vibrant silver") } },
        { "posh black", new List<Bag> { new Bag(3, "striped crimson") } },
        { "bright white", new List<Bag> { new Bag(2, "clear white") } },
        { "clear bronze", new List<Bag> { new Bag(2, "dim aqua"), new Bag(1, "mirrored indigo") } },
        { "vibrant yellow", new List<Bag> { new Bag(2, "vibrant silver") } },
        { "bright silver", new List<Bag> { new Bag(3, "clear beige"), new Bag(3, "mirrored lime") } },
        { "plaid magenta", new List<Bag> { new Bag(5, "striped gold"), new Bag(5, "posh purple"), new Bag(2, "pale brown") } },
        { "shiny black", new List<Bag> { new Bag(2, "posh beige"), new Bag(4, "posh magenta"), new Bag(4, "dim blue"), new Bag(4, "dark bronze") } },
        { "shiny yellow", new List<Bag> { new Bag(2, "wavy turquoise"), new Bag(2, "pale purple") } },
        { "plaid aqua", new List<Bag> { new Bag(3, "shiny fuchsia"), new Bag(1, "dull tomato"), new Bag(2, "light magenta"), new Bag(3, "mirrored green") } },
        { "wavy bronze", new List<Bag> { new Bag(2, "bright gold"), new Bag(5, "plaid green"), new Bag(1, "shiny violet"), new Bag(1, "faded chartreuse") } },
        { "mirrored purple", new List<Bag> { new Bag(2, "faded tomato"), new Bag(1, "dark gold"), new Bag(4, "dim aqua"), new Bag(1, "faded aqua") } },
        { "muted tan", new List<Bag> { new Bag(3, "pale teal"), new Bag(3, "drab tomato"), new Bag(4, "pale maroon"), new Bag(1, "dim cyan") } },
        { "plaid blue", new List<Bag> { new Bag(2, "muted coral"), new Bag(5, "striped maroon"), new Bag(3, "pale plum"), new Bag(5, "dotted purple") } },
        { "posh gray", new List<Bag> { new Bag(5, "muted salmon"), new Bag(2, "wavy orange") } },
        { "wavy orange", new List<Bag> { new Bag(5, "dark aqua") } },
        { "bright brown", new List<Bag> { new Bag(3, "muted yellow"), new Bag(5, "faded lavender"), new Bag(2, "drab cyan"), new Bag(2, "mirrored indigo") } },
        { "dark brown", new List<Bag> { new Bag(3, "plaid coral") } },
        { "bright beige", new List<Bag> { new Bag(4, "vibrant indigo"), new Bag(5, "bright lime"), new Bag(5, "bright magenta") } },
        { "clear tan", new List<Bag> { new Bag(3, "dark turquoise"), new Bag(4, "vibrant cyan") } },
        { "light brown", new List<Bag> { new Bag(3, "light lime") } },
        { "wavy red", new List<Bag> { new Bag(5, "wavy cyan"), new Bag(4, "plaid bronze"), new Bag(3, "dark chartreuse") } },
        { "faded olive", new List<Bag> { new Bag(1, "wavy green"), new Bag(3, "drab olive") } },
        { "vibrant lime", new List<Bag> { new Bag(5, "vibrant silver"), new Bag(2, "light silver") } },
        { "faded plum", new List<Bag> { new Bag(3, "clear lavender"), new Bag(1, "dotted lavender"), new Bag(5, "muted silver"), new Bag(3, "plaid purple") } },
        { "dark violet", new List<Bag> { new Bag(2, "vibrant beige"), new Bag(3, "light crimson") } },
        { "posh lime", new List<Bag> {  } },
        { "dark magenta", new List<Bag> { new Bag(2, "muted cyan") } },
        { "striped white", new List<Bag> { new Bag(5, "light tan"), new Bag(3, "plaid orange"), new Bag(1, "dark gold"), new Bag(4, "mirrored white") } },
        { "dull cyan", new List<Bag> { new Bag(1, "muted red"), new Bag(5, "faded lavender"), new Bag(5, "plaid gold"), new Bag(5, "dark beige") } },
        { "mirrored white", new List<Bag> { new Bag(2, "dark olive"), new Bag(4, "striped bronze") } },
        { "light plum", new List<Bag> { new Bag(3, "wavy crimson") } },
        { "clear red", new List<Bag> { new Bag(4, "faded violet"), new Bag(3, "dotted tan"), new Bag(1, "pale indigo"), new Bag(4, "vibrant brown") } },
        { "muted maroon", new List<Bag> { new Bag(3, "bright indigo"), new Bag(1, "striped magenta") } },
        { "dull chartreuse", new List<Bag> { new Bag(4, "posh orange") } },
        { "muted green", new List<Bag> { new Bag(2, "vibrant orange"), new Bag(3, "dull red") } },
        { "muted coral", new List<Bag> { new Bag(1, "dark olive"), new Bag(4, "striped bronze") } },
        { "drab brown", new List<Bag> { new Bag(3, "shiny maroon") } },
        { "pale teal", new List<Bag> { new Bag(2, "faded aqua"), new Bag(4, "mirrored magenta"), new Bag(2, "plaid red"), new Bag(1, "dark coral") } },
        { "dull purple", new List<Bag> { new Bag(2, "dotted teal"), new Bag(3, "vibrant orange") } },
        { "mirrored maroon", new List<Bag> { new Bag(3, "light purple"), new Bag(4, "posh beige"), new Bag(1, "dim gold"), new Bag(4, "striped olive") } },
        { "dull salmon", new List<Bag> { new Bag(3, "mirrored red") } },
        { "posh maroon", new List<Bag> { new Bag(3, "dark bronze"), new Bag(2, "faded lavender"), new Bag(3, "plaid red") } },
        { "shiny teal", new List<Bag> { new Bag(1, "dotted purple"), new Bag(5, "dull black"), new Bag(1, "muted purple") } },
        { "dotted olive", new List<Bag> { new Bag(1, "wavy aqua"), new Bag(2, "clear indigo"), new Bag(2, "light coral"), new Bag(1, "plaid yellow") } },
        { "drab silver", new List<Bag> { new Bag(2, "wavy coral"), new Bag(1, "light purple"), new Bag(4, "shiny fuchsia") } },
        { "posh lavender", new List<Bag> { new Bag(3, "shiny plum"), new Bag(5, "wavy coral"), new Bag(2, "mirrored green") } },
        { "dark silver", new List<Bag> { new Bag(2, "vibrant blue"), new Bag(2, "dull crimson") } },
        { "clear indigo", new List<Bag> { new Bag(3, "plaid aqua"), new Bag(4, "posh orange") } },
        { "plaid purple", new List<Bag> { new Bag(3, "vibrant gold"), new Bag(4, "wavy fuchsia"), new Bag(2, "striped maroon"), new Bag(2, "wavy coral") } },
        { "dull gray", new List<Bag> { new Bag(4, "striped maroon"), new Bag(1, "striped gold"), new Bag(4, "vibrant salmon"), new Bag(3, "shiny fuchsia") } },
        { "dim maroon", new List<Bag> { new Bag(4, "shiny beige") } },
        { "plaid lime", new List<Bag> { new Bag(4, "bright lime"), new Bag(5, "vibrant tan") } },
        { "faded lime", new List<Bag> { new Bag(3, "dotted crimson"), new Bag(2, "wavy violet") } },
        { "pale coral", new List<Bag> { new Bag(5, "wavy blue") } },
        { "plaid crimson", new List<Bag> { new Bag(2, "dull black"), new Bag(3, "striped gold"), new Bag(5, "dim beige"), new Bag(1, "mirrored purple") } },
        { "dark beige", new List<Bag> { new Bag(4, "vibrant salmon"), new Bag(2, "drab plum"), new Bag(5, "dull chartreuse"), new Bag(4, "light crimson") } },
        { "clear crimson", new List<Bag> { new Bag(2, "shiny fuchsia"), new Bag(5, "faded chartreuse") } },
        { "dull orange", new List<Bag> { new Bag(5, "plaid bronze"), new Bag(5, "faded cyan"), new Bag(3, "dotted silver"), new Bag(5, "dim purple") } },
        { "dotted black", new List<Bag> { new Bag(2, "bright green"), new Bag(5, "bright tomato"), new Bag(1, "pale magenta") } },
        { "dull coral", new List<Bag> { new Bag(2, "dark beige"), new Bag(5, "striped gold") } },
        { "vibrant salmon", new List<Bag> { new Bag(5, "striped indigo"), new Bag(2, "plaid olive"), new Bag(2, "drab plum") } },
        { "dim blue", new List<Bag> { new Bag(2, "mirrored orange") } },
        { "dim black", new List<Bag> { new Bag(2, "light chartreuse"), new Bag(1, "wavy fuchsia") } },
        { "dark white", new List<Bag> { new Bag(4, "mirrored maroon"), new Bag(2, "dim lavender"), new Bag(5, "faded yellow"), new Bag(3, "dark silver") } },
        { "drab olive", new List<Bag> { new Bag(2, "muted white"), new Bag(1, "mirrored white"), new Bag(4, "striped crimson"), new Bag(4, "faded maroon") } },
        { "striped brown", new List<Bag> { new Bag(1, "dull fuchsia"), new Bag(1, "plaid crimson") } },
        { "clear tomato", new List<Bag> { new Bag(5, "drab chartreuse") } },
        { "muted bronze", new List<Bag> { new Bag(3, "light magenta"), new Bag(4, "clear yellow"), new Bag(5, "bright tomato") } },
        { "posh olive", new List<Bag> { new Bag(3, "dotted gold") } },
        { "dull maroon", new List<Bag> { new Bag(4, "plaid beige"), new Bag(5, "drab silver"), new Bag(3, "drab lime"), new Bag(5, "dull magenta") } },
        { "drab cyan", new List<Bag> { new Bag(3, "striped magenta"), new Bag(1, "vibrant bronze"), new Bag(2, "mirrored green"), new Bag(3, "plaid silver") } },
        { "posh magenta", new List<Bag> { new Bag(1, "striped chartreuse"), new Bag(4, "vibrant silver") } },
        { "muted violet", new List<Bag> { new Bag(4, "dark gold"), new Bag(1, "posh purple"), new Bag(3, "clear purple"), new Bag(4, "bright teal") } },
        { "muted silver", new List<Bag> { new Bag(2, "bright chartreuse"), new Bag(1, "clear chartreuse") } },
        { "wavy coral", new List<Bag> { new Bag(5, "mirrored red"), new Bag(1, "striped gold"), new Bag(5, "faded maroon"), new Bag(1, "dark olive") } },
        { "dark green", new List<Bag> { new Bag(3, "shiny gold") } },
        { "drab beige", new List<Bag> { new Bag(4, "vibrant crimson"), new Bag(4, "posh silver") } },
        { "plaid gray", new List<Bag> { new Bag(2, "wavy blue"), new Bag(5, "dim coral") } },
        { "plaid orange", new List<Bag> { new Bag(3, "mirrored orange"), new Bag(1, "dark olive"), new Bag(1, "light red"), new Bag(2, "striped gold") } },
        { "dull silver", new List<Bag> {  } },
        { "shiny lavender", new List<Bag> { new Bag(3, "dotted yellow"), new Bag(1, "wavy indigo"), new Bag(1, "dark coral") } },
        { "dim brown", new List<Bag> { new Bag(4, "dim blue"), new Bag(1, "drab plum") } },
        { "posh salmon", new List<Bag> { new Bag(3, "dim blue") } },
        { "drab orange", new List<Bag> { new Bag(1, "faded bronze"), new Bag(5, "dull black") } },
        { "wavy crimson", new List<Bag> { new Bag(1, "drab salmon"), new Bag(2, "vibrant salmon") } },
        { "dull black", new List<Bag> { new Bag(5, "vibrant orange") } },
        { "clear teal", new List<Bag> { new Bag(5, "faded aqua"), new Bag(1, "plaid crimson"), new Bag(1, "posh silver") } },
        { "wavy olive", new List<Bag> { new Bag(3, "faded aqua"), new Bag(3, "faded fuchsia"), new Bag(2, "drab cyan") } },
        { "bright gray", new List<Bag> { new Bag(4, "clear coral"), new Bag(2, "clear white"), new Bag(3, "faded lavender"), new Bag(4, "dark turquoise") } },
        { "striped green", new List<Bag> { new Bag(1, "faded magenta"), new Bag(1, "wavy tan"), new Bag(4, "posh red"), new Bag(1, "striped bronze") } },
        { "clear salmon", new List<Bag> { new Bag(2, "striped green"), new Bag(1, "striped aqua"), new Bag(3, "muted white"), new Bag(3, "pale plum") } },
        { "wavy indigo", new List<Bag> { new Bag(2, "vibrant orange"), new Bag(1, "shiny indigo"), new Bag(1, "drab tomato") } },
        { "clear brown", new List<Bag> { new Bag(3, "muted maroon"), new Bag(4, "dotted silver") } },
        { "vibrant silver", new List<Bag> { new Bag(4, "wavy violet"), new Bag(2, "posh chartreuse") } },
        { "mirrored salmon", new List<Bag> { new Bag(4, "bright brown"), new Bag(3, "mirrored crimson"), new Bag(1, "mirrored aqua") } },
        { "faded white", new List<Bag> { new Bag(1, "wavy crimson"), new Bag(3, "drab silver"), new Bag(5, "striped yellow"), new Bag(3, "dotted olive") } },
        { "muted indigo", new List<Bag> { new Bag(1, "wavy indigo") } },
        { "drab aqua", new List<Bag> { new Bag(5, "dotted teal"), new Bag(4, "mirrored white") } },
        { "posh red", new List<Bag> { new Bag(5, "wavy crimson") } },
        { "dim turquoise", new List<Bag> { new Bag(1, "striped turquoise"), new Bag(4, "dotted crimson") } },
        { "dark yellow", new List<Bag> { new Bag(1, "drab olive"), new Bag(3, "muted aqua") } },
        { "pale red", new List<Bag> { new Bag(2, "vibrant gray") } },
        { "vibrant black", new List<Bag> { new Bag(1, "posh gray"), new Bag(5, "pale teal"), new Bag(5, "shiny red") } },
        { "pale purple", new List<Bag> { new Bag(5, "dim olive") } },
        { "dim tomato", new List<Bag> { new Bag(3, "plaid lavender") } },
        { "dim yellow", new List<Bag> { new Bag(4, "plaid brown") } },
        { "plaid silver", new List<Bag> {  } },
        { "plaid white", new List<Bag> { new Bag(2, "muted purple"), new Bag(5, "dull black") } },
        { "muted magenta", new List<Bag> { new Bag(2, "plaid gray"), new Bag(5, "wavy salmon"), new Bag(3, "dark chartreuse") } },
        { "bright aqua", new List<Bag> { new Bag(1, "dark indigo"), new Bag(1, "faded gray"), new Bag(5, "vibrant white"), new Bag(2, "vibrant gold") } },
        { "drab crimson", new List<Bag> { new Bag(2, "clear orange") } },
        { "wavy purple", new List<Bag> { new Bag(2, "vibrant plum"), new Bag(3, "dark fuchsia"), new Bag(2, "pale salmon") } },
        { "wavy teal", new List<Bag> { new Bag(1, "drab salmon"), new Bag(4, "muted indigo"), new Bag(5, "bright violet"), new Bag(5, "muted bronze") } },
        { "pale salmon", new List<Bag> { new Bag(5, "mirrored blue"), new Bag(4, "mirrored maroon") } },
        { "faded lavender", new List<Bag> { new Bag(2, "muted blue"), new Bag(4, "striped blue"), new Bag(3, "pale brown"), new Bag(2, "pale purple") } },
        { "dull plum", new List<Bag> { new Bag(5, "clear coral") } },
        { "drab maroon", new List<Bag> { new Bag(2, "plaid bronze"), new Bag(1, "bright orange") } },
        { "light turquoise", new List<Bag> { new Bag(4, "striped teal"), new Bag(4, "posh indigo") } },
        { "dotted orange", new List<Bag> { new Bag(2, "wavy violet") } },
        { "bright teal", new List<Bag> { new Bag(4, "clear indigo"), new Bag(1, "vibrant violet") } },
        { "mirrored fuchsia", new List<Bag> { new Bag(4, "muted brown"), new Bag(5, "wavy coral"), new Bag(2, "wavy turquoise") } },
        { "dark indigo", new List<Bag> { new Bag(1, "light red"), new Bag(4, "vibrant lime"), new Bag(2, "drab teal") } },
        { "plaid brown", new List<Bag> { new Bag(2, "dull gray"), new Bag(3, "mirrored magenta") } },
        { "wavy yellow", new List<Bag> { new Bag(4, "dotted brown") } },
        { "light orange", new List<Bag> { new Bag(4, "shiny black") } },
        { "dark cyan", new List<Bag> { new Bag(3, "mirrored chartreuse"), new Bag(4, "pale magenta"), new Bag(2, "dull black"), new Bag(2, "posh lime") } },
        { "muted chartreuse", new List<Bag> { new Bag(3, "dull silver"), new Bag(1, "dark aqua"), new Bag(2, "light tomato") } },
        { "dull red", new List<Bag> { new Bag(5, "mirrored orange"), new Bag(2, "plaid yellow") } },
        { "dotted cyan", new List<Bag> { new Bag(1, "vibrant fuchsia"), new Bag(5, "drab olive"), new Bag(4, "clear chartreuse"), new Bag(5, "pale beige") } },
        { "dim beige", new List<Bag> { new Bag(2, "striped yellow"), new Bag(3, "bright cyan") } },
        { "dull magenta", new List<Bag> { new Bag(4, "faded black") } },
        { "dotted blue", new List<Bag> { new Bag(2, "posh maroon"), new Bag(5, "dark gold") } },
        { "muted olive", new List<Bag> { new Bag(1, "mirrored aqua"), new Bag(4, "dull black"), new Bag(5, "clear gold"), new Bag(1, "mirrored cyan") } },
        { "mirrored silver", new List<Bag> { new Bag(2, "bright blue"), new Bag(4, "shiny orange") } },
        { "muted brown", new List<Bag> { new Bag(5, "muted white"), new Bag(4, "clear violet"), new Bag(3, "light red") } },
        { "muted lime", new List<Bag> { new Bag(2, "plaid yellow"), new Bag(2, "pale chartreuse"), new Bag(2, "muted tomato") } },
        { "clear silver", new List<Bag> { new Bag(2, "clear purple"), new Bag(2, "light tomato"), new Bag(4, "light gray"), new Bag(1, "shiny crimson") } },
        { "dim tan", new List<Bag> { new Bag(2, "dull brown"), new Bag(1, "dull tomato"), new Bag(2, "dim salmon"), new Bag(1, "dull green") } },
        { "shiny cyan", new List<Bag> { new Bag(5, "plaid turquoise") } },
        { "faded indigo", new List<Bag> { new Bag(4, "drab plum"), new Bag(4, "clear maroon"), new Bag(5, "wavy cyan"), new Bag(4, "dim crimson") } },
        { "posh bronze", new List<Bag> { new Bag(5, "mirrored olive") } },
        { "posh aqua", new List<Bag> { new Bag(3, "dull violet"), new Bag(5, "bright silver"), new Bag(1, "drab coral"), new Bag(5, "shiny orange") } },
        { "dark blue", new List<Bag> { new Bag(5, "light silver"), new Bag(1, "posh magenta"), new Bag(3, "mirrored crimson"), new Bag(4, "pale chartreuse") } },
        { "dim crimson", new List<Bag> { new Bag(1, "faded gray"), new Bag(3, "dull turquoise") } },
        { "dark coral", new List<Bag> { new Bag(3, "bright violet"), new Bag(3, "mirrored violet") } },
        { "pale green", new List<Bag> { new Bag(2, "muted white"), new Bag(5, "bright lime"), new Bag(4, "dark indigo"), new Bag(2, "faded fuchsia") } },
        { "shiny silver", new List<Bag> { new Bag(4, "bright teal"), new Bag(1, "dim gold") } },
        { "light fuchsia", new List<Bag> { new Bag(1, "dull white"), new Bag(1, "striped indigo"), new Bag(2, "light orange") } },
        { "vibrant crimson", new List<Bag> { new Bag(4, "striped maroon"), new Bag(5, "dim white") } },
        { "clear yellow", new List<Bag> { new Bag(5, "bright green") } },
        { "striped aqua", new List<Bag> { new Bag(4, "mirrored beige"), new Bag(4, "clear beige") } },
        { "dark chartreuse", new List<Bag> { new Bag(3, "bright lime"), new Bag(3, "mirrored magenta") } },
        { "wavy turquoise", new List<Bag> { new Bag(4, "bright brown"), new Bag(5, "mirrored lime"), new Bag(3, "pale white"), new Bag(3, "drab salmon") } },
        { "faded tomato", new List<Bag> { new Bag(2, "clear indigo"), new Bag(3, "faded teal"), new Bag(4, "dark teal") } },
        { "dull indigo", new List<Bag> { new Bag(5, "vibrant indigo"), new Bag(1, "mirrored purple"), new Bag(1, "vibrant tan"), new Bag(2, "shiny plum") } },
        { "posh yellow", new List<Bag> { new Bag(5, "clear cyan"), new Bag(3, "mirrored red"), new Bag(5, "mirrored magenta") } },
        { "plaid yellow", new List<Bag> { new Bag(3, "vibrant gold"), new Bag(4, "posh crimson"), new Bag(3, "mirrored green") } },
        { "plaid olive", new List<Bag> { new Bag(3, "vibrant indigo"), new Bag(3, "posh indigo"), new Bag(1, "posh magenta"), new Bag(5, "dim olive") } },
        { "bright cyan", new List<Bag> { new Bag(2, "vibrant brown"), new Bag(2, "muted red") } },
        { "clear chartreuse", new List<Bag> { new Bag(2, "muted salmon"), new Bag(1, "plaid aqua") } },
        { "shiny plum", new List<Bag> { new Bag(5, "mirrored gray"), new Bag(2, "dotted maroon") } },
        { "dim teal", new List<Bag> { new Bag(3, "dotted tan"), new Bag(4, "faded aqua"), new Bag(2, "light teal") } },
        { "mirrored bronze", new List<Bag> { new Bag(3, "wavy plum"), new Bag(5, "dotted tan") } },
        { "muted turquoise", new List<Bag> { new Bag(2, "mirrored silver"), new Bag(2, "dotted yellow") } },
        { "clear gold", new List<Bag> { new Bag(4, "plaid olive") } },
        { "mirrored orange", new List<Bag> { new Bag(5, "mirrored cyan"), new Bag(2, "faded maroon"), new Bag(2, "bright violet") } },
        { "striped chartreuse", new List<Bag> { new Bag(3, "dark gold"), new Bag(2, "pale fuchsia") } },
        { "dull turquoise", new List<Bag> { new Bag(5, "faded black") } },
        { "bright chartreuse", new List<Bag> { new Bag(1, "drab turquoise") } },
        { "vibrant green", new List<Bag> { new Bag(3, "wavy plum"), new Bag(1, "shiny fuchsia"), new Bag(3, "dark yellow"), new Bag(1, "dotted lime") } },
        { "mirrored black", new List<Bag> { new Bag(4, "plaid red"), new Bag(2, "wavy brown") } },
        { "striped magenta", new List<Bag> { new Bag(3, "dim lavender") } },
        { "shiny gold", new List<Bag> { new Bag(3, "clear fuchsia"), new Bag(2, "vibrant indigo"), new Bag(4, "dotted maroon") } },
        { "posh fuchsia", new List<Bag> { new Bag(3, "dull silver"), new Bag(3, "mirrored lime"), new Bag(2, "dull black") } },
        { "bright magenta", new List<Bag> { new Bag(5, "clear violet"), new Bag(1, "light red"), new Bag(1, "mirrored white") } },
        { "mirrored tomato", new List<Bag> { new Bag(1, "dark olive"), new Bag(5, "faded maroon") } },
        { "wavy gray", new List<Bag> { new Bag(5, "dotted orange"), new Bag(3, "muted magenta"), new Bag(2, "plaid maroon"), new Bag(4, "drab tomato") } },
        { "dim plum", new List<Bag> { new Bag(4, "dim salmon"), new Bag(4, "light cyan"), new Bag(3, "wavy coral") } },
        { "shiny chartreuse", new List<Bag> { new Bag(2, "drab plum"), new Bag(2, "pale beige") } },
        { "striped gray", new List<Bag> { new Bag(4, "muted aqua") } },
        { "faded cyan", new List<Bag> { new Bag(2, "muted coral") } },
        { "clear coral", new List<Bag> { new Bag(5, "faded white"), new Bag(5, "dull coral") } },
        { "dim violet", new List<Bag> { new Bag(2, "dark tomato"), new Bag(3, "vibrant silver"), new Bag(2, "clear maroon") } },
        { "wavy tomato", new List<Bag> { new Bag(1, "striped orange"), new Bag(2, "posh magenta") } },
        { "drab chartreuse", new List<Bag> { new Bag(4, "posh crimson"), new Bag(3, "wavy brown") } },
        { "dotted plum", new List<Bag> { new Bag(4, "posh crimson"), new Bag(3, "dull magenta") } },
        { "striped crimson", new List<Bag> { new Bag(1, "wavy coral") } },
        { "faded yellow", new List<Bag> { new Bag(2, "faded gray") } },
        { "faded magenta", new List<Bag> { new Bag(4, "dotted yellow") } },
        { "bright orange", new List<Bag> { new Bag(5, "dark plum"), new Bag(3, "plaid white"), new Bag(3, "bright chartreuse") } },
        { "drab red", new List<Bag> { new Bag(4, "vibrant cyan") } },
        { "wavy white", new List<Bag> { new Bag(4, "mirrored lavender"), new Bag(3, "muted tomato"), new Bag(3, "faded tomato"), new Bag(5, "drab cyan") } },
        { "striped salmon", new List<Bag> { new Bag(5, "dotted silver") } },
        { "mirrored violet", new List<Bag> { new Bag(3, "plaid silver"), new Bag(1, "dotted maroon"), new Bag(5, "striped gray") } },
        { "pale fuchsia", new List<Bag> { new Bag(2, "dark gold") } },
        { "striped silver", new List<Bag> { new Bag(1, "faded cyan"), new Bag(2, "muted orange") } },
        { "dull brown", new List<Bag> { new Bag(5, "dotted chartreuse"), new Bag(4, "vibrant red"), new Bag(2, "plaid purple"), new Bag(4, "shiny fuchsia") } },
        { "dull gold", new List<Bag> { new Bag(1, "dull olive"), new Bag(1, "clear coral"), new Bag(4, "light tomato"), new Bag(4, "muted yellow") } },
        { "plaid green", new List<Bag> { new Bag(5, "dark bronze"), new Bag(1, "muted aqua"), new Bag(4, "plaid aqua") } },
        { "dim white", new List<Bag> { new Bag(4, "bright red"), new Bag(2, "striped teal"), new Bag(2, "posh crimson") } },
        { "drab salmon", new List<Bag> {  } },
        { "dull fuchsia", new List<Bag> { new Bag(5, "clear crimson"), new Bag(1, "pale green"), new Bag(3, "vibrant coral"), new Bag(3, "plaid salmon") } },
        { "pale lime", new List<Bag> { new Bag(1, "plaid magenta") } },
        { "wavy lavender", new List<Bag> { new Bag(4, "faded magenta"), new Bag(3, "dark yellow"), new Bag(5, "plaid aqua") } },
        { "shiny gray", new List<Bag> { new Bag(4, "dark teal"), new Bag(1, "wavy crimson"), new Bag(4, "posh lime") } },
        { "dull bronze", new List<Bag> { new Bag(5, "drab tomato"), new Bag(4, "pale tan") } },
        { "dotted chartreuse", new List<Bag> { new Bag(2, "dark maroon"), new Bag(4, "mirrored black"), new Bag(4, "light orange") } },
        { "dotted aqua", new List<Bag> { new Bag(2, "mirrored maroon"), new Bag(2, "mirrored blue"), new Bag(3, "dark cyan"), new Bag(4, "dotted olive") } },
        { "striped indigo", new List<Bag> { new Bag(4, "mirrored gray"), new Bag(5, "light tan"), new Bag(4, "dotted tan") } },
        { "shiny magenta", new List<Bag> { new Bag(5, "dim chartreuse"), new Bag(2, "striped olive"), new Bag(5, "clear blue") } },
        { "bright lime", new List<Bag> { new Bag(4, "drab cyan"), new Bag(4, "striped chartreuse"), new Bag(1, "dotted yellow") } },
        { "dotted white", new List<Bag> { new Bag(1, "clear purple"), new Bag(1, "clear teal"), new Bag(1, "dotted cyan") } },
        { "dotted red", new List<Bag> { new Bag(3, "dark silver") } },
        { "dotted fuchsia", new List<Bag> { new Bag(1, "pale orange") } },
        { "pale aqua", new List<Bag> { new Bag(1, "dim beige"), new Bag(2, "shiny aqua"), new Bag(1, "faded gray") } },
        { "dotted tan", new List<Bag> { new Bag(3, "muted coral"), new Bag(1, "shiny fuchsia"), new Bag(5, "wavy tan") } },
        { "light bronze", new List<Bag> { new Bag(1, "drab lavender"), new Bag(5, "faded red"), new Bag(3, "light tan"), new Bag(1, "striped white") } },
        { "dim cyan", new List<Bag> { new Bag(1, "vibrant brown"), new Bag(3, "faded gray"), new Bag(5, "striped lime"), new Bag(5, "plaid beige") } },
        { "dim silver", new List<Bag> { new Bag(2, "striped gray"), new Bag(3, "plaid gold"), new Bag(5, "striped orange") } },
        { "shiny aqua", new List<Bag> { new Bag(3, "dotted tan"), new Bag(4, "muted brown"), new Bag(1, "mirrored maroon") } },
        { "drab tan", new List<Bag> { new Bag(4, "muted brown"), new Bag(1, "dotted lavender"), new Bag(2, "dull coral") } },
        { "shiny beige", new List<Bag> { new Bag(2, "muted blue"), new Bag(3, "wavy turquoise"), new Bag(5, "plaid silver") } },
        { "muted aqua", new List<Bag> { new Bag(2, "mirrored orange") } },
        { "striped beige", new List<Bag> { new Bag(3, "muted coral"), new Bag(4, "dim gold"), new Bag(1, "dim beige") } },
        { "light teal", new List<Bag> { new Bag(3, "faded green"), new Bag(5, "dark indigo"), new Bag(1, "pale gold") } }
    };
}