using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System;

public enum InsType
{
    jmp,
    acc,
    nop
};

public class Instruction
{
    public InsType Type { get; set;}
    public int Val { get; set;}
    public bool Executed { get; set; } = false;
}

public class Day8
{
    public static int ValueBeforeInf()
    {
        var accum = 0;
        var pos = 0;
        var instruction = Values.First();

        do 
        {
            switch(instruction.Type)
            {
                case InsType.acc:
                    accum += instruction.Val;
                    pos++;
                    break;

                case InsType.jmp:
                    pos += instruction.Val;
                    break;

                case InsType.nop:
                    pos += 1;
                    break;
            }
            instruction.Executed = true;
            instruction = Values[pos];
        }
        while(!instruction.Executed);

        return accum;
    }

    public static int BruteforceResult()
    {
        void SwitchType(int pos) =>
            Values[pos].Type = Values[pos].Type == InsType.jmp
                ? InsType.nop
                : InsType.jmp;

        void ResetToUnexecuted() 
        {
            foreach(var inst in Values) 
                inst.Executed = false;
        }

        for(int pos = 0; pos < Values.Count; pos++)
        {
            if (Values[pos].Type == InsType.acc)
                continue;
            
            Console.WriteLine($"Attempt to switch line #{pos}");

            SwitchType(pos);

            var result = ValuesUntilNotFixed();
            if(result != 0)
                return result;

            SwitchType(pos); //switch back
            ResetToUnexecuted();
        }

        return 0;
    }

    // return 0 if not fixed
    public static int ValuesUntilNotFixed()
    {
        var accum = 0;
        var pos = 0;
        var instruction = Values.First();

        do 
        {
            switch(instruction.Type)
            {
                case InsType.acc:
                    accum += instruction.Val;
                    pos++;
                    break;

                case InsType.jmp:
                    pos += instruction.Val;
                    break;

                case InsType.nop:
                    pos += 1;
                    break;
            }
            instruction.Executed = true;

            if(pos == Values.Count)
                return accum;
            
            instruction = Values[pos];
        }
        while(!instruction.Executed);

        return 0;
    }

    public static List<Instruction> Values = new List<Instruction>
    {
        new Instruction { Type = InsType.acc, Val = -7 },
        new Instruction { Type = InsType.acc, Val = +2 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.acc, Val = +14 },
        new Instruction { Type = InsType.jmp, Val = +191 },
        new Instruction { Type = InsType.acc, Val = +47 },
        new Instruction { Type = InsType.nop, Val = +339 },
        new Instruction { Type = InsType.acc, Val = +49 },
        new Instruction { Type = InsType.jmp, Val = +104 },
        new Instruction { Type = InsType.jmp, Val = +629 },
        new Instruction { Type = InsType.jmp, Val = +374 },
        new Instruction { Type = InsType.acc, Val = +24 },
        new Instruction { Type = InsType.jmp, Val = +220 },
        new Instruction { Type = InsType.nop, Val = +474 },
        new Instruction { Type = InsType.acc, Val = +25 },
        new Instruction { Type = InsType.jmp, Val = +340 },
        new Instruction { Type = InsType.acc, Val = +16 },
        new Instruction { Type = InsType.acc, Val = +3 },
        new Instruction { Type = InsType.acc, Val = +41 },
        new Instruction { Type = InsType.jmp, Val = +566 },
        new Instruction { Type = InsType.jmp, Val = +296 },
        new Instruction { Type = InsType.acc, Val = +15 },
        new Instruction { Type = InsType.jmp, Val = +452 },
        new Instruction { Type = InsType.acc, Val = +21 },
        new Instruction { Type = InsType.jmp, Val = +129 },
        new Instruction { Type = InsType.acc, Val = +10 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.acc, Val = +39 },
        new Instruction { Type = InsType.jmp, Val = +396 },
        new Instruction { Type = InsType.acc, Val = +5 },
        new Instruction { Type = InsType.acc, Val = -4 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.jmp, Val = +496 },
        new Instruction { Type = InsType.nop, Val = +181 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.acc, Val = +7 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.jmp, Val = +370 },
        new Instruction { Type = InsType.acc, Val = +16 },
        new Instruction { Type = InsType.acc, Val = -18 },
        new Instruction { Type = InsType.acc, Val = +47 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.jmp, Val = +99 },
        new Instruction { Type = InsType.nop, Val = +17 },
        new Instruction { Type = InsType.acc, Val = +25 },
        new Instruction { Type = InsType.acc, Val = -15 },
        new Instruction { Type = InsType.jmp, Val = +285 },
        new Instruction { Type = InsType.nop, Val = +545 },
        new Instruction { Type = InsType.nop, Val = +147 },
        new Instruction { Type = InsType.nop, Val = +479 },
        new Instruction { Type = InsType.acc, Val = -4 },
        new Instruction { Type = InsType.jmp, Val = +386 },
        new Instruction { Type = InsType.acc, Val = +36 },
        new Instruction { Type = InsType.acc, Val = -12 },
        new Instruction { Type = InsType.jmp, Val = +50 },
        new Instruction { Type = InsType.acc, Val = +37 },
        new Instruction { Type = InsType.nop, Val = +133 },
        new Instruction { Type = InsType.acc, Val = +11 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.jmp, Val = +32 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.nop, Val = +210 },
        new Instruction { Type = InsType.acc, Val = -15 },
        new Instruction { Type = InsType.acc, Val = -6 },
        new Instruction { Type = InsType.jmp, Val = +446 },
        new Instruction { Type = InsType.acc, Val = +25 },
        new Instruction { Type = InsType.acc, Val = +1 },
        new Instruction { Type = InsType.acc, Val = +17 },
        new Instruction { Type = InsType.acc, Val = -4 },
        new Instruction { Type = InsType.jmp, Val = +355 },
        new Instruction { Type = InsType.acc, Val = -4 },
        new Instruction { Type = InsType.jmp, Val = +292 },
        new Instruction { Type = InsType.acc, Val = +16 },
        new Instruction { Type = InsType.acc, Val = +44 },
        new Instruction { Type = InsType.acc, Val = +26 },
        new Instruction { Type = InsType.jmp, Val = +157 },
        new Instruction { Type = InsType.acc, Val = -18 },
        new Instruction { Type = InsType.acc, Val = +15 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.acc, Val = -3 },
        new Instruction { Type = InsType.jmp, Val = +46 },
        new Instruction { Type = InsType.acc, Val = +30 },
        new Instruction { Type = InsType.acc, Val = +16 },
        new Instruction { Type = InsType.jmp, Val = -7 },
        new Instruction { Type = InsType.acc, Val = +34 },
        new Instruction { Type = InsType.jmp, Val = +515 },
        new Instruction { Type = InsType.acc, Val = +11 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.acc, Val = -9 },
        new Instruction { Type = InsType.acc, Val = -3 },
        new Instruction { Type = InsType.jmp, Val = +548 },
        new Instruction { Type = InsType.jmp, Val = +278 },
        new Instruction { Type = InsType.nop, Val = +332 },
        new Instruction { Type = InsType.acc, Val = -19 },
        new Instruction { Type = InsType.acc, Val = +49 },
        new Instruction { Type = InsType.jmp, Val = +536 },
        new Instruction { Type = InsType.acc, Val = -9 },
        new Instruction { Type = InsType.acc, Val = +46 },
        new Instruction { Type = InsType.jmp, Val = +124 },
        new Instruction { Type = InsType.acc, Val = +41 },
        new Instruction { Type = InsType.acc, Val = +47 },
        new Instruction { Type = InsType.acc, Val = -5 },
        new Instruction { Type = InsType.acc, Val = -13 },
        new Instruction { Type = InsType.jmp, Val = +41 },
        new Instruction { Type = InsType.nop, Val = +178 },
        new Instruction { Type = InsType.acc, Val = +12 },
        new Instruction { Type = InsType.acc, Val = +45 },
        new Instruction { Type = InsType.jmp, Val = +461 },
        new Instruction { Type = InsType.acc, Val = +37 },
        new Instruction { Type = InsType.acc, Val = +12 },
        new Instruction { Type = InsType.acc, Val = +38 },
        new Instruction { Type = InsType.jmp, Val = -68 },
        new Instruction { Type = InsType.acc, Val = -6 },
        new Instruction { Type = InsType.nop, Val = +494 },
        new Instruction { Type = InsType.acc, Val = -9 },
        new Instruction { Type = InsType.jmp, Val = -63 },
        new Instruction { Type = InsType.acc, Val = +42 },
        new Instruction { Type = InsType.acc, Val = +16 },
        new Instruction { Type = InsType.acc, Val = +30 },
        new Instruction { Type = InsType.jmp, Val = +70 },
        new Instruction { Type = InsType.acc, Val = +13 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.acc, Val = -18 },
        new Instruction { Type = InsType.jmp, Val = +528 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.jmp, Val = +493 },
        new Instruction { Type = InsType.nop, Val = +402 },
        new Instruction { Type = InsType.jmp, Val = +381 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.jmp, Val = +372 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.acc, Val = +25 },
        new Instruction { Type = InsType.jmp, Val = +425 },
        new Instruction { Type = InsType.acc, Val = -10 },
        new Instruction { Type = InsType.jmp, Val = +510 },
        new Instruction { Type = InsType.jmp, Val = +439 },
        new Instruction { Type = InsType.nop, Val = +78 },
        new Instruction { Type = InsType.acc, Val = +36 },
        new Instruction { Type = InsType.acc, Val = +7 },
        new Instruction { Type = InsType.nop, Val = +281 },
        new Instruction { Type = InsType.jmp, Val = +504 },
        new Instruction { Type = InsType.jmp, Val = -108 },
        new Instruction { Type = InsType.acc, Val = +40 },
        new Instruction { Type = InsType.jmp, Val = -122 },
        new Instruction { Type = InsType.acc, Val = +23 },
        new Instruction { Type = InsType.acc, Val = -2 },
        new Instruction { Type = InsType.acc, Val = +7 },
        new Instruction { Type = InsType.jmp, Val = +370 },
        new Instruction { Type = InsType.acc, Val = +25 },
        new Instruction { Type = InsType.nop, Val = -5 },
        new Instruction { Type = InsType.acc, Val = +33 },
        new Instruction { Type = InsType.acc, Val = +37 },
        new Instruction { Type = InsType.jmp, Val = +70 },
        new Instruction { Type = InsType.acc, Val = -6 },
        new Instruction { Type = InsType.nop, Val = +336 },
        new Instruction { Type = InsType.jmp, Val = +34 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.acc, Val = -18 },
        new Instruction { Type = InsType.jmp, Val = +473 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.acc, Val = +4 },
        new Instruction { Type = InsType.acc, Val = +25 },
        new Instruction { Type = InsType.jmp, Val = -87 },
        new Instruction { Type = InsType.acc, Val = -12 },
        new Instruction { Type = InsType.acc, Val = +47 },
        new Instruction { Type = InsType.acc, Val = +49 },
        new Instruction { Type = InsType.jmp, Val = +323 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.jmp, Val = +167 },
        new Instruction { Type = InsType.acc, Val = -10 },
        new Instruction { Type = InsType.acc, Val = +45 },
        new Instruction { Type = InsType.jmp, Val = +355 },
        new Instruction { Type = InsType.acc, Val = +32 },
        new Instruction { Type = InsType.acc, Val = +38 },
        new Instruction { Type = InsType.acc, Val = +2 },
        new Instruction { Type = InsType.jmp, Val = -93 },
        new Instruction { Type = InsType.acc, Val = +8 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.acc, Val = +4 },
        new Instruction { Type = InsType.acc, Val = -1 },
        new Instruction { Type = InsType.jmp, Val = +108 },
        new Instruction { Type = InsType.nop, Val = +164 },
        new Instruction { Type = InsType.acc, Val = +41 },
        new Instruction { Type = InsType.jmp, Val = +440 },
        new Instruction { Type = InsType.acc, Val = -16 },
        new Instruction { Type = InsType.acc, Val = +47 },
        new Instruction { Type = InsType.jmp, Val = +355 },
        new Instruction { Type = InsType.acc, Val = -13 },
        new Instruction { Type = InsType.acc, Val = +29 },
        new Instruction { Type = InsType.acc, Val = +50 },
        new Instruction { Type = InsType.jmp, Val = -101 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.jmp, Val = +316 },
        new Instruction { Type = InsType.acc, Val = +27 },
        new Instruction { Type = InsType.acc, Val = +31 },
        new Instruction { Type = InsType.nop, Val = -29 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.jmp, Val = +250 },
        new Instruction { Type = InsType.acc, Val = +12 },
        new Instruction { Type = InsType.acc, Val = -13 },
        new Instruction { Type = InsType.jmp, Val = +73 },
        new Instruction { Type = InsType.jmp, Val = +72 },
        new Instruction { Type = InsType.acc, Val = +36 },
        new Instruction { Type = InsType.acc, Val = +44 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.jmp, Val = -33 },
        new Instruction { Type = InsType.acc, Val = -18 },
        new Instruction { Type = InsType.acc, Val = +16 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.acc, Val = +6 },
        new Instruction { Type = InsType.jmp, Val = +104 },
        new Instruction { Type = InsType.jmp, Val = +295 },
        new Instruction { Type = InsType.acc, Val = +10 },
        new Instruction { Type = InsType.nop, Val = -80 },
        new Instruction { Type = InsType.jmp, Val = +74 },
        new Instruction { Type = InsType.acc, Val = -13 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.acc, Val = +22 },
        new Instruction { Type = InsType.acc, Val = +50 },
        new Instruction { Type = InsType.jmp, Val = +280 },
        new Instruction { Type = InsType.jmp, Val = +265 },
        new Instruction { Type = InsType.jmp, Val = +278 },
        new Instruction { Type = InsType.acc, Val = +46 },
        new Instruction { Type = InsType.acc, Val = -14 },
        new Instruction { Type = InsType.acc, Val = -17 },
        new Instruction { Type = InsType.jmp, Val = -19 },
        new Instruction { Type = InsType.acc, Val = +39 },
        new Instruction { Type = InsType.acc, Val = +31 },
        new Instruction { Type = InsType.acc, Val = -11 },
        new Instruction { Type = InsType.jmp, Val = +400 },
        new Instruction { Type = InsType.jmp, Val = +80 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.acc, Val = +27 },
        new Instruction { Type = InsType.nop, Val = +209 },
        new Instruction { Type = InsType.jmp, Val = -184 },
        new Instruction { Type = InsType.acc, Val = +12 },
        new Instruction { Type = InsType.acc, Val = +21 },
        new Instruction { Type = InsType.acc, Val = +23 },
        new Instruction { Type = InsType.jmp, Val = +352 },
        new Instruction { Type = InsType.acc, Val = +29 },
        new Instruction { Type = InsType.jmp, Val = -5 },
        new Instruction { Type = InsType.acc, Val = +15 },
        new Instruction { Type = InsType.acc, Val = +7 },
        new Instruction { Type = InsType.jmp, Val = +6 },
        new Instruction { Type = InsType.acc, Val = +31 },
        new Instruction { Type = InsType.acc, Val = -5 },
        new Instruction { Type = InsType.nop, Val = +83 },
        new Instruction { Type = InsType.acc, Val = +31 },
        new Instruction { Type = InsType.jmp, Val = -239 },
        new Instruction { Type = InsType.acc, Val = +8 },
        new Instruction { Type = InsType.acc, Val = -2 },
        new Instruction { Type = InsType.acc, Val = +49 },
        new Instruction { Type = InsType.acc, Val = -12 },
        new Instruction { Type = InsType.jmp, Val = -52 },
        new Instruction { Type = InsType.acc, Val = -15 },
        new Instruction { Type = InsType.acc, Val = -14 },
        new Instruction { Type = InsType.jmp, Val = +126 },
        new Instruction { Type = InsType.jmp, Val = +385 },
        new Instruction { Type = InsType.acc, Val = +30 },
        new Instruction { Type = InsType.acc, Val = -5 },
        new Instruction { Type = InsType.acc, Val = +6 },
        new Instruction { Type = InsType.jmp, Val = -187 },
        new Instruction { Type = InsType.acc, Val = +39 },
        new Instruction { Type = InsType.acc, Val = +40 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.acc, Val = +6 },
        new Instruction { Type = InsType.jmp, Val = +24 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.jmp, Val = +131 },
        new Instruction { Type = InsType.jmp, Val = -127 },
        new Instruction { Type = InsType.acc, Val = +8 },
        new Instruction { Type = InsType.acc, Val = +30 },
        new Instruction { Type = InsType.jmp, Val = -265 },
        new Instruction { Type = InsType.acc, Val = -2 },
        new Instruction { Type = InsType.jmp, Val = -265 },
        new Instruction { Type = InsType.acc, Val = +22 },
        new Instruction { Type = InsType.acc, Val = -19 },
        new Instruction { Type = InsType.acc, Val = -9 },
        new Instruction { Type = InsType.nop, Val = +10 },
        new Instruction { Type = InsType.jmp, Val = +148 },
        new Instruction { Type = InsType.acc, Val = -14 },
        new Instruction { Type = InsType.acc, Val = +38 },
        new Instruction { Type = InsType.acc, Val = +50 },
        new Instruction { Type = InsType.acc, Val = -7 },
        new Instruction { Type = InsType.jmp, Val = +197 },
        new Instruction { Type = InsType.acc, Val = +11 },
        new Instruction { Type = InsType.acc, Val = +22 },
        new Instruction { Type = InsType.jmp, Val = +201 },
        new Instruction { Type = InsType.jmp, Val = -155 },
        new Instruction { Type = InsType.jmp, Val = -32 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.nop, Val = -50 },
        new Instruction { Type = InsType.jmp, Val = -99 },
        new Instruction { Type = InsType.jmp, Val = -5 },
        new Instruction { Type = InsType.acc, Val = +11 },
        new Instruction { Type = InsType.acc, Val = -18 },
        new Instruction { Type = InsType.jmp, Val = -186 },
        new Instruction { Type = InsType.acc, Val = +6 },
        new Instruction { Type = InsType.acc, Val = +43 },
        new Instruction { Type = InsType.jmp, Val = +159 },
        new Instruction { Type = InsType.jmp, Val = +249 },
        new Instruction { Type = InsType.acc, Val = +44 },
        new Instruction { Type = InsType.acc, Val = +29 },
        new Instruction { Type = InsType.nop, Val = +313 },
        new Instruction { Type = InsType.acc, Val = +23 },
        new Instruction { Type = InsType.jmp, Val = +311 },
        new Instruction { Type = InsType.jmp, Val = +152 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.acc, Val = +41 },
        new Instruction { Type = InsType.jmp, Val = -251 },
        new Instruction { Type = InsType.jmp, Val = +102 },
        new Instruction { Type = InsType.nop, Val = -17 },
        new Instruction { Type = InsType.nop, Val = +176 },
        new Instruction { Type = InsType.jmp, Val = +40 },
        new Instruction { Type = InsType.acc, Val = +28 },
        new Instruction { Type = InsType.jmp, Val = -21 },
        new Instruction { Type = InsType.acc, Val = -4 },
        new Instruction { Type = InsType.acc, Val = -10 },
        new Instruction { Type = InsType.acc, Val = -19 },
        new Instruction { Type = InsType.acc, Val = -15 },
        new Instruction { Type = InsType.jmp, Val = +23 },
        new Instruction { Type = InsType.nop, Val = +144 },
        new Instruction { Type = InsType.acc, Val = +9 },
        new Instruction { Type = InsType.acc, Val = +18 },
        new Instruction { Type = InsType.jmp, Val = +141 },
        new Instruction { Type = InsType.acc, Val = -19 },
        new Instruction { Type = InsType.acc, Val = -10 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.jmp, Val = -7 },
        new Instruction { Type = InsType.acc, Val = +46 },
        new Instruction { Type = InsType.acc, Val = -9 },
        new Instruction { Type = InsType.jmp, Val = -174 },
        new Instruction { Type = InsType.acc, Val = +30 },
        new Instruction { Type = InsType.acc, Val = +30 },
        new Instruction { Type = InsType.jmp, Val = -201 },
        new Instruction { Type = InsType.acc, Val = +34 },
        new Instruction { Type = InsType.acc, Val = +24 },
        new Instruction { Type = InsType.acc, Val = +37 },
        new Instruction { Type = InsType.acc, Val = +44 },
        new Instruction { Type = InsType.jmp, Val = -158 },
        new Instruction { Type = InsType.acc, Val = +4 },
        new Instruction { Type = InsType.acc, Val = +39 },
        new Instruction { Type = InsType.jmp, Val = -52 },
        new Instruction { Type = InsType.jmp, Val = -329 },
        new Instruction { Type = InsType.jmp, Val = +68 },
        new Instruction { Type = InsType.acc, Val = +25 },
        new Instruction { Type = InsType.nop, Val = -105 },
        new Instruction { Type = InsType.acc, Val = -15 },
        new Instruction { Type = InsType.acc, Val = +34 },
        new Instruction { Type = InsType.jmp, Val = -6 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.acc, Val = +1 },
        new Instruction { Type = InsType.jmp, Val = +163 },
        new Instruction { Type = InsType.nop, Val = -285 },
        new Instruction { Type = InsType.acc, Val = +8 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.jmp, Val = +143 },
        new Instruction { Type = InsType.acc, Val = -3 },
        new Instruction { Type = InsType.nop, Val = -269 },
        new Instruction { Type = InsType.acc, Val = -16 },
        new Instruction { Type = InsType.jmp, Val = -310 },
        new Instruction { Type = InsType.acc, Val = -5 },
        new Instruction { Type = InsType.jmp, Val = -304 },
        new Instruction { Type = InsType.acc, Val = +45 },
        new Instruction { Type = InsType.nop, Val = -231 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.jmp, Val = +245 },
        new Instruction { Type = InsType.nop, Val = -243 },
        new Instruction { Type = InsType.jmp, Val = +187 },
        new Instruction { Type = InsType.acc, Val = -6 },
        new Instruction { Type = InsType.acc, Val = +7 },
        new Instruction { Type = InsType.acc, Val = +17 },
        new Instruction { Type = InsType.acc, Val = +6 },
        new Instruction { Type = InsType.jmp, Val = -111 },
        new Instruction { Type = InsType.acc, Val = +24 },
        new Instruction { Type = InsType.acc, Val = -10 },
        new Instruction { Type = InsType.acc, Val = +21 },
        new Instruction { Type = InsType.jmp, Val = -97 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.acc, Val = -12 },
        new Instruction { Type = InsType.acc, Val = +10 },
        new Instruction { Type = InsType.jmp, Val = +127 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.jmp, Val = -211 },
        new Instruction { Type = InsType.acc, Val = -11 },
        new Instruction { Type = InsType.acc, Val = +36 },
        new Instruction { Type = InsType.acc, Val = +45 },
        new Instruction { Type = InsType.acc, Val = -19 },
        new Instruction { Type = InsType.jmp, Val = -182 },
        new Instruction { Type = InsType.jmp, Val = -366 },
        new Instruction { Type = InsType.acc, Val = +38 },
        new Instruction { Type = InsType.acc, Val = -11 },
        new Instruction { Type = InsType.acc, Val = +32 },
        new Instruction { Type = InsType.jmp, Val = -260 },
        new Instruction { Type = InsType.acc, Val = +6 },
        new Instruction { Type = InsType.acc, Val = +31 },
        new Instruction { Type = InsType.jmp, Val = +3 },
        new Instruction { Type = InsType.acc, Val = +5 },
        new Instruction { Type = InsType.jmp, Val = +101 },
        new Instruction { Type = InsType.jmp, Val = -64 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.acc, Val = +5 },
        new Instruction { Type = InsType.nop, Val = +40 },
        new Instruction { Type = InsType.acc, Val = -13 },
        new Instruction { Type = InsType.jmp, Val = +95 },
        new Instruction { Type = InsType.nop, Val = +76 },
        new Instruction { Type = InsType.acc, Val = +44 },
        new Instruction { Type = InsType.acc, Val = +43 },
        new Instruction { Type = InsType.acc, Val = +43 },
        new Instruction { Type = InsType.jmp, Val = +196 },
        new Instruction { Type = InsType.acc, Val = +34 },
        new Instruction { Type = InsType.jmp, Val = +161 },
        new Instruction { Type = InsType.acc, Val = +5 },
        new Instruction { Type = InsType.acc, Val = +45 },
        new Instruction { Type = InsType.acc, Val = +7 },
        new Instruction { Type = InsType.jmp, Val = +20 },
        new Instruction { Type = InsType.acc, Val = +13 },
        new Instruction { Type = InsType.jmp, Val = -127 },
        new Instruction { Type = InsType.acc, Val = +5 },
        new Instruction { Type = InsType.acc, Val = +18 },
        new Instruction { Type = InsType.jmp, Val = -239 },
        new Instruction { Type = InsType.jmp, Val = -76 },
        new Instruction { Type = InsType.nop, Val = +214 },
        new Instruction { Type = InsType.jmp, Val = -284 },
        new Instruction { Type = InsType.acc, Val = +10 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.jmp, Val = -81 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.acc, Val = -3 },
        new Instruction { Type = InsType.jmp, Val = -55 },
        new Instruction { Type = InsType.nop, Val = -288 },
        new Instruction { Type = InsType.acc, Val = +37 },
        new Instruction { Type = InsType.acc, Val = +1 },
        new Instruction { Type = InsType.acc, Val = -12 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.nop, Val = +91 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.acc, Val = +18 },
        new Instruction { Type = InsType.jmp, Val = +4 },
        new Instruction { Type = InsType.acc, Val = -7 },
        new Instruction { Type = InsType.acc, Val = -10 },
        new Instruction { Type = InsType.jmp, Val = -229 },
        new Instruction { Type = InsType.nop, Val = -230 },
        new Instruction { Type = InsType.nop, Val = +45 },
        new Instruction { Type = InsType.acc, Val = +37 },
        new Instruction { Type = InsType.jmp, Val = +127 },
        new Instruction { Type = InsType.jmp, Val = +69 },
        new Instruction { Type = InsType.jmp, Val = -153 },
        new Instruction { Type = InsType.acc, Val = -15 },
        new Instruction { Type = InsType.acc, Val = -19 },
        new Instruction { Type = InsType.acc, Val = +32 },
        new Instruction { Type = InsType.jmp, Val = -33 },
        new Instruction { Type = InsType.nop, Val = +164 },
        new Instruction { Type = InsType.acc, Val = +32 },
        new Instruction { Type = InsType.jmp, Val = -133 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.jmp, Val = +8 },
        new Instruction { Type = InsType.acc, Val = -11 },
        new Instruction { Type = InsType.nop, Val = +82 },
        new Instruction { Type = InsType.acc, Val = +7 },
        new Instruction { Type = InsType.acc, Val = +40 },
        new Instruction { Type = InsType.jmp, Val = +79 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.jmp, Val = +159 },
        new Instruction { Type = InsType.acc, Val = +4 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.nop, Val = +143 },
        new Instruction { Type = InsType.jmp, Val = -351 },
        new Instruction { Type = InsType.acc, Val = -7 },
        new Instruction { Type = InsType.jmp, Val = +78 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.acc, Val = +4 },
        new Instruction { Type = InsType.jmp, Val = +20 },
        new Instruction { Type = InsType.jmp, Val = -3 },
        new Instruction { Type = InsType.acc, Val = +2 },
        new Instruction { Type = InsType.acc, Val = +23 },
        new Instruction { Type = InsType.jmp, Val = -256 },
        new Instruction { Type = InsType.acc, Val = +33 },
        new Instruction { Type = InsType.jmp, Val = -473 },
        new Instruction { Type = InsType.acc, Val = +29 },
        new Instruction { Type = InsType.acc, Val = -13 },
        new Instruction { Type = InsType.jmp, Val = +77 },
        new Instruction { Type = InsType.jmp, Val = +158 },
        new Instruction { Type = InsType.acc, Val = -16 },
        new Instruction { Type = InsType.jmp, Val = -10 },
        new Instruction { Type = InsType.jmp, Val = -181 },
        new Instruction { Type = InsType.jmp, Val = -135 },
        new Instruction { Type = InsType.nop, Val = -95 },
        new Instruction { Type = InsType.acc, Val = +46 },
        new Instruction { Type = InsType.acc, Val = +39 },
        new Instruction { Type = InsType.acc, Val = -3 },
        new Instruction { Type = InsType.jmp, Val = -94 },
        new Instruction { Type = InsType.jmp, Val = -67 },
        new Instruction { Type = InsType.acc, Val = +49 },
        new Instruction { Type = InsType.nop, Val = -78 },
        new Instruction { Type = InsType.nop, Val = -9 },
        new Instruction { Type = InsType.jmp, Val = +107 },
        new Instruction { Type = InsType.acc, Val = -19 },
        new Instruction { Type = InsType.acc, Val = -1 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.acc, Val = -4 },
        new Instruction { Type = InsType.jmp, Val = -189 },
        new Instruction { Type = InsType.acc, Val = +11 },
        new Instruction { Type = InsType.jmp, Val = -106 },
        new Instruction { Type = InsType.jmp, Val = -200 },
        new Instruction { Type = InsType.jmp, Val = +122 },
        new Instruction { Type = InsType.acc, Val = +8 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.acc, Val = +15 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.jmp, Val = -493 },
        new Instruction { Type = InsType.acc, Val = +13 },
        new Instruction { Type = InsType.jmp, Val = -8 },
        new Instruction { Type = InsType.acc, Val = +36 },
        new Instruction { Type = InsType.acc, Val = -10 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.acc, Val = +9 },
        new Instruction { Type = InsType.jmp, Val = +7 },
        new Instruction { Type = InsType.jmp, Val = +85 },
        new Instruction { Type = InsType.acc, Val = +22 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.nop, Val = -124 },
        new Instruction { Type = InsType.jmp, Val = -517 },
        new Instruction { Type = InsType.jmp, Val = -338 },
        new Instruction { Type = InsType.acc, Val = +39 },
        new Instruction { Type = InsType.nop, Val = -438 },
        new Instruction { Type = InsType.acc, Val = -11 },
        new Instruction { Type = InsType.jmp, Val = +69 },
        new Instruction { Type = InsType.acc, Val = +8 },
        new Instruction { Type = InsType.acc, Val = +34 },
        new Instruction { Type = InsType.acc, Val = +34 },
        new Instruction { Type = InsType.acc, Val = -9 },
        new Instruction { Type = InsType.jmp, Val = -205 },
        new Instruction { Type = InsType.nop, Val = -528 },
        new Instruction { Type = InsType.jmp, Val = -495 },
        new Instruction { Type = InsType.acc, Val = +47 },
        new Instruction { Type = InsType.acc, Val = +40 },
        new Instruction { Type = InsType.acc, Val = +30 },
        new Instruction { Type = InsType.jmp, Val = -328 },
        new Instruction { Type = InsType.acc, Val = -2 },
        new Instruction { Type = InsType.acc, Val = +41 },
        new Instruction { Type = InsType.jmp, Val = -475 },
        new Instruction { Type = InsType.acc, Val = +42 },
        new Instruction { Type = InsType.acc, Val = +48 },
        new Instruction { Type = InsType.acc, Val = +2 },
        new Instruction { Type = InsType.acc, Val = +7 },
        new Instruction { Type = InsType.jmp, Val = -415 },
        new Instruction { Type = InsType.nop, Val = -249 },
        new Instruction { Type = InsType.acc, Val = -3 },
        new Instruction { Type = InsType.jmp, Val = +65 },
        new Instruction { Type = InsType.acc, Val = +23 },
        new Instruction { Type = InsType.nop, Val = -4 },
        new Instruction { Type = InsType.jmp, Val = -254 },
        new Instruction { Type = InsType.acc, Val = -12 },
        new Instruction { Type = InsType.acc, Val = +22 },
        new Instruction { Type = InsType.acc, Val = +27 },
        new Instruction { Type = InsType.jmp, Val = -176 },
        new Instruction { Type = InsType.jmp, Val = -408 },
        new Instruction { Type = InsType.acc, Val = -15 },
        new Instruction { Type = InsType.acc, Val = +14 },
        new Instruction { Type = InsType.acc, Val = +30 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.jmp, Val = -363 },
        new Instruction { Type = InsType.jmp, Val = -426 },
        new Instruction { Type = InsType.acc, Val = +38 },
        new Instruction { Type = InsType.nop, Val = -425 },
        new Instruction { Type = InsType.jmp, Val = -440 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.acc, Val = +22 },
        new Instruction { Type = InsType.jmp, Val = -63 },
        new Instruction { Type = InsType.jmp, Val = -406 },
        new Instruction { Type = InsType.nop, Val = -445 },
        new Instruction { Type = InsType.acc, Val = -5 },
        new Instruction { Type = InsType.acc, Val = +34 },
        new Instruction { Type = InsType.nop, Val = -425 },
        new Instruction { Type = InsType.jmp, Val = +65 },
        new Instruction { Type = InsType.acc, Val = +33 },
        new Instruction { Type = InsType.jmp, Val = -91 },
        new Instruction { Type = InsType.acc, Val = -12 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.jmp, Val = -541 },
        new Instruction { Type = InsType.nop, Val = -489 },
        new Instruction { Type = InsType.jmp, Val = -490 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.acc, Val = +20 },
        new Instruction { Type = InsType.acc, Val = +38 },
        new Instruction { Type = InsType.acc, Val = -18 },
        new Instruction { Type = InsType.jmp, Val = -548 },
        new Instruction { Type = InsType.acc, Val = +43 },
        new Instruction { Type = InsType.acc, Val = -7 },
        new Instruction { Type = InsType.jmp, Val = -351 },
        new Instruction { Type = InsType.acc, Val = -9 },
        new Instruction { Type = InsType.acc, Val = +50 },
        new Instruction { Type = InsType.acc, Val = +1 },
        new Instruction { Type = InsType.nop, Val = -587 },
        new Instruction { Type = InsType.jmp, Val = -230 },
        new Instruction { Type = InsType.jmp, Val = +1 },
        new Instruction { Type = InsType.nop, Val = +43 },
        new Instruction { Type = InsType.jmp, Val = -65 },
        new Instruction { Type = InsType.acc, Val = +31 },
        new Instruction { Type = InsType.acc, Val = +5 },
        new Instruction { Type = InsType.acc, Val = +1 },
        new Instruction { Type = InsType.jmp, Val = -105 },
        new Instruction { Type = InsType.nop, Val = -477 },
        new Instruction { Type = InsType.acc, Val = +21 },
        new Instruction { Type = InsType.nop, Val = -92 },
        new Instruction { Type = InsType.jmp, Val = -263 },
        new Instruction { Type = InsType.acc, Val = +28 },
        new Instruction { Type = InsType.jmp, Val = -265 },
        new Instruction { Type = InsType.jmp, Val = -311 },
        new Instruction { Type = InsType.acc, Val = +2 },
        new Instruction { Type = InsType.acc, Val = +23 },
        new Instruction { Type = InsType.acc, Val = +50 },
        new Instruction { Type = InsType.jmp, Val = -4 },
        new Instruction { Type = InsType.acc, Val = +42 },
        new Instruction { Type = InsType.acc, Val = +42 },
        new Instruction { Type = InsType.acc, Val = +31 },
        new Instruction { Type = InsType.jmp, Val = -167 },
        new Instruction { Type = InsType.acc, Val = +49 },
        new Instruction { Type = InsType.acc, Val = +46 },
        new Instruction { Type = InsType.jmp, Val = -73 },
        new Instruction { Type = InsType.nop, Val = -135 },
        new Instruction { Type = InsType.acc, Val = +43 },
        new Instruction { Type = InsType.jmp, Val = -236 },
        new Instruction { Type = InsType.acc, Val = -14 },
        new Instruction { Type = InsType.acc, Val = -3 },
        new Instruction { Type = InsType.jmp, Val = -406 },
        new Instruction { Type = InsType.acc, Val = +2 },
        new Instruction { Type = InsType.acc, Val = -3 },
        new Instruction { Type = InsType.acc, Val = +47 },
        new Instruction { Type = InsType.jmp, Val = -420 },
        new Instruction { Type = InsType.acc, Val = -8 },
        new Instruction { Type = InsType.acc, Val = +18 },
        new Instruction { Type = InsType.jmp, Val = -604 },
        new Instruction { Type = InsType.jmp, Val = -218 },
        new Instruction { Type = InsType.acc, Val = +37 },
        new Instruction { Type = InsType.acc, Val = -16 },
        new Instruction { Type = InsType.nop, Val = -278 },
        new Instruction { Type = InsType.acc, Val = -15 },
        new Instruction { Type = InsType.jmp, Val = -214 },
        new Instruction { Type = InsType.acc, Val = -6 },
        new Instruction { Type = InsType.acc, Val = +18 },
        new Instruction { Type = InsType.acc, Val = +7 },
        new Instruction { Type = InsType.acc, Val = +0 },
        new Instruction { Type = InsType.jmp, Val = -252 },
        new Instruction { Type = InsType.acc, Val = +14 },
        new Instruction { Type = InsType.jmp, Val = -266 },
        new Instruction { Type = InsType.acc, Val = +27 },
        new Instruction { Type = InsType.acc, Val = -16 },
        new Instruction { Type = InsType.nop, Val = -533 },
        new Instruction { Type = InsType.nop, Val = -534 },
        new Instruction { Type = InsType.jmp, Val = +1 }
    };
}