using System.Collections.Generic;

public class Pass
{
    public int Min { get; set; }
    public int Max { get; set; }
    public char Symbol { get; set; }
    public string Value { get; set; }

}

public class Day2
{
    public static int RightPasswordsCount()
    {
        var correct = 0;
        foreach (var pass in Values)
        {
            //Console.WriteLine($"pass: {pass.Value} min: {pass.Min} max: {pass.Max} symb: {pass.Symbol}");
            var minChr = pass.Value[pass.Min-1];
            var maxChr = pass.Value[pass.Max-1];
            //Console.WriteLine($"maxChr: {minChr} maxChr: {maxChr}");
            
            var minIsRight = /*pass.Value.Count() > pass.Min && */pass.Value[pass.Min-1] == pass.Symbol;
            var maxIsRight = /*pass.Value.Count() > pass.Max && */pass.Value[pass.Max-1] == pass.Symbol;
            if(minIsRight ^ maxIsRight)
                correct++;
            /*var count = pass.Value.Count(p => p == pass.Symbol);
            if (count >= pass.Min && count <= pass.Max)
                correct++;*/
            
        }
        return correct;
    }

    public static List<Pass> Values = new List<Pass> { 
        new Pass { Min = 1, Max = 2, Symbol = 'x', Value = "xpxc" },
        new Pass { Min = 1, Max = 5, Symbol = 'b', Value = "bwlbbbbcq" },
        new Pass { Min = 3, Max = 5, Symbol = 'v', Value = "qvjjdhvl" },
        new Pass { Min = 9, Max = 12, Symbol = 't', Value = "ttfjvvtgxtctrntnhtt" },
        new Pass { Min = 3, Max = 4, Symbol = 'r', Value = "rqjw"},
        new Pass { Min = 3, Max = 7, Symbol = 'p', Value = "ppfpppppp"},
        new Pass { Min = 5, Max = 6, Symbol = 'q', Value = "qqqqgq"},
        new Pass { Min = 7, Max = 10, Symbol = 'v', Value = "gpvgmqkvxgbvs"},
        new Pass { Min = 4, Max = 12, Symbol = 'b', Value = "kkdnrhwzbbbb"},
        new Pass { Min = 3, Max = 7, Symbol = 'r', Value = "rrkwrshls"},
        new Pass { Min = 3, Max = 4, Symbol = 'l', Value = "ldltwzclnrllhkb"},
        new Pass { Min = 4, Max = 6, Symbol = 'm', Value = "mfcmmdvmmmm"},
        new Pass { Min = 6, Max = 16, Symbol = 'c', Value = "ccccczcccccccccgcc"},
        new Pass { Min = 5, Max = 7, Symbol = 'k', Value = "kkppkrr"},
        new Pass { Min = 2, Max = 5, Symbol = 'p', Value = "bpppmpcjrgwp"},
        new Pass { Min = 8, Max = 14, Symbol = 'c', Value = "dcwklzcckccwdw"},
        new Pass { Min = 4, Max = 7, Symbol = 'j', Value = "qhjjjhsj"},
        new Pass { Min = 2, Max = 5, Symbol = 'c', Value = "jcdclznbzb"},
        new Pass { Min = 7, Max = 8, Symbol = 'x', Value = "xxxxxxxsxxxxlxxxxxx"},
        new Pass { Min = 6, Max = 7, Symbol = 's', Value = "rhsstssmvssss"},
        new Pass { Min = 8, Max = 16, Symbol = 'j', Value = "rhsxwjrtpjjjjxhcjhx"},
        new Pass { Min = 13, Max = 14, Symbol = 'q', Value = "lqmqqqzsvqqjqq"},
        new Pass { Min = 5, Max = 7, Symbol = 'g', Value = "gggsfggj"},
        new Pass { Min = 15, Max = 16, Symbol = 's', Value = "ssssssssssssssxd"},
        new Pass { Min = 3, Max = 5, Symbol = 'd', Value = "dmwsm"},
        new Pass { Min = 4, Max = 5, Symbol = 'v', Value = "vbvvvg"},
        new Pass { Min = 5, Max = 6, Symbol = 'f', Value = "jfzbgfp"},
        new Pass { Min = 1, Max = 4, Symbol = 'k', Value = "qkkkk"},
        new Pass { Min = 11, Max = 15, Symbol = 'l', Value = "lllllllllllllln"},
        new Pass { Min = 12, Max = 16, Symbol = 'n', Value = "nfpnnnnnnhncnjnnls"},
        new Pass { Min = 6, Max = 8, Symbol = 'l', Value = "llllllllll"},
        new Pass { Min = 13, Max = 15, Symbol = 'p', Value = "pppppppppppphppp"},
        new Pass { Min = 4, Max = 9, Symbol = 'k', Value = "bkvqvwkgk"},
        new Pass { Min = 1, Max = 3, Symbol = 'j', Value = "jsrg"},
        new Pass { Min = 10, Max = 14, Symbol = 'r', Value = "rrvfrvrrrrtrrmsr"},
        new Pass { Min = 2, Max = 4, Symbol = 'r', Value = "tcfnd"},
        new Pass { Min = 5, Max = 6, Symbol = 't', Value = "ttwtjk"},
        new Pass { Min = 7, Max = 18, Symbol = 'h', Value = "wjjfhphhbqlvqkhjwhk"},
        new Pass { Min = 6, Max = 9, Symbol = 'p', Value = "phkkzvppppjpcpnfpsxt"},
        new Pass { Min = 5, Max = 6, Symbol = 'f', Value = "ffffmfffffff"},
        new Pass { Min = 9, Max = 16, Symbol = 'p', Value = "gbwsmxplndwmrpps"},
        new Pass { Min = 1, Max = 6, Symbol = 's', Value = "sczssw"},
        new Pass { Min = 5, Max = 14, Symbol = 't', Value = "ctxlqhrlvvdttwlnt"},
        new Pass { Min = 2, Max = 5, Symbol = 'n', Value = "nndkqnnft"},
        new Pass { Min = 7, Max = 8, Symbol = 'c', Value = "zclccrwc"},
        new Pass { Min = 4, Max = 11, Symbol = 'q', Value = "pqrqdkpqbjshn"},
        new Pass { Min = 5, Max = 6, Symbol = 'm', Value = "nmcmrbmfcgmfw"},
        new Pass { Min = 16, Max = 17, Symbol = 'h', Value = "hhhhhhhxhhrhhhhhlh"},
        new Pass { Min = 5, Max = 6, Symbol = 'v', Value = "vvvvvv"},
        new Pass { Min = 2, Max = 11, Symbol = 'm', Value = "wpsmlpznxdkhs"},
        new Pass { Min = 3, Max = 4, Symbol = 's', Value = "sswf"},
        new Pass { Min = 2, Max = 3, Symbol = 's', Value = "hsbczzspqkwjr"},
        new Pass { Min = 4, Max = 7, Symbol = 's', Value = "zsjrrsvssss"},
        new Pass { Min = 11, Max = 16, Symbol = 'j', Value = "hpjdcwpjjnjfgkjlxt"},
        new Pass { Min = 5, Max = 7, Symbol = 'b', Value = "rcbbbbg"},
        new Pass { Min = 13, Max = 15, Symbol = 'w', Value = "wwwwwwwwwwwwwwww"},
        new Pass { Min = 1, Max = 6, Symbol = 'c', Value = "cccmgc"},
        new Pass { Min = 2, Max = 4, Symbol = 'v', Value = "vvgv"},
        new Pass { Min = 4, Max = 5, Symbol = 'm', Value = "mfmmhms"},
        new Pass { Min = 1, Max = 3, Symbol = 't', Value = "mntqgkdfjsxzptk"},
        new Pass { Min = 2, Max = 7, Symbol = 'v', Value = "nvnqmvv"},
        new Pass { Min = 19, Max = 20, Symbol = 'c', Value = "ccccccccccccccpcccfc"},
        new Pass { Min = 11, Max = 12, Symbol = 't', Value = "wttmnqtbkttc"},
        new Pass { Min = 3, Max = 5, Symbol = 'p', Value = "ptpvp"},
        new Pass { Min = 1, Max = 11, Symbol = 'l', Value = "lglwgtlqlnxl"},
        new Pass { Min = 4, Max = 8, Symbol = 'm', Value = "mprmmmmwmmfmm"},
        new Pass { Min = 9, Max = 10, Symbol = 'd', Value = "ddddddddxdd"},
        new Pass { Min = 16, Max = 20, Symbol = 'r', Value = "rrrrrrrrrrrrrrrlrrrt"},
        new Pass { Min = 1, Max = 4, Symbol = 'g', Value = "gggg"},
        new Pass { Min = 2, Max = 12, Symbol = 'b', Value = "bczgbbbfbwbprbbbtb"},
        new Pass { Min = 2, Max = 7, Symbol = 'n', Value = "nnnmnxkntwwxnr"},
        new Pass { Min = 14, Max = 18, Symbol = 'z', Value = "tzzzqzzzlnpqzpzzkz"},
        new Pass { Min = 5, Max = 7, Symbol = 'p', Value = "ppppmkp"},
        new Pass { Min = 9, Max = 14, Symbol = 'c', Value = "vvcgvrxlccxvlpfml"},
        new Pass { Min = 2, Max = 3, Symbol = 'l', Value = "jlzpf"},
        new Pass { Min = 3, Max = 5, Symbol = 'p', Value = "pbpbp"},
        new Pass { Min = 9, Max = 13, Symbol = 'j', Value = "jjjjjjjjjjjjj"},
        new Pass { Min = 5, Max = 7, Symbol = 'k', Value = "fmckjkkklkxpf"},
        new Pass { Min = 5, Max = 6, Symbol = 'd', Value = "ddddrd"},
        new Pass { Min = 9, Max = 10, Symbol = 's', Value = "sssnsgssbs"},
        new Pass { Min = 9, Max = 10, Symbol = 'p', Value = "ppwvppbpptpp"},
        new Pass { Min = 1, Max = 8, Symbol = 'z', Value = "kmfszzrx"},
        new Pass { Min = 9, Max = 10, Symbol = 'v', Value = "vvjjvsklvdkrkvs"},
        new Pass { Min = 2, Max = 17, Symbol = 'k', Value = "kkctmcfzhtvskxlkq"},
        new Pass { Min = 10, Max = 12, Symbol = 'n', Value = "vjnndvnlgnhmfc"},
        new Pass { Min = 5, Max = 6, Symbol = 'n', Value = "hnnnnntn"},
        new Pass { Min = 1, Max = 6, Symbol = 'f', Value = "fptffkhhkktfbtst"},
        new Pass { Min = 4, Max = 6, Symbol = 'k', Value = "kqnkjhhwqhpzb"},
        new Pass { Min = 6, Max = 12, Symbol = 'r', Value = "rrrrrrrrrrrv"},
        new Pass { Min = 8, Max = 13, Symbol = 'l', Value = "llllllllwlllllll"},
        new Pass { Min = 4, Max = 6, Symbol = 'p', Value = "qxprzs"},
        new Pass { Min = 2, Max = 10, Symbol = 'w', Value = "wswpdwwwrcth"},
        new Pass { Min = 4, Max = 6, Symbol = 'n', Value = "gnnfnnnnnnn"},
        new Pass { Min = 10, Max = 14, Symbol = 's', Value = "ssssssprbfssssw"},
        new Pass { Min = 3, Max = 4, Symbol = 'f', Value = "ftfk"},
        new Pass { Min = 6, Max = 16, Symbol = 'x', Value = "cqxxqwrdxxxxsxbxxxxt"},
        new Pass { Min = 4, Max = 8, Symbol = 'f', Value = "ffsqvfpm"},
        new Pass { Min = 8, Max = 11, Symbol = 't', Value = "ttztttttttnttt"},
        new Pass { Min = 13, Max = 15, Symbol = 'q', Value = "qqnqqqqqqqqqqqq"},
        new Pass { Min = 2, Max = 3, Symbol = 'w', Value = "wwww"},
        new Pass { Min = 2, Max = 8, Symbol = 'n', Value = "ntnnnnnrnn"},
        new Pass { Min = 2, Max = 3, Symbol = 'k', Value = "jkzkk"},
        new Pass { Min = 3, Max = 4, Symbol = 's', Value = "sscscp"},
        new Pass { Min = 14, Max = 19, Symbol = 'g', Value = "gzggggggggggfgfgggqg"},
        new Pass { Min = 5, Max = 6, Symbol = 'n', Value = "nnnnwlnn"},
        new Pass { Min = 11, Max = 12, Symbol = 'b', Value = "bbmbbbbbbbxbbn"},
        new Pass { Min = 5, Max = 6, Symbol = 't', Value = "zntzfk"},
        new Pass { Min = 4, Max = 5, Symbol = 'j', Value = "ljphjl"},
        new Pass { Min = 3, Max = 12, Symbol = 'd', Value = "zndtlvdvvdzzn"},
        new Pass { Min = 7, Max = 8, Symbol = 'h', Value = "hhhhhhhwhh"},
        new Pass { Min = 12, Max = 13, Symbol = 's', Value = "sssssshssxssss"},
        new Pass { Min = 4, Max = 5, Symbol = 'h', Value = "nhsxxmh"},
        new Pass { Min = 7, Max = 9, Symbol = 'f', Value = "fzfkffffsfxn"},
        new Pass { Min = 1, Max = 8, Symbol = 'c', Value = "cccfcpccmhcch"},
        new Pass { Min = 1, Max = 2, Symbol = 'd', Value = "kfdwwm"},
        new Pass { Min = 13, Max = 14, Symbol = 'l', Value = "llllllllllllcll"},
        new Pass { Min = 2, Max = 5, Symbol = 'p', Value = "jpxdpkg"},
        new Pass { Min = 2, Max = 4, Symbol = 'h', Value = "hvhbmhhhhhnh"},
        new Pass { Min = 5, Max = 9, Symbol = 'g', Value = "ngqgtqtggdgg"},
        new Pass { Min = 15, Max = 17, Symbol = 'b', Value = "brhlrjflddssrrjxb"},
        new Pass { Min = 10, Max = 15, Symbol = 'v', Value = "vkfvvqtcxvvvtvcbvv"},
        new Pass { Min = 1, Max = 3, Symbol = 'g', Value = "pvkqsgzggg"},
        new Pass { Min = 7, Max = 8, Symbol = 'j', Value = "jjjjjjbjj"},
        new Pass { Min = 3, Max = 4, Symbol = 'w', Value = "jwrw"},
        new Pass { Min = 4, Max = 7, Symbol = 'c', Value = "mhcmkcjrpncxmcrccbc"},
        new Pass { Min = 9, Max = 12, Symbol = 'q', Value = "qqqqqqqqqqqs"},
        new Pass { Min = 13, Max = 16, Symbol = 'n', Value = "nwngndnnnnnnnnnnnn"},
        new Pass { Min = 3, Max = 4, Symbol = 'b', Value = "fjbbb"},
        new Pass { Min = 8, Max = 9, Symbol = 'd', Value = "jdfdsqnmdwfdnddkd"},
        new Pass { Min = 1, Max = 4, Symbol = 'f', Value = "ggfwgbfhvs"},
        new Pass { Min = 4, Max = 5, Symbol = 'g', Value = "gggvg"},
        new Pass { Min = 8, Max = 12, Symbol = 'x', Value = "gxhxxxxkxzmfxxx"},
        new Pass { Min = 1, Max = 5, Symbol = 'q', Value = "dqqhq"},
        new Pass { Min = 3, Max = 9, Symbol = 'm', Value = "mmdmmmzmmp"},
        new Pass { Min = 1, Max = 2, Symbol = 'l', Value = "llll"},
        new Pass { Min = 6, Max = 8, Symbol = 'q', Value = "qjwhqqhpkbzppc"},
        new Pass { Min = 3, Max = 10, Symbol = 'm', Value = "mmcjgrtzmmdmmm"},
        new Pass { Min = 2, Max = 4, Symbol = 'q', Value = "cxvq"},
        new Pass { Min = 11, Max = 13, Symbol = 'v', Value = "fvvvvvvvvvvvv"},
        new Pass { Min = 7, Max = 13, Symbol = 'b', Value = "bbbgbnbkbkbrldbbtc"},
        new Pass { Min = 14, Max = 16, Symbol = 'm', Value = "wmmmmmzxrmmjmwmh"},
        new Pass { Min = 6, Max = 10, Symbol = 'b', Value = "bwvwbbvshbgtbsrlwbzt"},
        new Pass { Min = 6, Max = 8, Symbol = 'q', Value = "qdwhcgpqxw"},
        new Pass { Min = 16, Max = 17, Symbol = 'l', Value = "llllbjlrllllcbdhllpl"},
        new Pass { Min = 3, Max = 4, Symbol = 'm', Value = "mmmrv"},
        new Pass { Min = 7, Max = 8, Symbol = 'm', Value = "mhjnnchg"},
        new Pass { Min = 12, Max = 13, Symbol = 'p', Value = "ppppppppppppt"},
        new Pass { Min = 1, Max = 4, Symbol = 's', Value = "sssx"},
        new Pass { Min = 1, Max = 2, Symbol = 'd', Value = "xmpdq"},
        new Pass { Min = 10, Max = 11, Symbol = 'x', Value = "xxxxxxxxxbbx"},
        new Pass { Min = 2, Max = 4, Symbol = 's', Value = "lxds"},
        new Pass { Min = 1, Max = 4, Symbol = 'b', Value = "jbsxbbmbbj"},
        new Pass { Min = 6, Max = 8, Symbol = 'q', Value = "qqqqqqblqq"},
        new Pass { Min = 15, Max = 16, Symbol = 'q', Value = "qqqqqwzqqqqqnqqqqfq"},
        new Pass { Min = 5, Max = 7, Symbol = 's', Value = "fzvsssr"},
        new Pass { Min = 6, Max = 7, Symbol = 'l', Value = "lncbgqr"},
        new Pass { Min = 7, Max = 8, Symbol = 's', Value = "ssssssvs"},
        new Pass { Min = 3, Max = 5, Symbol = 'r', Value = "rbrjt"},
        new Pass { Min = 3, Max = 8, Symbol = 'j', Value = "ksjjtvnjbjppjjjl"},
        new Pass { Min = 6, Max = 10, Symbol = 's', Value = "sszlkrsssss"},
        new Pass { Min = 1, Max = 4, Symbol = 'z', Value = "znzfpz"},
        new Pass { Min = 7, Max = 11, Symbol = 'm', Value = "dfkcbxmxmnmmtvmtdn"},
        new Pass { Min = 6, Max = 9, Symbol = 'h', Value = "hlhhkhhhq"},
        new Pass { Min = 8, Max = 9, Symbol = 'p', Value = "ppppppppvp"},
        new Pass { Min = 6, Max = 9, Symbol = 'c', Value = "cccgccccmcch"},
        new Pass { Min = 5, Max = 8, Symbol = 'g', Value = "bgkggjgtvggn"},
        new Pass { Min = 3, Max = 4, Symbol = 'x', Value = "xxhk"},
        new Pass { Min = 10, Max = 12, Symbol = 'h', Value = "hhhhhhhhhlhhhhdnh"},
        new Pass { Min = 5, Max = 6, Symbol = 'j', Value = "zjjsjn"},
        new Pass { Min = 9, Max = 14, Symbol = 's', Value = "ksclwttsmpjtds"},
        new Pass { Min = 6, Max = 7, Symbol = 'l', Value = "gtdcblql"},
        new Pass { Min = 1, Max = 4, Symbol = 'd', Value = "dkndjkcd"},
        new Pass { Min = 1, Max = 6, Symbol = 'k', Value = "kkkkkckmc"},
        new Pass { Min = 10, Max = 12, Symbol = 'x', Value = "xxxxxxxxxrxl"},
        new Pass { Min = 2, Max = 5, Symbol = 'v', Value = "fxdjtv"},
        new Pass { Min = 3, Max = 5, Symbol = 'q', Value = "pjmkqdmqnzqppr"},
        new Pass { Min = 5, Max = 8, Symbol = 't', Value = "xtgtgtcht"},
        new Pass { Min = 6, Max = 11, Symbol = 'j', Value = "nftjzjmfljqjrc"},
        new Pass { Min = 6, Max = 9, Symbol = 'g', Value = "rskgggmgmwjggggvgb"},
        new Pass { Min = 11, Max = 12, Symbol = 'v', Value = "vkvdmvdvvvdv"},
        new Pass { Min = 15, Max = 16, Symbol = 'z', Value = "zzzzzzzzzzzzzzgxz"},
        new Pass { Min = 13, Max = 17, Symbol = 'v', Value = "vvvvvvvvvvvvvvvvnv"},
        new Pass { Min = 9, Max = 14, Symbol = 'j', Value = "clrfkrwhjtvzvqqj"},
        new Pass { Min = 1, Max = 12, Symbol = 'l', Value = "lljljznslllffhblz"},
        new Pass { Min = 4, Max = 7, Symbol = 'c', Value = "cccgcxclc"},
        new Pass { Min = 6, Max = 11, Symbol = 'z', Value = "tbxqrzzbwbr"},
        new Pass { Min = 18, Max = 19, Symbol = 'm', Value = "jmbmmqmshmczlphfgmf"},
        new Pass { Min = 1, Max = 5, Symbol = 's', Value = "ssvsq"},
        new Pass { Min = 4, Max = 5, Symbol = 'k', Value = "kkkkw"},
        new Pass { Min = 4, Max = 7, Symbol = 'f', Value = "fcqffxff"},
        new Pass { Min = 3, Max = 8, Symbol = 'f', Value = "fffzthzf"},
        new Pass { Min = 9, Max = 12, Symbol = 'v', Value = "vvvvvvvvvvvmvv"},
        new Pass { Min = 14, Max = 17, Symbol = 'f', Value = "ftflcfffjtjrvfkffmvf"},
        new Pass { Min = 4, Max = 7, Symbol = 'n', Value = "pnmnxnqqjp"},
        new Pass { Min = 6, Max = 7, Symbol = 'r', Value = "rrrkrmr"},
        new Pass { Min = 4, Max = 13, Symbol = 'k', Value = "drckdzxrsmzrkqckn"},
        new Pass { Min = 5, Max = 14, Symbol = 't', Value = "dttttttttttttt"},
        new Pass { Min = 13, Max = 14, Symbol = 'v', Value = "vvvvfvvvvvvvvvv"},
        new Pass { Min = 7, Max = 12, Symbol = 'j', Value = "jrljwnctjqjjxj"},
        new Pass { Min = 6, Max = 7, Symbol = 'v', Value = "wchfzvm"},
        new Pass { Min = 1, Max = 8, Symbol = 'd', Value = "dddddddzd"},
        new Pass { Min = 10, Max = 12, Symbol = 'g', Value = "gvvzrglgrgggggggggg"},
        new Pass { Min = 3, Max = 4, Symbol = 'n', Value = "ngtnnn"},
        new Pass { Min = 2, Max = 4, Symbol = 'b', Value = "fzbb"},
        new Pass { Min = 1, Max = 15, Symbol = 'x', Value = "cxxfxxxckxxhxlxxxxxx"},
        new Pass { Min = 7, Max = 19, Symbol = 'f', Value = "ffkzcglddffcfvfhffv"},
        new Pass { Min = 9, Max = 12, Symbol = 's', Value = "sssssssmssss"},
        new Pass { Min = 13, Max = 20, Symbol = 't', Value = "ttttmttttttthtttddtt"},
        new Pass { Min = 2, Max = 15, Symbol = 'v', Value = "vvqvcwvvvvsvvqvwm"},
        new Pass { Min = 5, Max = 10, Symbol = 'w', Value = "wxcstswwwwnc"},
        new Pass { Min = 3, Max = 4, Symbol = 'v', Value = "tjvvnvvtzfdcjjwb"},
        new Pass { Min = 1, Max = 2, Symbol = 'l', Value = "lbclr"},
        new Pass { Min = 2, Max = 13, Symbol = 'd', Value = "dkdlddcddddddd"},
        new Pass { Min = 2, Max = 7, Symbol = 'n', Value = "npnngnnn"},
        new Pass { Min = 4, Max = 12, Symbol = 'g', Value = "kmvvmfngwmlg"},
        new Pass { Min = 1, Max = 2, Symbol = 'w', Value = "wwwww"},
        new Pass { Min = 5, Max = 11, Symbol = 't', Value = "ttttjtttttttttttt"},
        new Pass { Min = 4, Max = 5, Symbol = 'r', Value = "srlrrr"},
        new Pass { Min = 5, Max = 8, Symbol = 'q', Value = "qhqfpjqsnqqkq"},
        new Pass { Min = 8, Max = 15, Symbol = 's', Value = "hvtnslpsfbsssrw"},
        new Pass { Min = 11, Max = 16, Symbol = 'n', Value = "gnwnfndrnnhnnknsnnc"},
        new Pass { Min = 2, Max = 7, Symbol = 'r', Value = "tdrrshrrhsxrr"},
        new Pass { Min = 16, Max = 18, Symbol = 'm', Value = "mmbmmmjmmmmmmmmmmbm"},
        new Pass { Min = 6, Max = 7, Symbol = 'n', Value = "nnnnnxt"},
        new Pass { Min = 4, Max = 6, Symbol = 'k', Value = "dpxzklksk"},
        new Pass { Min = 1, Max = 9, Symbol = 'g', Value = "ggkxhgggggggggggqg"},
        new Pass { Min = 1, Max = 8, Symbol = 'l', Value = "lllglllh"},
        new Pass { Min = 1, Max = 4, Symbol = 'c', Value = "cwtc"},
        new Pass { Min = 5, Max = 6, Symbol = 'h', Value = "vhhhvshh"},
        new Pass { Min = 10, Max = 11, Symbol = 'x', Value = "xxxxxxxxxxc"},
        new Pass { Min = 2, Max = 3, Symbol = 'q', Value = "qhqqgqmt"},
        new Pass { Min = 3, Max = 6, Symbol = 'k', Value = "hkqqshgjnxmlkrjdzg"},
        new Pass { Min = 9, Max = 11, Symbol = 'l', Value = "llprlllllllll"},
        new Pass { Min = 5, Max = 7, Symbol = 'l', Value = "lknflmrv"},
        new Pass { Min = 8, Max = 9, Symbol = 'h', Value = "hhhhhhhhh"},
        new Pass { Min = 7, Max = 8, Symbol = 'z', Value = "zzzzzgvzzzzz"},
        new Pass { Min = 18, Max = 20, Symbol = 'v', Value = "vvvvvvvhbvqvgvlvjbrv"},
        new Pass { Min = 13, Max = 15, Symbol = 'k', Value = "xkfcvkrnfkkkvcpt"},
        new Pass { Min = 3, Max = 5, Symbol = 'l', Value = "llnnglmgtz"},
        new Pass { Min = 15, Max = 19, Symbol = 't', Value = "tmtsfttxtctdtgtmpttt"},
        new Pass { Min = 6, Max = 8, Symbol = 'f', Value = "gmffwvffff"},
        new Pass { Min = 10, Max = 13, Symbol = 'd', Value = "dndsddddddpdjndddd"},
        new Pass { Min = 7, Max = 10, Symbol = 'r', Value = "rjzqrpgrrrcmrrg"},
        new Pass { Min = 1, Max = 4, Symbol = 'm', Value = "hlmm"},
        new Pass { Min = 9, Max = 15, Symbol = 'd', Value = "pdddlrwdzddddddd"},
        new Pass { Min = 6, Max = 13, Symbol = 'q', Value = "qqqhnvqqqqqqfbqq"},
        new Pass { Min = 1, Max = 11, Symbol = 'z', Value = "wzsqmnrzwzzhzxczzzzd"},
        new Pass { Min = 6, Max = 11, Symbol = 't', Value = "tptnjttkttttvtttr"},
        new Pass { Min = 3, Max = 5, Symbol = 'n', Value = "nnznnn"},
        new Pass { Min = 5, Max = 6, Symbol = 't', Value = "trtttslv"},
        new Pass { Min = 5, Max = 6, Symbol = 'g', Value = "gggggt"},
        new Pass { Min = 15, Max = 19, Symbol = 's', Value = "sssssssssssxsswsssss"},
        new Pass { Min = 1, Max = 13, Symbol = 'q', Value = "wzqjljdqqqqnqq"},
        new Pass { Min = 6, Max = 7, Symbol = 'k', Value = "kkkkkgkkk"},
        new Pass { Min = 4, Max = 5, Symbol = 'k', Value = "zkxvk"},
        new Pass { Min = 7, Max = 14, Symbol = 't', Value = "thsstltbvmsctqkfhdzc"},
        new Pass { Min = 2, Max = 5, Symbol = 'n', Value = "hnnnn"},
        new Pass { Min = 2, Max = 16, Symbol = 't', Value = "gsvkhmhktcxkfqbtd"},
        new Pass { Min = 8, Max = 9, Symbol = 'q', Value = "qqtzznrqg"},
        new Pass { Min = 17, Max = 18, Symbol = 'v', Value = "vvzvvvvvvvvvvvvvlk"},
        new Pass { Min = 3, Max = 4, Symbol = 'v', Value = "vvvl"},
        new Pass { Min = 3, Max = 4, Symbol = 'b', Value = "bbvb"},
        new Pass { Min = 10, Max = 12, Symbol = 'w', Value = "wwwcwwwwwwkzwhw"},
        new Pass { Min = 1, Max = 3, Symbol = 'd', Value = "ntps"},
        new Pass { Min = 8, Max = 9, Symbol = 'j', Value = "mqcjcjjfjjhjbjj"},
        new Pass { Min = 1, Max = 7, Symbol = 'j', Value = "mjjjjjjj"},
        new Pass { Min = 13, Max = 14, Symbol = 'f', Value = "bzffglvfcfsfjb"},
        new Pass { Min = 2, Max = 3, Symbol = 'k', Value = "kqkq"},
        new Pass { Min = 7, Max = 15, Symbol = 'c', Value = "fccpccshcccccccc"},
        new Pass { Min = 12, Max = 13, Symbol = 'k', Value = "kkkkkkpkktksqk"},
        new Pass { Min = 12, Max = 13, Symbol = 'w', Value = "rwwwwwkwwwwswwwhw"},
        new Pass { Min = 5, Max = 12, Symbol = 'k', Value = "nlkthkkklkkktchmhb"},
        new Pass { Min = 15, Max = 16, Symbol = 'f', Value = "fffffffdffffffbf"},
        new Pass { Min = 3, Max = 4, Symbol = 'k', Value = "kqkprkkp"},
        new Pass { Min = 4, Max = 5, Symbol = 'p', Value = "dcpdppzpppjqm"},
        new Pass { Min = 4, Max = 7, Symbol = 'b', Value = "qbbkgbgz"},
        new Pass { Min = 10, Max = 11, Symbol = 'n', Value = "nnnnnnnnnnw"},
        new Pass { Min = 9, Max = 12, Symbol = 'h', Value = "hhhchbhhvhrhhh"},
        new Pass { Min = 3, Max = 5, Symbol = 'h', Value = "hrhnbcl"},
        new Pass { Min = 6, Max = 10, Symbol = 'v', Value = "nvlvhvrpvvvvvvv"},
        new Pass { Min = 3, Max = 6, Symbol = 'd', Value = "dddddjd"},
        new Pass { Min = 4, Max = 5, Symbol = 'r', Value = "rrcvr"},
        new Pass { Min = 7, Max = 12, Symbol = 'l', Value = "llllllllllllltll"},
        new Pass { Min = 3, Max = 6, Symbol = 'b', Value = "zbbbbt"},
        new Pass { Min = 6, Max = 10, Symbol = 'z', Value = "zznzzzzzbzbhzz"},
        new Pass { Min = 2, Max = 5, Symbol = 'h', Value = "rfwbmkhmhhhmjhmh"},
        new Pass { Min = 11, Max = 13, Symbol = 'q', Value = "wkkzzqxvqqsqx"},
        new Pass { Min = 2, Max = 15, Symbol = 'p', Value = "hbpjpppppptppppzb"},
        new Pass { Min = 9, Max = 10, Symbol = 'b', Value = "bbmbbbbbsb"},
        new Pass { Min = 3, Max = 10, Symbol = 't', Value = "cqmtttjtttttf"},
        new Pass { Min = 8, Max = 11, Symbol = 'v', Value = "tvgcvvvvvkv"},
        new Pass { Min = 6, Max = 9, Symbol = 'g', Value = "tggnggtggkg"},
        new Pass { Min = 3, Max = 6, Symbol = 'w', Value = "dfwnht"},
        new Pass { Min = 8, Max = 14, Symbol = 'c', Value = "pncwqccsfgctpccxc"},
        new Pass { Min = 6, Max = 9, Symbol = 'p', Value = "bpppjtzprggp"},
        new Pass { Min = 15, Max = 18, Symbol = 'j', Value = "sjjjjjjdjmjbjjpvjj"},
        new Pass { Min = 1, Max = 6, Symbol = 'm', Value = "mhmkrhxn"},
        new Pass { Min = 10, Max = 11, Symbol = 'd', Value = "xcjtpdwdcfvhqdksfhd"},
        new Pass { Min = 16, Max = 17, Symbol = 't', Value = "txtlrttctwtztttnx"},
        new Pass { Min = 13, Max = 14, Symbol = 'j', Value = "jjtjjmjjnjjjjjjj"},
        new Pass { Min = 10, Max = 12, Symbol = 'm', Value = "ldqmmmgmmxrmfwrbv"},
        new Pass { Min = 4, Max = 6, Symbol = 'p', Value = "psmpnpkfq"},
        new Pass { Min = 13, Max = 14, Symbol = 't', Value = "tltttsttmtttjttt"},
        new Pass { Min = 7, Max = 9, Symbol = 'g', Value = "ggggggbgv"},
        new Pass { Min = 8, Max = 9, Symbol = 'q', Value = "qqqqqqqqd"},
        new Pass { Min = 4, Max = 5, Symbol = 'd', Value = "ddddl"},
        new Pass { Min = 14, Max = 16, Symbol = 'g', Value = "gggggggwggpgfpgm"},
        new Pass { Min = 4, Max = 5, Symbol = 'v', Value = "vvvvl"},
        new Pass { Min = 5, Max = 8, Symbol = 'v', Value = "gtjpvvdv"},
        new Pass { Min = 5, Max = 11, Symbol = 's', Value = "dsslsvqpwsss"},
        new Pass { Min = 4, Max = 6, Symbol = 'h', Value = "hhhghh"},
        new Pass { Min = 16, Max = 17, Symbol = 'k', Value = "hkkkkkkkkkkkkkkqj"},
        new Pass { Min = 5, Max = 10, Symbol = 'd', Value = "dddtddddjd"},
        new Pass { Min = 6, Max = 7, Symbol = 'v', Value = "vclfvvzvj"},
        new Pass { Min = 6, Max = 8, Symbol = 'm', Value = "dtkbcblppzx"},
        new Pass { Min = 1, Max = 4, Symbol = 'g', Value = "hggggg"},
        new Pass { Min = 9, Max = 11, Symbol = 'q', Value = "qdqvdqkdfqvqzqkq"},
        new Pass { Min = 2, Max = 6, Symbol = 's', Value = "ssgsbswhs"},
        new Pass { Min = 3, Max = 8, Symbol = 'j', Value = "jjpjjjjv"},
        new Pass { Min = 3, Max = 8, Symbol = 'd', Value = "dddddddqdddd"},
        new Pass { Min = 6, Max = 8, Symbol = 'v', Value = "vvvvhcvn"},
        new Pass { Min = 6, Max = 12, Symbol = 'z', Value = "gzzzzzzzzzzkzzzzz"},
        new Pass { Min = 5, Max = 12, Symbol = 'k', Value = "nrkzklbxcwbc"},
        new Pass { Min = 10, Max = 14, Symbol = 'p', Value = "clxjpnhsvttnjp"},
        new Pass { Min = 6, Max = 17, Symbol = 'w', Value = "vztxwwwgwlwcwwwtw"},
        new Pass { Min = 8, Max = 11, Symbol = 'c', Value = "cctzcccqcjc"},
        new Pass { Min = 1, Max = 3, Symbol = 'b', Value = "zdqx"},
        new Pass { Min = 3, Max = 5, Symbol = 'x', Value = "dvxxxx"},
        new Pass { Min = 6, Max = 13, Symbol = 'b', Value = "gvbbbbbbbbvpkbb"},
        new Pass { Min = 7, Max = 12, Symbol = 'k', Value = "hkbkkqkvkmpkrhk"},
        new Pass { Min = 3, Max = 6, Symbol = 'c', Value = "ccrbcdccc"},
        new Pass { Min = 4, Max = 6, Symbol = 'm', Value = "znhphh"},
        new Pass { Min = 4, Max = 11, Symbol = 'x', Value = "xmmgbxxgdxxtbwg"},
        new Pass { Min = 15, Max = 16, Symbol = 'm', Value = "nmmbmmbjmrbvmmbm"},
        new Pass { Min = 11, Max = 12, Symbol = 'j', Value = "jdcjjtsjjdjj"},
        new Pass { Min = 1, Max = 4, Symbol = 'c', Value = "cccfcc"},
        new Pass { Min = 6, Max = 15, Symbol = 'n', Value = "ssvnnnnnnwnggzmp"},
        new Pass { Min = 4, Max = 6, Symbol = 'l', Value = "qwfllpx"},
        new Pass { Min = 6, Max = 9, Symbol = 'b', Value = "bbbbbsbbmb"},
        new Pass { Min = 3, Max = 6, Symbol = 'j', Value = "ljjgfh"},
        new Pass { Min = 5, Max = 9, Symbol = 't', Value = "tttttphtwtvtf"},
        new Pass { Min = 8, Max = 12, Symbol = 'x', Value = "xtdxxxdjghxxpxhkbxx"},
        new Pass { Min = 5, Max = 9, Symbol = 'r', Value = "rrprrmrrrjvszrrtp"},
        new Pass { Min = 15, Max = 16, Symbol = 'r', Value = "lrrrrrrrrrrrkrrrr"},
        new Pass { Min = 2, Max = 5, Symbol = 'q', Value = "ltfgqcqmt"},
        new Pass { Min = 7, Max = 13, Symbol = 'k', Value = "zkkkkkkkkkkkhkkkkk"},
        new Pass { Min = 5, Max = 6, Symbol = 'z', Value = "zzzzzszz"},
        new Pass { Min = 2, Max = 7, Symbol = 'g', Value = "tnjqnsgkdtc"},
        new Pass { Min = 3, Max = 4, Symbol = 'j', Value = "njjjgkxcgckj"},
        new Pass { Min = 4, Max = 7, Symbol = 'j', Value = "rxmjlxzhjjjsgjcj"},
        new Pass { Min = 7, Max = 10, Symbol = 'f', Value = "rmfbffhffcf"},
        new Pass { Min = 11, Max = 12, Symbol = 'h', Value = "hdhhhhhhhhhsh"},
        new Pass { Min = 7, Max = 8, Symbol = 'v', Value = "nwrvvvvdv"},
        new Pass { Min = 8, Max = 9, Symbol = 'l', Value = "llllllllf"},
        new Pass { Min = 4, Max = 5, Symbol = 'r', Value = "rmxrrrrx"},
        new Pass { Min = 2, Max = 3, Symbol = 'c', Value = "ccgdcc"},
        new Pass { Min = 13, Max = 15, Symbol = 'r', Value = "rrwrrrnrrrrrdrslr"},
        new Pass { Min = 4, Max = 16, Symbol = 'x', Value = "cnlxmtpxdzxblfxxjd"},
        new Pass { Min = 4, Max = 5, Symbol = 'm', Value = "mmmmtm"},
        new Pass { Min = 9, Max = 13, Symbol = 'x', Value = "gxxxxxxlxxqxxxxx"},
        new Pass { Min = 1, Max = 3, Symbol = 'd', Value = "ddhd"},
        new Pass { Min = 11, Max = 14, Symbol = 'f', Value = "tffffffffqlfff"},
        new Pass { Min = 2, Max = 4, Symbol = 'r', Value = "xrrf"},
        new Pass { Min = 1, Max = 11, Symbol = 'm', Value = "mtdmsmmmmdmmmmmsmtmr"},
        new Pass { Min = 1, Max = 8, Symbol = 'g', Value = "pggtggggdgmgggn"},
        new Pass { Min = 7, Max = 8, Symbol = 'f', Value = "ffvfffpff"},
        new Pass { Min = 2, Max = 7, Symbol = 'k', Value = "khqgfzk"},
        new Pass { Min = 11, Max = 12, Symbol = 's', Value = "ssssssssssbsss"},
        new Pass { Min = 7, Max = 14, Symbol = 'h', Value = "hthpwhhxhglzqtmhh"},
        new Pass { Min = 2, Max = 4, Symbol = 'z', Value = "zzpmz"},
        new Pass { Min = 16, Max = 18, Symbol = 'x', Value = "xxxqxxmlgbxxxxxxxx"},
        new Pass { Min = 9, Max = 11, Symbol = 'v', Value = "dblhzhvvvnfvptvmf"},
        new Pass { Min = 4, Max = 11, Symbol = 'n', Value = "nxsddnsnnngsdnghngk"},
        new Pass { Min = 8, Max = 11, Symbol = 'x', Value = "xxxxxxxwxxxxxxxxx"},
        new Pass { Min = 1, Max = 4, Symbol = 's', Value = "swst"},
        new Pass { Min = 13, Max = 14, Symbol = 'm', Value = "mgmmghmmmmmmrmmfmmmg"},
        new Pass { Min = 4, Max = 5, Symbol = 'c', Value = "dcccc"},
        new Pass { Min = 4, Max = 5, Symbol = 'r', Value = "jzrrc"},
        new Pass { Min = 13, Max = 19, Symbol = 'b', Value = "bbbbbbbbbbbcbcbbbbb"},
        new Pass { Min = 11, Max = 14, Symbol = 'c', Value = "ccccncfclccccfcccm"},
        new Pass { Min = 3, Max = 4, Symbol = 't', Value = "tstl"},
        new Pass { Min = 1, Max = 20, Symbol = 'v', Value = "vzrzgsvsfgxjqkxgdpwv"},
        new Pass { Min = 14, Max = 15, Symbol = 'h', Value = "hhvkbhhhhhhhhmhhsh"},
        new Pass { Min = 9, Max = 13, Symbol = 'b', Value = "bbbbbbbbtbbbbbb"},
        new Pass { Min = 2, Max = 3, Symbol = 'b', Value = "zbbb"},
        new Pass { Min = 17, Max = 18, Symbol = 's', Value = "smsssssrsssssssssfss"},
        new Pass { Min = 5, Max = 10, Symbol = 'v', Value = "vfvvvfvdvjvlltv"},
        new Pass { Min = 9, Max = 10, Symbol = 'n', Value = "nnnqnnnnxtn"},
        new Pass { Min = 6, Max = 7, Symbol = 'w', Value = "pwtwwwfkwvk"},
        new Pass { Min = 11, Max = 14, Symbol = 'z', Value = "wzzzzzjzzzlzzkz"},
        new Pass { Min = 5, Max = 6, Symbol = 'l', Value = "lxlllv"},
        new Pass { Min = 5, Max = 8, Symbol = 'v', Value = "vvvvvvthhv"},
        new Pass { Min = 1, Max = 9, Symbol = 'r', Value = "rrrrjkzrdqmr"},
        new Pass { Min = 6, Max = 8, Symbol = 's', Value = "sssssssg"},
        new Pass { Min = 2, Max = 4, Symbol = 'f', Value = "frfff"},
        new Pass { Min = 1, Max = 16, Symbol = 'r', Value = "pzbdrgnpndnrrwkczmr"},
        new Pass { Min = 8, Max = 9, Symbol = 'b', Value = "sbbbbbbblkwb"},
        new Pass { Min = 2, Max = 5, Symbol = 'z', Value = "zzjzz"},
        new Pass { Min = 3, Max = 6, Symbol = 'q', Value = "qqwqqr"},
        new Pass { Min = 2, Max = 13, Symbol = 'v', Value = "vbvvbvvjvvnvcdnvc"},
        new Pass { Min = 12, Max = 15, Symbol = 'p', Value = "pppppppppppppppp"},
        new Pass { Min = 2, Max = 7, Symbol = 'm', Value = "mmmmmmd"},
        new Pass { Min = 6, Max = 11, Symbol = 'f', Value = "ffffffffffz"},
        new Pass { Min = 5, Max = 6, Symbol = 'r', Value = "drrthrzrrrp"},
        new Pass { Min = 2, Max = 7, Symbol = 'q', Value = "fntqnbqqzb"},
        new Pass { Min = 5, Max = 14, Symbol = 'w', Value = "wlfwstdfzvwvqw"},
        new Pass { Min = 4, Max = 7, Symbol = 's', Value = "mgsssslfjzsssv"},
        new Pass { Min = 7, Max = 8, Symbol = 'g', Value = "tgtgjrggggsggtg"},
        new Pass { Min = 11, Max = 19, Symbol = 'z', Value = "fkzzzvzzvzdzzzzzfzz"},
        new Pass { Min = 3, Max = 7, Symbol = 'w', Value = "kwcwwww"},
        new Pass { Min = 6, Max = 14, Symbol = 's', Value = "sssssssssssswjss"},
        new Pass { Min = 7, Max = 8, Symbol = 'v', Value = "vvmbxvxv"},
        new Pass { Min = 2, Max = 6, Symbol = 'n', Value = "nnnnnp"},
        new Pass { Min = 7, Max = 8, Symbol = 'b', Value = "bbbbbbbb"},
        new Pass { Min = 3, Max = 6, Symbol = 'z', Value = "zzzzhz"},
        new Pass { Min = 11, Max = 17, Symbol = 't', Value = "bltttdttttttttttzt"},
        new Pass { Min = 1, Max = 9, Symbol = 'l', Value = "llllllvll"},
        new Pass { Min = 10, Max = 11, Symbol = 'n', Value = "tznsxfhdpnn"},
        new Pass { Min = 6, Max = 8, Symbol = 't', Value = "tttttnttt"},
        new Pass { Min = 4, Max = 10, Symbol = 'p', Value = "pppppppbppppppnc"},
        new Pass { Min = 4, Max = 11, Symbol = 'j', Value = "rhvjjjjjjwjnrcp"},
        new Pass { Min = 3, Max = 4, Symbol = 'j', Value = "cjjj"},
        new Pass { Min = 7, Max = 12, Symbol = 'v', Value = "kmctjvksqzvv"},
        new Pass { Min = 16, Max = 17, Symbol = 'w', Value = "wwwwwwwwcwwwwwwwwww"},
        new Pass { Min = 12, Max = 16, Symbol = 'f', Value = "fffffjbfffwffwffff"},
        new Pass { Min = 9, Max = 10, Symbol = 'p', Value = "ppntppppjppkpdp"},
        new Pass { Min = 3, Max = 4, Symbol = 'l', Value = "lllcf"},
        new Pass { Min = 5, Max = 6, Symbol = 'b', Value = "dbbbbsbtb"},
        new Pass { Min = 2, Max = 3, Symbol = 'p', Value = "pvpz"},
        new Pass { Min = 5, Max = 6, Symbol = 'f', Value = "pqffdf"},
        new Pass { Min = 1, Max = 3, Symbol = 'l', Value = "lnlpxl"},
        new Pass { Min = 8, Max = 10, Symbol = 'n', Value = "nnnjttnxmmns"},
        new Pass { Min = 1, Max = 10, Symbol = 'j', Value = "xjjwtjtjjjjjjj"},
        new Pass { Min = 2, Max = 8, Symbol = 'm', Value = "smwmcmzrfqbmmwdmm"},
        new Pass { Min = 1, Max = 6, Symbol = 'k', Value = "jxpsfkkkgm"},
        new Pass { Min = 5, Max = 9, Symbol = 'f', Value = "zjfffjjwknqh"},
        new Pass { Min = 1, Max = 6, Symbol = 'c', Value = "rcccczcccccc"},
        new Pass { Min = 13, Max = 17, Symbol = 'g', Value = "zsgpfppggwshgbtggxzh"},
        new Pass { Min = 12, Max = 14, Symbol = 'n', Value = "qmknbfcgnnnhwn"},
        new Pass { Min = 1, Max = 6, Symbol = 'k', Value = "vdklkkzkkkkfkm"},
        new Pass { Min = 1, Max = 3, Symbol = 'h', Value = "hhlhhhl"},
        new Pass { Min = 16, Max = 18, Symbol = 'p', Value = "qggnxmswcppklptgsp"},
        new Pass { Min = 1, Max = 4, Symbol = 'm', Value = "vmmqmmmmmmm"},
        new Pass { Min = 8, Max = 10, Symbol = 'l', Value = "lllllxlllvllg"},
        new Pass { Min = 4, Max = 12, Symbol = 'g', Value = "gjgghggwctzvgggggg"},
        new Pass { Min = 8, Max = 11, Symbol = 'x', Value = "jxhxxxxxxxx"},
        new Pass { Min = 4, Max = 16, Symbol = 'n', Value = "xnrnbkrkdvntnjkc"},
        new Pass { Min = 2, Max = 4, Symbol = 'm', Value = "mdmmj"},
        new Pass { Min = 6, Max = 7, Symbol = 'n', Value = "nnnnnngnnnntn"},
        new Pass { Min = 1, Max = 13, Symbol = 'j', Value = "jjjgjjjfgjjmj"},
        new Pass { Min = 8, Max = 10, Symbol = 'z', Value = "zzzzzzpjtz"},
        new Pass { Min = 1, Max = 18, Symbol = 'f', Value = "ffkwvfgcrnffgnffmf"},
        new Pass { Min = 4, Max = 5, Symbol = 'j', Value = "jjtjvb"},
        new Pass { Min = 6, Max = 11, Symbol = 's', Value = "ssscsnslsssssssshsss"},
        new Pass { Min = 11, Max = 12, Symbol = 'n', Value = "nnnnnnnnnnmd"},
        new Pass { Min = 2, Max = 10, Symbol = 'n', Value = "cpnhnrnbknnkwnbnlb"},
        new Pass { Min = 2, Max = 4, Symbol = 'd', Value = "dddnh"},
        new Pass { Min = 9, Max = 12, Symbol = 'f', Value = "fffffffffffldfff"},
        new Pass { Min = 1, Max = 9, Symbol = 'd', Value = "ddddddvdlddddd"},
        new Pass { Min = 1, Max = 8, Symbol = 'w', Value = "wnwwwdwww"},
        new Pass { Min = 3, Max = 4, Symbol = 'h', Value = "bhgv"},
        new Pass { Min = 1, Max = 4, Symbol = 'x', Value = "vxxj"},
        new Pass { Min = 3, Max = 4, Symbol = 'g', Value = "gmgbg"},
        new Pass { Min = 7, Max = 8, Symbol = 'j', Value = "nzwgbtnj"},
        new Pass { Min = 3, Max = 6, Symbol = 'z', Value = "zzpzzhzw"},
        new Pass { Min = 8, Max = 10, Symbol = 'h', Value = "hmhhhhszgz"},
        new Pass { Min = 1, Max = 5, Symbol = 'm', Value = "dnqgnxjm"},
        new Pass { Min = 11, Max = 12, Symbol = 'z', Value = "zkzpbjxszzzhwgdz"},
        new Pass { Min = 10, Max = 11, Symbol = 'r', Value = "rlrrrrrrrrr"},
        new Pass { Min = 1, Max = 2, Symbol = 'v', Value = "vvvvtsvvvvvvvvqvvvn"},
        new Pass { Min = 13, Max = 14, Symbol = 'n', Value = "nrfzqlxxxsxqhnkhrmws"},
        new Pass { Min = 1, Max = 4, Symbol = 'z', Value = "znftzjjwzc"},
        new Pass { Min = 6, Max = 15, Symbol = 'v', Value = "fvvvlvvhvvvvvzhvv"},
        new Pass { Min = 5, Max = 10, Symbol = 'x', Value = "mtxprgbqxxkfnssvq"},
        new Pass { Min = 8, Max = 9, Symbol = 'f', Value = "lffffffwf"},
        new Pass { Min = 1, Max = 4, Symbol = 'g', Value = "grxgvlhflrbghj"},
        new Pass { Min = 3, Max = 5, Symbol = 'c', Value = "fcxcl"},
        new Pass { Min = 6, Max = 7, Symbol = 's', Value = "ssssdds"},
        new Pass { Min = 10, Max = 13, Symbol = 'l', Value = "llllllllllllxl"},
        new Pass { Min = 12, Max = 15, Symbol = 'j', Value = "jjvjjbjcjjjjsjjj"},
        new Pass { Min = 1, Max = 2, Symbol = 'c', Value = "ctggc"},
        new Pass { Min = 2, Max = 4, Symbol = 'w', Value = "wbwwwwr"},
        new Pass { Min = 8, Max = 20, Symbol = 'v', Value = "phvvvvvrbvvfvvvvvvhv"},
        new Pass { Min = 5, Max = 8, Symbol = 'v', Value = "cvvnvjbl"},
        new Pass { Min = 4, Max = 19, Symbol = 'x', Value = "xhvxflxpkxxcfvwxxhl"},
        new Pass { Min = 1, Max = 2, Symbol = 'm', Value = "mgqj" },
        new Pass { Min = 5, Max = 6, Symbol = 'q', Value = "wpxdbq" },
        new Pass { Min = 19, Max = 20, Symbol = 'd', Value = "ddddddbxddddddddddpd" },
        new Pass { Min = 5, Max = 11, Symbol = 'd', Value = "dhhwddjddkdd" },
        new Pass { Min = 6, Max = 7, Symbol = 'g', Value = "ggggggn" },
        new Pass { Min = 1, Max = 7, Symbol = 'h', Value = "zhphhhhhgn" },
        new Pass { Min = 7, Max = 11, Symbol = 's', Value = "ssssssssssksssss" },
        new Pass { Min = 2, Max = 3, Symbol = 'n', Value = "hnwn" },
        new Pass { Min = 8, Max = 9, Symbol = 'h', Value = "hhsshhhhh" },
        new Pass { Min = 1, Max = 2, Symbol = 'c', Value = "ccwcc" },
        new Pass { Min = 2, Max = 5, Symbol = 's', Value = "cdsmmfqfcrsh" },
        new Pass { Min = 3, Max = 5, Symbol = 'm', Value = "mwmjt" },
        new Pass { Min = 1, Max = 4, Symbol = 'n', Value = "ndntnnnnnnnnnn" },
        new Pass { Min = 4, Max = 6, Symbol = 's', Value = "ssslsssshsssmq" },
        new Pass { Min = 5, Max = 16, Symbol = 'r', Value = "rrrrcrrrjrrrrrrrrr" },
        new Pass { Min = 1, Max = 6, Symbol = 'v', Value = "bvvvvvvv" },
        new Pass { Min = 9, Max = 10, Symbol = 't', Value = "tsttttztxtttttb" },
        new Pass { Min = 8, Max = 12, Symbol = 'd', Value = "tvrbvwxdddxmhfsd" },
        new Pass { Min = 3, Max = 9, Symbol = 'w', Value = "wbwwwwwwww" },
        new Pass { Min = 3, Max = 5, Symbol = 'g', Value = "bgglcqg" },
        new Pass { Min = 8, Max = 12, Symbol = 'f', Value = "fqffvdzslhksrv" },
        new Pass { Min = 1, Max = 4, Symbol = 'h', Value = "hsqh" },
        new Pass { Min = 6, Max = 12, Symbol = 'b', Value = "hbwhxbfppkbb" },
        new Pass { Min = 12, Max = 15, Symbol = 'l', Value = "llllllllllllllplv" },
        new Pass { Min = 16, Max = 17, Symbol = 'm', Value = "mmmmmzmvmmmmmmkmhmmm" },
        new Pass { Min = 2, Max = 8, Symbol = 'p', Value = "mpnnnpwpv" },
        new Pass { Min = 9, Max = 10, Symbol = 'x', Value = "xxpxxxxlcxj" },
        new Pass { Min = 10, Max = 14, Symbol = 'c', Value = "mccclvcccfcckwcbczc" },
        new Pass { Min = 2, Max = 3, Symbol = 'v', Value = "vvsrg" },
        new Pass { Min = 13, Max = 15, Symbol = 'h', Value = "hhhhrlhfhhhhvhhhshh" },
        new Pass { Min = 3, Max = 8, Symbol = 'z', Value = "vsbkqlzzzzzsmzw" },
        new Pass { Min = 9, Max = 11, Symbol = 'h', Value = "qhhhhhhhddnh" },
        new Pass { Min = 4, Max = 5, Symbol = 'h', Value = "hhhkxhh" },
        new Pass { Min = 7, Max = 12, Symbol = 't', Value = "dtcvttttbhnntft" },
        new Pass { Min = 1, Max = 5, Symbol = 'z', Value = "kksnxzzxz" },
        new Pass { Min = 1, Max = 3, Symbol = 'j', Value = "cjjjjjjjfjj" },
        new Pass { Min = 12, Max = 15, Symbol = 's', Value = "sslssstssssssszss" },
        new Pass { Min = 2, Max = 4, Symbol = 'c', Value = "mntc" },
        new Pass { Min = 5, Max = 8, Symbol = 'v', Value = "mvbsvfvvvlsrv" },
        new Pass { Min = 5, Max = 6, Symbol = 'z', Value = "zmhfjq" },
        new Pass { Min = 10, Max = 15, Symbol = 'r', Value = "rrrrrrrjrbrmrjr" },
        new Pass { Min = 9, Max = 11, Symbol = 'j', Value = "jjjjjjjjjjxjjj" },
        new Pass { Min = 1, Max = 2, Symbol = 'd', Value = "jwhdd" },
        new Pass { Min = 4, Max = 5, Symbol = 'm', Value = "mmmkm" },
        new Pass { Min = 1, Max = 7, Symbol = 'j', Value = "rprmjbxjj" },
        new Pass { Min = 13, Max = 14, Symbol = 'g', Value = "ggggggpqggggqgg" },
        new Pass { Min = 1, Max = 5, Symbol = 'l', Value = "llxzlkpptdzg" },
        new Pass { Min = 1, Max = 2, Symbol = 'z', Value = "zzzzzzzzzzzzjzzz" },
        new Pass { Min = 3, Max = 4, Symbol = 'h', Value = "qhhwtz" },
        new Pass { Min = 2, Max = 5, Symbol = 't', Value = "tptttt" },
        new Pass { Min = 1, Max = 14, Symbol = 'c', Value = "cccccccccccccxcccc" },
        new Pass { Min = 8, Max = 9, Symbol = 't', Value = "tgtpttwtqttvt" },
        new Pass { Min = 1, Max = 16, Symbol = 'm', Value = "mhmtpmmpmmtmzmmcqj" },
        new Pass { Min = 3, Max = 4, Symbol = 'q', Value = "qqvq" },
        new Pass { Min = 10, Max = 11, Symbol = 'h', Value = "hxhhhhhhhbhh" },
        new Pass { Min = 5, Max = 6, Symbol = 'n', Value = "xlchhnljrlnfrlwzs" },
        new Pass { Min = 1, Max = 9, Symbol = 'x', Value = "mxxxxxxxtxxxfxx" },
        new Pass { Min = 2, Max = 7, Symbol = 'n', Value = "bbnnrqmnnnnnl" },
        new Pass { Min = 2, Max = 7, Symbol = 'p', Value = "rgpqnqp" },
        new Pass { Min = 3, Max = 4, Symbol = 'f', Value = "fndf" },
        new Pass { Min = 10, Max = 11, Symbol = 'c', Value = "cccccccccqc" },
        new Pass { Min = 3, Max = 10, Symbol = 'l', Value = "lpzxlhpslfh" },
        new Pass { Min = 3, Max = 5, Symbol = 'k', Value = "kkkkkkk" },
        new Pass { Min = 14, Max = 17, Symbol = 'b', Value = "bbbbbbbtbbbbbfbbbb" },
        new Pass { Min = 1, Max = 2, Symbol = 'f', Value = "gfff" },
        new Pass { Min = 10, Max = 14, Symbol = 'j', Value = "jjjjjjhjjjdjrjc" },
        new Pass { Min = 1, Max = 9, Symbol = 's', Value = "wszsswssspsss" },
        new Pass { Min = 4, Max = 6, Symbol = 'k', Value = "dckkkkkk" },
        new Pass { Min = 3, Max = 13, Symbol = 'h', Value = "hhvkvhhhhhhdhh" },
        new Pass { Min = 15, Max = 16, Symbol = 'g', Value = "ggggggggggggggngg" },
        new Pass { Min = 2, Max = 11, Symbol = 'm', Value = "nzdsmbqtmmmmxskcmmv" },
        new Pass { Min = 3, Max = 11, Symbol = 'm', Value = "mmmkmhxmwmcmqdlpmf" },
        new Pass { Min = 1, Max = 8, Symbol = 'n', Value = "snnnbnwn" },
        new Pass { Min = 1, Max = 13, Symbol = 'j', Value = "pjjjjjgjjjjjxjj" },
        new Pass { Min = 3, Max = 18, Symbol = 'm', Value = "mmvvmqmlmmmmzcmkwqlw" },
        new Pass { Min = 1, Max = 4, Symbol = 'd', Value = "dbdx" },
        new Pass { Min = 12, Max = 15, Symbol = 'r', Value = "rrrrrrmrrrrrrrr" },
        new Pass { Min = 4, Max = 18, Symbol = 's', Value = "sssvsssssszsssssscss" },
        new Pass { Min = 2, Max = 5, Symbol = 'q', Value = "nqbmmbqds" },
        new Pass { Min = 3, Max = 12, Symbol = 'd', Value = "hrdvzzcrbjwdkgddbrpq" },
        new Pass { Min = 2, Max = 3, Symbol = 'r', Value = "rsrghkrmdsfm" },
        new Pass { Min = 5, Max = 9, Symbol = 'k', Value = "twfwkkkswqkkkkwv" },
        new Pass { Min = 4, Max = 6, Symbol = 'p', Value = "tppxpstmxcw" },
        new Pass { Min = 12, Max = 13, Symbol = 'k', Value = "kkkktkkkkrkksk" },
        new Pass { Min = 1, Max = 2, Symbol = 'm', Value = "lmmm" },
        new Pass { Min = 3, Max = 5, Symbol = 's', Value = "shsss" },
        new Pass { Min = 6, Max = 7, Symbol = 'c', Value = "ccccclc" },
        new Pass { Min = 10, Max = 17, Symbol = 's', Value = "ssssshsssssssssshs" },
        new Pass { Min = 6, Max = 15, Symbol = 'n', Value = "nnnxnrtfnnnnnnnnn" },
        new Pass { Min = 3, Max = 18, Symbol = 's', Value = "jsfcdsscssmnsgssnj" },
        new Pass { Min = 7, Max = 8, Symbol = 'x', Value = "xxcxxxxr" },
        new Pass { Min = 3, Max = 5, Symbol = 'l', Value = "lvlllll" },
        new Pass { Min = 11, Max = 12, Symbol = 'h', Value = "hmhhhhhhhcxjhhfdh" },
        new Pass { Min = 3, Max = 4, Symbol = 'd', Value = "wdfdd" },
        new Pass { Min = 3, Max = 4, Symbol = 'r', Value = "qrvr" },
        new Pass { Min = 10, Max = 18, Symbol = 'j', Value = "mvwlxblnhjddlzkhqjfj" },
        new Pass { Min = 6, Max = 20, Symbol = 'b', Value = "bhbbbbbbbbbtbbkbbbbc" },
        new Pass { Min = 8, Max = 9, Symbol = 'c', Value = "cclccmnrr" },
        new Pass { Min = 3, Max = 6, Symbol = 'w', Value = "wwwwwww" },
        new Pass { Min = 5, Max = 9, Symbol = 'k', Value = "dlgkjnqxk" },
        new Pass { Min = 12, Max = 18, Symbol = 'f', Value = "fqfffbfffffcfffhfkf" },
        new Pass { Min = 1, Max = 3, Symbol = 'w', Value = "fwwgjsclwpw" },
        new Pass { Min = 6, Max = 7, Symbol = 'z', Value = "zwzzzzl" },
        new Pass { Min = 14, Max = 16, Symbol = 'r', Value = "jrrrrrrrrrrrrfrrrr" },
        new Pass { Min = 11, Max = 14, Symbol = 'b', Value = "bbbbbbbbbbbbbw" },
        new Pass { Min = 9, Max = 11, Symbol = 'h', Value = "hhhzhhhfxhhhh" },
        new Pass { Min = 3, Max = 4, Symbol = 'p', Value = "pplnp" },
        new Pass { Min = 2, Max = 3, Symbol = 'f', Value = "ffff" },
        new Pass { Min = 5, Max = 8, Symbol = 'p', Value = "lppppppsppppppp" },
        new Pass { Min = 17, Max = 18, Symbol = 'w', Value = "wwwwwwwwwwwwwwwwzcww" },
        new Pass { Min = 11, Max = 13, Symbol = 'n', Value = "nnnnnnnqnnnnfn" },
        new Pass { Min = 7, Max = 12, Symbol = 'f', Value = "fxmfpdfjrffjgtffzlfg" },
        new Pass { Min = 4, Max = 16, Symbol = 'w', Value = "bctwmwtxvwqzrwwwwhw" },
        new Pass { Min = 2, Max = 7, Symbol = 'm', Value = "gmmmmmjmmmm" },
        new Pass { Min = 1, Max = 15, Symbol = 'q', Value = "tqqqqqqqqqqqqqqq" },
        new Pass { Min = 3, Max = 4, Symbol = 'q', Value = "gqwq" },
        new Pass { Min = 3, Max = 12, Symbol = 's', Value = "ssssssssssrhpsg" },
        new Pass { Min = 6, Max = 8, Symbol = 'm', Value = "mrmlmhcrsm" },
        new Pass { Min = 4, Max = 9, Symbol = 'q', Value = "gdbffcqbqt" },
        new Pass { Min = 1, Max = 17, Symbol = 'k', Value = "kkkkkkkkkkkkkkkkkmk" },
        new Pass { Min = 15, Max = 16, Symbol = 'h', Value = "hghhhhhhhhhhhhrhh" },
        new Pass { Min = 4, Max = 5, Symbol = 'p', Value = "pkpzmb" },
        new Pass { Min = 2, Max = 18, Symbol = 'h', Value = "khvkdpbxdptllfdxvhh" },
        new Pass { Min = 18, Max = 20, Symbol = 'z', Value = "zzczzzzzzzzzzzzzzpzs" },
        new Pass { Min = 1, Max = 11, Symbol = 'p', Value = "ppppppcpzppppppppp" },
        new Pass { Min = 4, Max = 9, Symbol = 'z', Value = "ztpfrjzwnv" },
        new Pass { Min = 6, Max = 11, Symbol = 'x', Value = "snxxtstcqhv" },
        new Pass { Min = 3, Max = 5, Symbol = 'c', Value = "nrlcccbcpsvcc" },
        new Pass { Min = 2, Max = 7, Symbol = 'z', Value = "dztxzzqmfzrpz" },
        new Pass { Min = 5, Max = 14, Symbol = 'w', Value = "pbcjnqpwwlccfscz" },
        new Pass { Min = 1, Max = 5, Symbol = 'f', Value = "rfndsxdmhbgf" },
        new Pass { Min = 8, Max = 14, Symbol = 't', Value = "ttttpdfwtxfttd" },
        new Pass { Min = 2, Max = 11, Symbol = 'l', Value = "lndmmrnxdmdpdmlzll" },
        new Pass { Min = 3, Max = 4, Symbol = 'h', Value = "chzl" },
        new Pass { Min = 10, Max = 17, Symbol = 'd', Value = "ngkkdbvflmcssmgmdk" },
        new Pass { Min = 4, Max = 7, Symbol = 'd', Value = "bhksdtd" },
        new Pass { Min = 2, Max = 6, Symbol = 'k', Value = "ktkdkzwsgkhkk" },
        new Pass { Min = 1, Max = 4, Symbol = 'r', Value = "hrrs" },
        new Pass { Min = 15, Max = 19, Symbol = 'j', Value = "ndnvjfjljnwklsmdbjj" },
        new Pass { Min = 5, Max = 12, Symbol = 'v', Value = "vhvvvrvgvvqgwvvbfv" },
        new Pass { Min = 2, Max = 3, Symbol = 'r', Value = "rfkkhrrhqhks" },
        new Pass { Min = 13, Max = 17, Symbol = 'q', Value = "qqmlqqqqqmqqvqqqcqq" },
        new Pass { Min = 4, Max = 15, Symbol = 'z', Value = "zvbkvbzczkrttcz" },
        new Pass { Min = 4, Max = 8, Symbol = 's', Value = "ssssssss" },
        new Pass { Min = 13, Max = 14, Symbol = 'x', Value = "xmxxrxxxgxxxmb" },
        new Pass { Min = 7, Max = 10, Symbol = 's', Value = "sfjzslwsqsss" },
        new Pass { Min = 4, Max = 13, Symbol = 'c', Value = "clccncccccccpc" },
        new Pass { Min = 2, Max = 4, Symbol = 'l', Value = "lddlpplrqqs" },
        new Pass { Min = 12, Max = 13, Symbol = 'j', Value = "jjjvjjhjjjjmjjjjj" },
        new Pass { Min = 6, Max = 9, Symbol = 'n', Value = "lnnznnpnclnnn" },
        new Pass { Min = 6, Max = 10, Symbol = 'g', Value = "gggggggwgjgg" },
        new Pass { Min = 4, Max = 6, Symbol = 'l', Value = "tjhqmr" },
        new Pass { Min = 2, Max = 4, Symbol = 'd', Value = "hddxjdvj" },
        new Pass { Min = 5, Max = 13, Symbol = 't', Value = "tzftwttwttjttt" },
        new Pass { Min = 1, Max = 9, Symbol = 'j', Value = "jnjjjkjftjjfmjhjkj" },
        new Pass { Min = 8, Max = 9, Symbol = 'q', Value = "qqqsqqqjj" },
        new Pass { Min = 15, Max = 19, Symbol = 'l', Value = "lllllbtdlsllllllxlfl" },
        new Pass { Min = 5, Max = 6, Symbol = 'g', Value = "gkgkrsgg" },
        new Pass { Min = 2, Max = 4, Symbol = 't', Value = "tttb" },
        new Pass { Min = 12, Max = 15, Symbol = 'p', Value = "jpppppspgpppppkxb" },
        new Pass { Min = 10, Max = 13, Symbol = 'n', Value = "nznprnnhnmgxhxnknnnn" },
        new Pass { Min = 12, Max = 13, Symbol = 'd', Value = "dddsdddddddsd" },
        new Pass { Min = 5, Max = 15, Symbol = 'q', Value = "qqqqkqqqmqfzqqqw" },
        new Pass { Min = 5, Max = 9, Symbol = 's', Value = "nmgslvgdz" },
        new Pass { Min = 1, Max = 4, Symbol = 'd', Value = "gddkddd" },
        new Pass { Min = 12, Max = 16, Symbol = 'v', Value = "zvdsdsgjrtjvzsjtx" },
        new Pass { Min = 11, Max = 14, Symbol = 'q', Value = "pqdgjqqqqgqqjwlqqqmq" },
        new Pass { Min = 2, Max = 7, Symbol = 'p', Value = "pkpqsppqgz" },
        new Pass { Min = 6, Max = 10, Symbol = 'b', Value = "bzdbbbbbbvbbbx" },
        new Pass { Min = 14, Max = 15, Symbol = 'v', Value = "vvvvqvvvcvvvvvvv" },
        new Pass { Min = 4, Max = 5, Symbol = 'w', Value = "wjwwwhjwg" },
        new Pass { Min = 5, Max = 10, Symbol = 'x', Value = "wgthfxtdpxx" },
        new Pass { Min = 6, Max = 7, Symbol = 'c', Value = "ccqcfcbcccbml" },
        new Pass { Min = 6, Max = 7, Symbol = 'w', Value = "rwwwwxb" },
        new Pass { Min = 4, Max = 5, Symbol = 'n', Value = "jnnnngvljjmnr" },
        new Pass { Min = 3, Max = 11, Symbol = 'm', Value = "lbmmmmmmmmtxgxmmzm" },
        new Pass { Min = 1, Max = 2, Symbol = 'b', Value = "bbbvjcbbb" },
        new Pass { Min = 6, Max = 9, Symbol = 'b', Value = "tbwbbcbbbb" },
        new Pass { Min = 11, Max = 13, Symbol = 'd', Value = "sdkwqrjdddbdd" },
        new Pass { Min = 9, Max = 15, Symbol = 't', Value = "ttttpqttjttttsjt" },
        new Pass { Min = 5, Max = 7, Symbol = 'j', Value = "jjjjjjzj" },
        new Pass { Min = 12, Max = 13, Symbol = 'v', Value = "vvjvmvvqvfzvcvvvvvv" },
        new Pass { Min = 6, Max = 7, Symbol = 'd', Value = "ddlddrd" },
        new Pass { Min = 5, Max = 6, Symbol = 'j', Value = "jjjjwj" },
        new Pass { Min = 5, Max = 6, Symbol = 'f', Value = "fffffp" },
        new Pass { Min = 6, Max = 7, Symbol = 'w', Value = "zwmwdwww" },
        new Pass { Min = 1, Max = 4, Symbol = 'd', Value = "jddddppdktdgh" },
        new Pass { Min = 4, Max = 14, Symbol = 'n', Value = "nnnnncnnnnnnnnrn" },
        new Pass { Min = 14, Max = 17, Symbol = 'c', Value = "ccccccsdccccccccn" },
        new Pass { Min = 3, Max = 4, Symbol = 'z', Value = "zzzgqz" },
        new Pass { Min = 5, Max = 17, Symbol = 'm', Value = "mmrsmmnzqlnbmmlljwpm" },
        new Pass { Min = 3, Max = 5, Symbol = 'j', Value = "cgvjh" },
        new Pass { Min = 12, Max = 13, Symbol = 'w', Value = "wtgblrdchjjkfhg" },
        new Pass { Min = 4, Max = 7, Symbol = 't', Value = "rgclgtt" },
        new Pass { Min = 1, Max = 3, Symbol = 'k', Value = "wckhkkkjkk" },
        new Pass { Min = 6, Max = 11, Symbol = 'n', Value = "nnnnnnnnnnvn" },
        new Pass { Min = 17, Max = 18, Symbol = 'k', Value = "kktkkkknczkkkkhkkk" },
        new Pass { Min = 1, Max = 6, Symbol = 'x', Value = "rwxqgxrxxxmsmkrx" },
        new Pass { Min = 17, Max = 18, Symbol = 'g', Value = "ggggggggggggggqgjp" },
        new Pass { Min = 14, Max = 17, Symbol = 'w', Value = "wwwwwwwwwwwwwnwww" },
        new Pass { Min = 11, Max = 12, Symbol = 'w', Value = "vcbmkbwnwbwww" },
        new Pass { Min = 15, Max = 16, Symbol = 'g', Value = "gggggggggghjgwgggjvg" },
        new Pass { Min = 5, Max = 9, Symbol = 'n', Value = "nnnnwnnnfnnnnnnsnnnn" },
        new Pass { Min = 3, Max = 4, Symbol = 'k', Value = "kkkjhk" },
        new Pass { Min = 5, Max = 8, Symbol = 'k', Value = "kkkkmkkkk" },
        new Pass { Min = 9, Max = 13, Symbol = 'k', Value = "kkrskkkkkkkqfkknmz" },
        new Pass { Min = 2, Max = 3, Symbol = 'j', Value = "jtjcj" },
        new Pass { Min = 7, Max = 8, Symbol = 'c', Value = "ccvcrcsxc" },
        new Pass { Min = 5, Max = 9, Symbol = 'k', Value = "kkkkgkkkkk" },
        new Pass { Min = 4, Max = 5, Symbol = 'h', Value = "hhzsxv" },
        new Pass { Min = 1, Max = 7, Symbol = 'd', Value = "lgdbdhdddd" },
        new Pass { Min = 5, Max = 6, Symbol = 'j', Value = "dsjjkj" },
        new Pass { Min = 7, Max = 20, Symbol = 'x', Value = "xnxwmwkbbbkjbpfwkpgx" },
        new Pass { Min = 11, Max = 12, Symbol = 'q', Value = "wmbqtffthfcqgq" },
        new Pass { Min = 7, Max = 16, Symbol = 'h', Value = "hhfkhhdhhhhhhhhhhhh" },
        new Pass { Min = 9, Max = 13, Symbol = 'b', Value = "bhbfbmbbsgbbfbj" },
        new Pass { Min = 8, Max = 10, Symbol = 'w', Value = "xwwmwwwgfwwzpwnw" },
        new Pass { Min = 7, Max = 11, Symbol = 'm', Value = "bmrmbwmmmmmmmm" },
        new Pass { Min = 8, Max = 9, Symbol = 'd', Value = "lshdfglpdq" },
        new Pass { Min = 11, Max = 13, Symbol = 'w', Value = "vxwwwwxckwwkww" },
        new Pass { Min = 8, Max = 13, Symbol = 'x', Value = "xxzxgtpxxlxxx" },
        new Pass { Min = 8, Max = 13, Symbol = 'z', Value = "jrsfgvzzzwrdxz" },
        new Pass { Min = 10, Max = 11, Symbol = 'q', Value = "qqqqqlqqqqq" },
        new Pass { Min = 2, Max = 7, Symbol = 'm', Value = "knxnmxm" },
        new Pass { Min = 2, Max = 4, Symbol = 'n', Value = "znnhnnnnnnn" },
        new Pass { Min = 4, Max = 6, Symbol = 'k', Value = "kmxgkkk" },
        new Pass { Min = 10, Max = 18, Symbol = 'z', Value = "qhhzhzbldchlmwdzfrsz" },
        new Pass { Min = 3, Max = 4, Symbol = 'n', Value = "nnnt" },
        new Pass { Min = 11, Max = 15, Symbol = 'v', Value = "vvvvvvvvvvwvwvf" },
        new Pass { Min = 4, Max = 9, Symbol = 'x', Value = "dxjxnmghvrxbnzgxljc" },
        new Pass { Min = 1, Max = 2, Symbol = 'm', Value = "mmgm" },
        new Pass { Min = 18, Max = 19, Symbol = 'z', Value = "zzzzczzzzczzzzzzzjsz" },
        new Pass { Min = 6, Max = 20, Symbol = 'p', Value = "pkhzdzpppfbphphpxppp" },
        new Pass { Min = 3, Max = 9, Symbol = 'h', Value = "zxhqqkkqknkfvq" },
        new Pass { Min = 5, Max = 8, Symbol = 'l', Value = "lllltlll" },
        new Pass { Min = 8, Max = 10, Symbol = 'z', Value = "zdzzzzmszz" },
        new Pass { Min = 10, Max = 17, Symbol = 'l', Value = "txhgwzsrjlvlvglxl" },
        new Pass { Min = 1, Max = 12, Symbol = 's', Value = "bvgswssssmssvssssssb" },
        new Pass { Min = 3, Max = 6, Symbol = 'j', Value = "xjjbjt" },
        new Pass { Min = 3, Max = 5, Symbol = 'x', Value = "xxlxq" },
        new Pass { Min = 5, Max = 15, Symbol = 'r', Value = "htprxzjstgzpddrtjrr" },
        new Pass { Min = 1, Max = 10, Symbol = 'x', Value = "xzftsqxxpgzdlcth" },
        new Pass { Min = 6, Max = 9, Symbol = 'w', Value = "wbdwwpbwwwwcrx" },
        new Pass { Min = 4, Max = 11, Symbol = 'n', Value = "nnknnhnnnnk" },
        new Pass { Min = 8, Max = 11, Symbol = 'f', Value = "ffffffpsfffff" },
        new Pass { Min = 6, Max = 9, Symbol = 'h', Value = "hhhnhhqhhhnhvv" },
        new Pass { Min = 6, Max = 9, Symbol = 'x', Value = "gqxzhlpnxlcrwnxxp" },
        new Pass { Min = 5, Max = 7, Symbol = 'k', Value = "kkkkjkkk" },
        new Pass { Min = 5, Max = 7, Symbol = 'x', Value = "xxdxxsqcx" },
        new Pass { Min = 6, Max = 7, Symbol = 'j', Value = "jfjljjfp" },
        new Pass { Min = 7, Max = 8, Symbol = 'l', Value = "clsldvlc" },
        new Pass { Min = 5, Max = 10, Symbol = 'h', Value = "qhqmchbzhlfhc" },
        new Pass { Min = 5, Max = 9, Symbol = 'm', Value = "mpdnhsmmb" },
        new Pass { Min = 2, Max = 4, Symbol = 'k', Value = "jvmkjrkhkctwlrq" },
        new Pass { Min = 2, Max = 3, Symbol = 's', Value = "ssgstssds" },
        new Pass { Min = 8, Max = 9, Symbol = 't', Value = "tvttttttht" },
        new Pass { Min = 5, Max = 6, Symbol = 'n', Value = "nnnpnpn" },
        new Pass { Min = 8, Max = 9, Symbol = 'x', Value = "xxxxqxxxsp" },
        new Pass { Min = 6, Max = 7, Symbol = 'z', Value = "zzzzzzl" },
        new Pass { Min = 4, Max = 5, Symbol = 'f', Value = "fffpkffq" },
        new Pass { Min = 1, Max = 12, Symbol = 'b', Value = "bsfbclbxbkbbmbmb" },
        new Pass { Min = 14, Max = 15, Symbol = 'b', Value = "rcnwnhbdfbhtblvb" },
        new Pass { Min = 7, Max = 9, Symbol = 'j', Value = "jjjjjjjjx" },
        new Pass { Min = 2, Max = 3, Symbol = 'x', Value = "xxxx" },
        new Pass { Min = 13, Max = 14, Symbol = 'z', Value = "zqzzzzzdztzzzmzz" },
        new Pass { Min = 2, Max = 6, Symbol = 'r', Value = "rmlbjrrbrc" },
        new Pass { Min = 2, Max = 3, Symbol = 'm', Value = "mwmm" },
        new Pass { Min = 9, Max = 10, Symbol = 'd', Value = "ddddddjddz" },
        new Pass { Min = 15, Max = 18, Symbol = 'p', Value = "pppppppzppppppzppj" },
        new Pass { Min = 3, Max = 6, Symbol = 'g', Value = "glfgdgfgbgdkg" },
        new Pass { Min = 1, Max = 3, Symbol = 's', Value = "sdsblxzscp" },
        new Pass { Min = 5, Max = 6, Symbol = 'v', Value = "vvvvsv" },
        new Pass { Min = 1, Max = 3, Symbol = 'd', Value = "vdxdkd" },
        new Pass { Min = 6, Max = 8, Symbol = 'w', Value = "wkzwcwvwwwqwd" },
        new Pass { Min = 9, Max = 10, Symbol = 'h', Value = "hhhhhhhhwh" },
        new Pass { Min = 9, Max = 12, Symbol = 'b', Value = "bdbbbbbwbbmbbbb" },
        new Pass { Min = 2, Max = 8, Symbol = 'b', Value = "bbbbbbbcb" },
        new Pass { Min = 2, Max = 9, Symbol = 'v', Value = "nvtgsfvpv" },
        new Pass { Min = 11, Max = 13, Symbol = 'v', Value = "hvvgvvvvvvbvphlhnv" },
        new Pass { Min = 6, Max = 7, Symbol = 'r', Value = "rrrrprr" },
        new Pass { Min = 10, Max = 16, Symbol = 'w', Value = "wlxptrzwmwxhspcww" },
        new Pass { Min = 5, Max = 7, Symbol = 'f', Value = "ffpfshf" },
        new Pass { Min = 3, Max = 6, Symbol = 't', Value = "rnttvx" },
        new Pass { Min = 8, Max = 16, Symbol = 'b', Value = "pvlbtnfbvspdhtkk" },
        new Pass { Min = 1, Max = 4, Symbol = 'v', Value = "vlvd" },
        new Pass { Min = 4, Max = 17, Symbol = 'l', Value = "qflfllkllplllllkl" },
        new Pass { Min = 1, Max = 3, Symbol = 's', Value = "psswjplkhvxssftnpl" },
        new Pass { Min = 6, Max = 11, Symbol = 't', Value = "tthmbtwkfct" },
        new Pass { Min = 11, Max = 17, Symbol = 'w', Value = "wwwwjwdtwcnwwwxkx" },
        new Pass { Min = 9, Max = 11, Symbol = 's', Value = "sssssssslsss" },
        new Pass { Min = 8, Max = 10, Symbol = 'n', Value = "nnnnnpnwnnnvw" },
        new Pass { Min = 12, Max = 13, Symbol = 'm', Value = "mmmmmmmmmmmnpmm" },
        new Pass { Min = 14, Max = 17, Symbol = 'w', Value = "xbswvmsflkmqlpkxwm" },
        new Pass { Min = 1, Max = 3, Symbol = 'w', Value = "mzww" },
        new Pass { Min = 5, Max = 6, Symbol = 'g', Value = "ggggdw" },
        new Pass { Min = 1, Max = 15, Symbol = 'r', Value = "rslcrjzhrjdpwqm" },
        new Pass { Min = 7, Max = 12, Symbol = 'g', Value = "ggdgfggdzlxfkg" },
        new Pass { Min = 2, Max = 11, Symbol = 'x', Value = "cpsxxkxxqhsxdxxjkgbt" },
        new Pass { Min = 7, Max = 8, Symbol = 'w', Value = "wdvhwwwp" },
        new Pass { Min = 1, Max = 4, Symbol = 'z', Value = "zmfzllxnrnlw" },
        new Pass { Min = 9, Max = 10, Symbol = 'b', Value = "rkbbbbksbpdsbcm" },
        new Pass { Min = 1, Max = 8, Symbol = 'h', Value = "sqdmcjpw" },
        new Pass { Min = 2, Max = 6, Symbol = 'x', Value = "pxxvrx" },
        new Pass { Min = 5, Max = 6, Symbol = 'x', Value = "xjshxxqt" },
        new Pass { Min = 1, Max = 13, Symbol = 'b', Value = "fbbbbbbbbbbbbbb" },
        new Pass { Min = 11, Max = 13, Symbol = 't', Value = "bwhtttdvtbtkw" },
        new Pass { Min = 2, Max = 6, Symbol = 'j', Value = "rjrggj" },
        new Pass { Min = 5, Max = 6, Symbol = 'v', Value = "fvvvwvtv" },
        new Pass { Min = 10, Max = 15, Symbol = 's', Value = "ssdsstswssssssc" },
        new Pass { Min = 2, Max = 6, Symbol = 'h', Value = "hnqzhlclp" },
        new Pass { Min = 8, Max = 12, Symbol = 't', Value = "pjztttrjtvttt" },
        new Pass { Min = 5, Max = 6, Symbol = 'g', Value = "gwxrggtmg" },
        new Pass { Min = 1, Max = 8, Symbol = 'z', Value = "kzzzzzzvz" },
        new Pass { Min = 10, Max = 15, Symbol = 'p', Value = "pppppppppvpppppp" },
        new Pass { Min = 3, Max = 4, Symbol = 'g', Value = "ngxdgg" },
        new Pass { Min = 2, Max = 5, Symbol = 'x', Value = "xcxxnbwh" },
        new Pass { Min = 3, Max = 10, Symbol = 's', Value = "sgkghshxdssws" },
        new Pass { Min = 1, Max = 2, Symbol = 's', Value = "pssldmf" },
        new Pass { Min = 2, Max = 5, Symbol = 'm', Value = "jmxmm" },
        new Pass { Min = 5, Max = 6, Symbol = 'n', Value = "pnsjqnnn" },
        new Pass { Min = 13, Max = 17, Symbol = 't', Value = "ttxslvttlnttrdwtt" },
        new Pass { Min = 1, Max = 6, Symbol = 'n', Value = "nnpnsn" },
        new Pass { Min = 3, Max = 20, Symbol = 'm', Value = "mmmmmwjmmmmmtmmvmmmm" },
        new Pass { Min = 15, Max = 17, Symbol = 's', Value = "ssszsslsssszssssss" },
        new Pass { Min = 5, Max = 8, Symbol = 's', Value = "hsgzspsk" },
        new Pass { Min = 7, Max = 8, Symbol = 'c', Value = "ccccccchc" },
        new Pass { Min = 14, Max = 17, Symbol = 'l', Value = "llllllllllllllllk" },
        new Pass { Min = 7, Max = 14, Symbol = 'p', Value = "xjbxdpkbgcpbfpptfx" },
        new Pass { Min = 5, Max = 6, Symbol = 's', Value = "sghmss" },
        new Pass { Min = 4, Max = 6, Symbol = 's', Value = "ssssss" },
        new Pass { Min = 1, Max = 2, Symbol = 'c', Value = "kcwpwc" },
        new Pass { Min = 5, Max = 6, Symbol = 'm', Value = "mmmqtmt" },
        new Pass { Min = 1, Max = 9, Symbol = 'l', Value = "glllllllslllll" },
        new Pass { Min = 3, Max = 4, Symbol = 'r', Value = "rrcr" },
        new Pass { Min = 6, Max = 9, Symbol = 'r', Value = "rpcbrrrrdvrrwf" },
        new Pass { Min = 3, Max = 7, Symbol = 'l', Value = "wglsfjtwlldg" },
        new Pass { Min = 6, Max = 9, Symbol = 'g', Value = "gggbgggxw" },
        new Pass { Min = 9, Max = 10, Symbol = 'j', Value = "jjjjjjjjrjjjjjjjjjj" },
        new Pass { Min = 4, Max = 14, Symbol = 'p', Value = "vbppfpncsmhctp" },
        new Pass { Min = 10, Max = 13, Symbol = 'k', Value = "kkkkkkkkkkkkkkkkk" },
        new Pass { Min = 3, Max = 5, Symbol = 'p', Value = "dnlpp" },
        new Pass { Min = 11, Max = 15, Symbol = 'f', Value = "fsffzftkfqflnflf" },
        new Pass { Min = 9, Max = 11, Symbol = 'q', Value = "bqdqcqqqqgffqfqmrqlq" },
        new Pass { Min = 1, Max = 10, Symbol = 'l', Value = "lszxlhdkgtprglxxl" },
        new Pass { Min = 16, Max = 18, Symbol = 'l', Value = "sllllllmlllllllllwl" },
        new Pass { Min = 4, Max = 7, Symbol = 'b', Value = "brblbbbtbj" },
        new Pass { Min = 3, Max = 6, Symbol = 'n', Value = "rhnntq" },
        new Pass { Min = 7, Max = 9, Symbol = 'k', Value = "kjnkjpbkkkkvkjm" },
        new Pass { Min = 11, Max = 12, Symbol = 'g', Value = "kvjpqmhcgbrl" },
        new Pass { Min = 3, Max = 12, Symbol = 'h', Value = "khhhvhhmchhgfh" },
        new Pass { Min = 3, Max = 4, Symbol = 'r', Value = "xmpr" },
        new Pass { Min = 3, Max = 7, Symbol = 'm', Value = "mmlmmmmhm" },
        new Pass { Min = 7, Max = 16, Symbol = 'm', Value = "mmmlmmlmmmmmmmmmmm" },
        new Pass { Min = 3, Max = 4, Symbol = 'b', Value = "sdbbbr" },
        new Pass { Min = 14, Max = 19, Symbol = 'k', Value = "hkkkkkjclkgmzvgkkkk" },
        new Pass { Min = 12, Max = 14, Symbol = 'w', Value = "ssqgwwcxcqwwww" },
        new Pass { Min = 2, Max = 3, Symbol = 'k', Value = "lkkr" },
        new Pass { Min = 1, Max = 7, Symbol = 't', Value = "wtttttlt" },
        new Pass { Min = 4, Max = 8, Symbol = 'd', Value = "wdjnqgdf" },
        new Pass { Min = 8, Max = 9, Symbol = 'j', Value = "jjsjwjjlj" },
        new Pass { Min = 4, Max = 7, Symbol = 'h', Value = "hnhphxhhhq" },
        new Pass { Min = 2, Max = 5, Symbol = 'd', Value = "qdjgqdb" },
        new Pass { Min = 3, Max = 5, Symbol = 'w', Value = "wpwzwdm" },
        new Pass { Min = 3, Max = 12, Symbol = 'n', Value = "pnnngxnjqjhpcntfrvz" },
        new Pass { Min = 10, Max = 15, Symbol = 'h', Value = "hhhhhvhhhhhhhhg" },
        new Pass { Min = 4, Max = 6, Symbol = 's', Value = "dwrsksjhtsrjdvmbsbwr" },
        new Pass { Min = 8, Max = 11, Symbol = 'v', Value = "vvvvvvvcvvvvvv" },
        new Pass { Min = 4, Max = 5, Symbol = 'm', Value = "lnmlmmwsmfsm" },
        new Pass { Min = 7, Max = 16, Symbol = 'c', Value = "kvzcrcbcvkcpptdccq" },
        new Pass { Min = 2, Max = 3, Symbol = 'b', Value = "bnbbpjp" },
        new Pass { Min = 3, Max = 5, Symbol = 'm', Value = "hpjkrmmlwq" },
        new Pass { Min = 3, Max = 7, Symbol = 'v', Value = "vvvnlhn" },
        new Pass { Min = 3, Max = 4, Symbol = 'b', Value = "bnbbb" },
        new Pass { Min = 3, Max = 6, Symbol = 'd', Value = "tkdktrctmjw" },
        new Pass { Min = 3, Max = 5, Symbol = 'f', Value = "pffffj" },
        new Pass { Min = 6, Max = 10, Symbol = 't', Value = "ltrgjvjthtpttphrttk" },
        new Pass { Min = 3, Max = 8, Symbol = 's', Value = "ssrkstfgssxxxc" },
        new Pass { Min = 1, Max = 2, Symbol = 'd', Value = "sdhkcfdcdg" },
        new Pass { Min = 6, Max = 12, Symbol = 'h', Value = "shhhhhzzzhfh" },
        new Pass { Min = 4, Max = 7, Symbol = 'j', Value = "jjkzgrj" },
        new Pass { Min = 13, Max = 15, Symbol = 'l', Value = "llltlwlllllqzlbldl" },
        new Pass { Min = 5, Max = 9, Symbol = 'd', Value = "dzxjdrftsprbldvddk" },
        new Pass { Min = 4, Max = 14, Symbol = 'q', Value = "wqsqqxtbfnckzqcqqqq" },
        new Pass { Min = 1, Max = 2, Symbol = 'v', Value = "lvdxdwpphqv" },
        new Pass { Min = 5, Max = 6, Symbol = 'z', Value = "zpzhzjzqtzh" },
        new Pass { Min = 3, Max = 4, Symbol = 'q', Value = "qqqlq" },
        new Pass { Min = 9, Max = 10, Symbol = 'v', Value = "svvvhvvvtv" },
        new Pass { Min = 3, Max = 12, Symbol = 'g', Value = "kjgmbzgklwfb" },
        new Pass { Min = 10, Max = 15, Symbol = 'v', Value = "vvddvvvrhvvmvwvvv" },
        new Pass { Min = 1, Max = 20, Symbol = 'j', Value = "kjjjjjjjjkjjpjjjjjjj" },
        new Pass { Min = 6, Max = 8, Symbol = 't', Value = "tttttdtt" },
        new Pass { Min = 11, Max = 12, Symbol = 'v', Value = "vvvvvqvvqvxvvv" },
        new Pass { Min = 12, Max = 13, Symbol = 'h', Value = "hnhshhhhshhhh" },
        new Pass { Min = 7, Max = 8, Symbol = 'z', Value = "vzzzzzrzzzfpz" },
        new Pass { Min = 7, Max = 8, Symbol = 'x', Value = "xkxhxxhn" },
        new Pass { Min = 4, Max = 7, Symbol = 'b', Value = "hbbzptb" },
        new Pass { Min = 5, Max = 9, Symbol = 'd', Value = "fddqjsdbj" },
        new Pass { Min = 3, Max = 10, Symbol = 'l', Value = "llllllglxslll" },
        new Pass { Min = 1, Max = 9, Symbol = 'b', Value = "dbsbbbbgbb" },
        new Pass { Min = 5, Max = 8, Symbol = 'n', Value = "dtnnsnnnn" },
        new Pass { Min = 7, Max = 16, Symbol = 'm', Value = "mmmmmmmmmmmmmmmsm" },
        new Pass { Min = 3, Max = 4, Symbol = 'f', Value = "nhwk" },
        new Pass { Min = 15, Max = 17, Symbol = 'w', Value = "wwfwwxwmwwwwwdswwwww" },
        new Pass { Min = 1, Max = 11, Symbol = 'l', Value = "llllllllllll" },
        new Pass { Min = 4, Max = 9, Symbol = 'c', Value = "cccccccchcc" },
        new Pass { Min = 2, Max = 3, Symbol = 'k', Value = "kkkkbskk" },
        new Pass { Min = 3, Max = 6, Symbol = 's', Value = "nssqtf" },
        new Pass { Min = 4, Max = 5, Symbol = 'm', Value = "mmrhm" },
        new Pass { Min = 9, Max = 11, Symbol = 'f', Value = "nfnsrfdfnfff" },
        new Pass { Min = 15, Max = 16, Symbol = 'k', Value = "kkkkkkkkkkkkkkzhk" },
        new Pass { Min = 6, Max = 9, Symbol = 'q', Value = "tzqqxqhnq" },
        new Pass { Min = 3, Max = 11, Symbol = 'k', Value = "kkkkkkkkkkck" },
        new Pass { Min = 2, Max = 5, Symbol = 'p', Value = "wmpgpmjmrqg" },
        new Pass { Min = 15, Max = 19, Symbol = 'r', Value = "rrrrrsrrrrrrhfrrjrr" },
        new Pass { Min = 4, Max = 10, Symbol = 'l', Value = "lllsldllll" },
        new Pass { Min = 4, Max = 7, Symbol = 's', Value = "sjhzqns" },
        new Pass { Min = 1, Max = 3, Symbol = 'n', Value = "nnknnp" },
        new Pass { Min = 13, Max = 14, Symbol = 'j', Value = "hjjgxjzjvjpxjj" },
        new Pass { Min = 4, Max = 5, Symbol = 'r', Value = "rrrgrrrrr" },
        new Pass { Min = 10, Max = 11, Symbol = 'p', Value = "ppptphpxkpppp" },
        new Pass { Min = 2, Max = 7, Symbol = 'j', Value = "fjsnxwpjgqnzjjj" },
        new Pass { Min = 6, Max = 8, Symbol = 'k', Value = "kdkkwnvkkkk" },
        new Pass { Min = 2, Max = 5, Symbol = 'q', Value = "qdqqjqqwq" },
        new Pass { Min = 5, Max = 7, Symbol = 'x', Value = "xdxddbcxvnxxxxhxxxq" },
        new Pass { Min = 2, Max = 6, Symbol = 'n', Value = "cnqlmrlwqhdbbvbnhskh" },
        new Pass { Min = 7, Max = 8, Symbol = 'z', Value = "zzzzzzzwz" },
        new Pass { Min = 6, Max = 8, Symbol = 'r', Value = "llrrtzrpr" },
        new Pass { Min = 1, Max = 7, Symbol = 'd', Value = "ddlddvmkddjpd" },
        new Pass { Min = 8, Max = 9, Symbol = 'v', Value = "vvvvvvvrkv" },
        new Pass { Min = 18, Max = 19, Symbol = 't', Value = "vtststttfmtqtmttdnz" },
        new Pass { Min = 3, Max = 9, Symbol = 'b', Value = "nbwbzntrb" },
        new Pass { Min = 3, Max = 4, Symbol = 'r', Value = "pzrrqqrj" },
        new Pass { Min = 5, Max = 9, Symbol = 'x', Value = "bvxxllwcf" },
        new Pass { Min = 4, Max = 6, Symbol = 'f', Value = "fxmlxf" },
        new Pass { Min = 11, Max = 15, Symbol = 'n', Value = "nnqnwnnnwnknnnnnfnn" },
        new Pass { Min = 9, Max = 11, Symbol = 'n', Value = "nnnnqnnnnnj" },
        new Pass { Min = 7, Max = 12, Symbol = 'k', Value = "kkkkkvjkkksskrkkk" },
        new Pass { Min = 2, Max = 3, Symbol = 'b', Value = "cbbvbv" },
        new Pass { Min = 3, Max = 6, Symbol = 'x', Value = "xxfldxxxc" },
        new Pass { Min = 6, Max = 11, Symbol = 'k', Value = "fkvvkkwkvkpjkjk" },
        new Pass { Min = 10, Max = 16, Symbol = 'f', Value = "ffffffmffffffffffff" },
        new Pass { Min = 7, Max = 8, Symbol = 'p', Value = "fppplpnc" },
        new Pass { Min = 11, Max = 20, Symbol = 'r', Value = "srrrfrrrrrrrrhrrbrrr" },
        new Pass { Min = 13, Max = 17, Symbol = 's', Value = "smssssssssssssssb" },
        new Pass { Min = 5, Max = 8, Symbol = 'q', Value = "fcqlqqqq" },
        new Pass { Min = 6, Max = 10, Symbol = 'g', Value = "rmpsgrlxcvgtggwgvk" },
        new Pass { Min = 13, Max = 15, Symbol = 'h', Value = "hhhhhhhhhcmfhhldhzh" },
        new Pass { Min = 5, Max = 10, Symbol = 'q', Value = "qqqqjqqqqqcq" },
        new Pass { Min = 5, Max = 9, Symbol = 'm', Value = "lmvcmmsznmmgmmmcs" },
        new Pass { Min = 5, Max = 6, Symbol = 'h', Value = "hhhbzr" },
        new Pass { Min = 3, Max = 4, Symbol = 'd', Value = "dzdg" },
        new Pass { Min = 11, Max = 14, Symbol = 'h', Value = "rfvjnjbzvrhthdxhv" },
        new Pass { Min = 14, Max = 19, Symbol = 'g', Value = "ggggggggggggggggggcg" },
        new Pass { Min = 6, Max = 7, Symbol = 'm', Value = "mmmmmphg" },
        new Pass { Min = 13, Max = 14, Symbol = 'p', Value = "ftzfrppkzrrpgp" },
        new Pass { Min = 12, Max = 16, Symbol = 'n', Value = "lxnnnnnngnnbnncnn" },
        new Pass { Min = 8, Max = 9, Symbol = 'c', Value = "dqgzbncfccrjtdkc" },
        new Pass { Min = 6, Max = 9, Symbol = 'r', Value = "jdrrfrtkmkfltkm" },
        new Pass { Min = 4, Max = 6, Symbol = 'g', Value = "dnggrr" },
        new Pass { Min = 3, Max = 4, Symbol = 's', Value = "ssssvs" },
        new Pass { Min = 18, Max = 19, Symbol = 'f', Value = "wffffffffsffffffffvf" },
        new Pass { Min = 6, Max = 10, Symbol = 'l', Value = "klllbxltll" },
        new Pass { Min = 6, Max = 7, Symbol = 'r', Value = "rbdgrrr" },
        new Pass { Min = 17, Max = 18, Symbol = 'l', Value = "vjplzpcftlkrllsbqlqg" },
        new Pass { Min = 3, Max = 9, Symbol = 'n', Value = "bqnnnnrbxkdsdwnvtwwh" },
        new Pass { Min = 1, Max = 2, Symbol = 'w', Value = "qwwt" },
        new Pass { Min = 5, Max = 18, Symbol = 'z', Value = "zzzzzzzzzzzzzzzzzlz" },
        new Pass { Min = 2, Max = 7, Symbol = 'n', Value = "nbnnnnnnn" },
        new Pass { Min = 14, Max = 15, Symbol = 'g', Value = "mcdcmxpxmgkqdhm" },
        new Pass { Min = 18, Max = 19, Symbol = 's', Value = "gsssssssssswssssssss" },
        new Pass { Min = 5, Max = 6, Symbol = 's', Value = "tptssvs" },
        new Pass { Min = 8, Max = 12, Symbol = 'c', Value = "cccnbcccmcctclccccx" },
        new Pass { Min = 6, Max = 15, Symbol = 't', Value = "tttttttttmttstf" },
        new Pass { Min = 5, Max = 6, Symbol = 'l', Value = "lllklq" },
        new Pass { Min = 7, Max = 9, Symbol = 'd', Value = "dqdcdcddxcddmdkrd" },
        new Pass { Min = 4, Max = 5, Symbol = 'r', Value = "rrvrxqnzrm" },
        new Pass { Min = 9, Max = 11, Symbol = 'p', Value = "pjpppppppppppppp" },
        new Pass { Min = 4, Max = 6, Symbol = 'v', Value = "vpvvvvv" },
        new Pass { Min = 6, Max = 9, Symbol = 'h', Value = "wwchhhgfh" },
        new Pass { Min = 10, Max = 11, Symbol = 'f', Value = "flfcjvtljftfffhff" },
        new Pass { Min = 6, Max = 7, Symbol = 'v', Value = "vvvvvvvv" },
        new Pass { Min = 12, Max = 15, Symbol = 'k', Value = "kjkkkktkkkkkzvn" },
        new Pass { Min = 6, Max = 9, Symbol = 'v', Value = "rsrvvgnwktwvvnvclvvc" },
        new Pass { Min = 2, Max = 12, Symbol = 'c', Value = "ccvqsctcwkmkqzc" },
        new Pass { Min = 16, Max = 18, Symbol = 'w', Value = "wwwwwwwwwwwwwwwwwwww" },
        new Pass { Min = 17, Max = 18, Symbol = 'g', Value = "ggzgggggggglggggsgg" },
        new Pass { Min = 13, Max = 18, Symbol = 'v', Value = "vvvvvnvvvgrvvkvtqv" },
        new Pass { Min = 5, Max = 11, Symbol = 'k', Value = "kkkkkkkkkkkkkkk" },
        new Pass { Min = 11, Max = 12, Symbol = 'f', Value = "ffffffffffvf" },
        new Pass { Min = 1, Max = 7, Symbol = 'h', Value = "rstpvhh" },
        new Pass { Min = 11, Max = 14, Symbol = 'l', Value = "lrnllwvlnflllfdfllt" },
        new Pass { Min = 5, Max = 7, Symbol = 'g', Value = "gcgjgrkgj" },
        new Pass { Min = 7, Max = 18, Symbol = 'z', Value = "zzzzzzgzztzzzzzzzxzz" },
        new Pass { Min = 17, Max = 18, Symbol = 'v', Value = "vvvvvvvvvvvvmvvvvvvv" },
        new Pass { Min = 16, Max = 18, Symbol = 'm', Value = "mmmmhmmmmmtmmmmvmx" },
        new Pass { Min = 1, Max = 3, Symbol = 'z', Value = "vzzzwz" },
        new Pass { Min = 5, Max = 6, Symbol = 'n', Value = "nnnhnq" },
        new Pass { Min = 8, Max = 15, Symbol = 'r', Value = "jsrprrrrmrrkgrkrr" },
        new Pass { Min = 2, Max = 12, Symbol = 'g', Value = "txwxcgwfqkfg" },
        new Pass { Min = 9, Max = 15, Symbol = 'l', Value = "ldlllllllllllll" },
        new Pass { Min = 3, Max = 5, Symbol = 'f', Value = "gfbsf" },
        new Pass { Min = 15, Max = 16, Symbol = 'v', Value = "vvhrnzxfvvvvcwjv" },
        new Pass { Min = 4, Max = 15, Symbol = 'c', Value = "cccmccccccccccccccc" },
        new Pass { Min = 7, Max = 13, Symbol = 'l', Value = "bwlzlxzllctjcf" },
        new Pass { Min = 1, Max = 3, Symbol = 'q', Value = "rsgtq" },
        new Pass { Min = 4, Max = 9, Symbol = 'n', Value = "npznnnvvnzg" },
        new Pass { Min = 3, Max = 7, Symbol = 'z', Value = "sqtczzfzzrzfz" },
        new Pass { Min = 2, Max = 3, Symbol = 'k', Value = "ckkrjnkglnz" },
        new Pass { Min = 9, Max = 10, Symbol = 'q', Value = "qqqqqqwqjqqfq" },
        new Pass { Min = 4, Max = 11, Symbol = 'v', Value = "vvvbvvvvvvnvvd" },
        new Pass { Min = 5, Max = 7, Symbol = 'n', Value = "lbwxnnnncnnwnv" },
        new Pass { Min = 8, Max = 9, Symbol = 'k', Value = "kgkkkkkjf" },
        new Pass { Min = 7, Max = 9, Symbol = 'l', Value = "llllllllll" },
        new Pass { Min = 15, Max = 19, Symbol = 'p', Value = "pppbpcppxcptppvmpppb" },
        new Pass { Min = 3, Max = 4, Symbol = 'm', Value = "fqmwcncsmp" }
    };
}